"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";

type Line={id:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;discount:number;netAmount:number;paymentStatus:string;paymentMethod:string|null;paidAmount:number;balanceAmount:number;subtotal:number};
type Data={bill:Bill;patient:{patientId:string;name:string;phone:string|null};visit:{id:number;tokenNumber:number;visitType:string;status:string;department:string|null}|null;lineItems:Line[]};
const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",IPD:"IPD",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",OTHER:"Other Service"}[x]||x);
export default function SelectedReview(){const s=useSearchParams();const billId=Number(s.get("billId")||0);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [discount,setDiscount]=useState("");const [pay,setPay]=useState("");const [method,setMethod]=useState("CASH");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init),d=await r.json();if(!r.ok)throw new Error(d.error||"Billing request failed.");return d};
 const load=async()=>{if(!billId)return;setLoading(true);setError("");try{setData(await run(`/api/billing-selected?billId=${billId}`))}catch(e){setError(e instanceof Error?e.message:"Unable to load selected-charge invoice.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[billId]);
 const payment=async()=>{if(!data)return;const amount=Number(pay);if(!Number.isFinite(amount)||amount<=0||amount>data.bill.balanceAmount){setError(amount===0?"Payment amount must be greater than ₹0.00.":"Enter a payment amount within the outstanding balance.");return}setLoading(true);setError("");try{const d=await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billId:data.bill.id,paidAmount:amount,paymentMethod:method})});setData(x=>x?{...x,bill:d.bill}:x);setPay("");setMessage(d.bill.paymentStatus==="PAID"?"Payment completed. Receipt is ready.":"Partial payment recorded.")}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.")}finally{setLoading(false)}};
 const applyDiscount=async()=>{if(!data)return;const value=Number(discount);if(!Number.isFinite(value)||value<0||value>data.bill.subtotal){setError("Enter a valid discount.");return}setLoading(true);try{const d=await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discount",billId:data.bill.id,discount:value})});setData(x=>x?{...x,bill:d.bill}:x);setMessage("Discount applied.")}catch(e){setError(e instanceof Error?e.message:"Unable to apply discount.")}finally{setLoading(false)}};
 const paid=data?.bill.paymentStatus==="PAID";
 if(!billId)return <main className="p-8">Invalid bill.</main>;
 return <main className="min-h-screen bg-[#fffaf0] p-4 text-[#172b3a] sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl space-y-5">
  <header className="rounded-[2rem] bg-gradient-to-br from-[#08483d] via-[#0d5b4c] to-[#176f5e] p-6 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.28em] text-[#f5d47b]">SAMS · Hospital Finance</p><h1 className="mt-2 text-3xl font-black">Selected Charges Review</h1><p className="mt-1 text-sm text-emerald-50">Selected Unpaid Charges → Invoice → Payment → Receipt</p></header>
  {data&&<><section className="grid gap-3 sm:grid-cols-3"><Card t="Patient" v={data.patient.name}/><Card t="HID" v={data.patient.patientId}/><Card t="Visit" v={data.visit?`#${data.visit.id} · Token #${data.visit.tokenNumber}`:"—"}/></section>
  <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">New Invoice</p><h2 className="text-2xl font-black text-[#0b2748]">{data.bill.billNumber}</h2><p className="mt-1 text-xs text-slate-500">This invoice contains only the charges selected from the Unpaid category.</p></div><span className={`rounded-full px-4 py-2 text-xs font-black ${paid?"bg-emerald-50 text-emerald-700":data.bill.paymentStatus==="PARTIAL"?"bg-amber-50 text-amber-700":"bg-red-50 text-red-700"}`}>{paid?"PAID":data.bill.paymentStatus==="PARTIAL"?"PARTIALLY UNPAID":"UNPAID"}</span></div>
  <div className="mt-5 space-y-2">{data.lineItems.map(l=><div key={l.id} className="flex items-center justify-between gap-4 rounded-xl border border-[#eee5d4] bg-[#fffdf8] p-4"><div><p className="font-black text-[#0b2748]">{l.description}</p><p className="mt-1 text-[10px] text-slate-400">{label(l.serviceType)} · Qty {l.quantity} × {money(l.unitPrice)}</p></div><b>{money(l.amount)}</b></div>)}</div>
  <div className="mt-5 ml-auto max-w-sm space-y-3"><Row t="Subtotal" v={money(data.bill.subtotal)}/><div className="flex items-center justify-between gap-3"><span>Discount</span><div className="flex gap-2"><input value={discount} onChange={e=>setDiscount(e.target.value)} disabled={loading||paid} placeholder="₹" className="w-24 rounded-lg border px-2 py-1"/><button onClick={()=>void applyDiscount()} disabled={loading||paid||discount===""} className="rounded-lg bg-amber-500 px-3 py-1 text-xs font-black text-white disabled:opacity-40">Apply</button></div></div><Row t="Net Amount" v={money(data.bill.netAmount)} strong/><Row t="Paid" v={money(data.bill.paidAmount)}/><Row t="Outstanding" v={money(data.bill.balanceAmount)} danger/></div></section>
  {!paid&&<section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Payment</p><div className="mt-3 grid gap-3 lg:grid-cols-[1fr_180px_auto]"><input value={pay} onChange={e=>setPay(e.target.value)} type="number" min="0" step="0.01" placeholder="Payment amount ₹" className="rounded-xl border px-4 py-3"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border px-3 py-3 font-bold"><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select><button onClick={()=>void payment()} disabled={loading||!pay} className="rounded-xl bg-[#0d5b4c] px-6 py-3 font-black text-white disabled:opacity-40">Record Payment</button></div></section>}
  {paid&&<section className="rounded-[1.5rem] border border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-emerald-700">Payment Complete</p><h3 className="text-xl font-black text-emerald-900">Receipt {data.bill.receiptNumber||"generated"}</h3></div>{data.visit&&<Link href={`/billing/receipt?visitId=${data.visit.id}`} target="_blank" className="rounded-xl bg-[#0d5b4c] px-5 py-3 text-center text-xs font-black text-white">Open / Print Receipt →</Link>}</div></section>}
  <Link href="/billing" className="inline-flex rounded-xl border border-[#eadfca] bg-white px-5 py-3 text-xs font-black text-[#0d5b4c]">← Back to Patient Charges</Link></>}
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading&&!data&&<div className="rounded-2xl bg-white p-10 text-center font-bold">Loading invoice…</div>}
 </div></main>}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-[#eadfca] bg-white p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t}</p><p className="mt-1 font-black text-[#0b2748]">{v}</p></div>}
function Row({t,v,strong,danger}:{t:string;v:string;strong?:boolean;danger?:boolean}){return <div className={`flex justify-between ${strong?"border-t pt-3 text-lg font-black":"text-sm"} ${danger?"text-red-700":""}`}><span>{t}</span><span>{v}</span></div>}
