"use client";
import { FormEvent, Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";

function AdminLoginContent(){
  const params=useSearchParams();
  const next=params.get("next")||"/admin";
  const[username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/admin/gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok){setError(d.error||"Admin authentication failed.");return}window.location.href=next}catch{setError("Unable to authenticate Admin.")}finally{setLoading(false)}}
  return <main className="flex min-h-screen items-center justify-center bg-[#080d16] px-5 text-slate-100"><div className="w-full max-w-md rounded-[2rem] border border-[#c9a85c]/25 bg-[#101925] p-8 shadow-[0_30px_100px_rgba(0,0,0,.5)]"><div className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-[#c9a85c]/30 bg-[#c9a85c]/10 text-2xl font-black text-[#e0c27a]">S</div><p className="mt-5 text-[9px] font-black uppercase tracking-[.3em] text-[#d9bb72]">SAMS · Restricted Area</p><h1 className="mt-2 text-3xl font-black">Admin Authentication</h1><p className="mt-2 text-sm leading-6 text-slate-400">Enter the Admin User ID and password to continue to the protected administration workspace.</p></div><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="text-[10px] font-black uppercase tracking-wider text-slate-500">Admin User ID</span><input required value={username} onChange={e=>setUsername(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1420] px-4 py-3 text-sm text-white outline-none focus:border-[#c9a85c]" autoComplete="username"/></label><label className="block"><span className="text-[10px] font-black uppercase tracking-wider text-slate-500">Admin Password</span><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1420] px-4 py-3 text-sm text-white outline-none focus:border-[#c9a85c]" autoComplete="current-password"/></label>{error&&<p className="rounded-xl bg-red-400/10 px-4 py-3 text-xs font-bold text-red-300">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#c9a85c] px-4 py-3 text-xs font-black text-[#10151d] disabled:opacity-50">{loading?"Authenticating…":"Enter Administration"}</button></form><p className="mt-5 text-center text-[10px] text-slate-500">This additional Admin gate is tied to the current SAMS user session.</p></div></main>
}

export default function AdminLoginPage(){
  return <Suspense fallback={<main className="flex min-h-screen items-center justify-center bg-[#080d16] text-slate-100">Loading Admin Authentication…</main>}><AdminLoginContent/></Suspense>;
}
