"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import ClinicalLeadCard from "@/components/ClinicalLeadCard";

export default function HomeV2() {
 const [lang,setLang]=useState<"en"|"hi">("en"); const hi=lang==="hi";
 return <main className="min-h-screen bg-[#e8d6b3] text-[#10233f]">
  <header className="sticky top-0 z-30 min-h-[104px] border-b border-[#ded5c5] bg-[#fbf8f1]/95 shadow-md backdrop-blur-xl"><div className="mx-auto flex min-h-[104px] max-w-[1400px] items-center justify-between gap-5 px-5 py-4 sm:px-8 sm:py-5"><Link href="/home-v2" className="flex min-w-0 items-center gap-4 sm:gap-5"><Image src="/serawat-logo.png" alt="SAMS" width={112} height={68} className="h-16 w-auto shrink-0 object-contain sm:h-[72px]" priority/><div className="min-w-0"><p className="font-serif text-3xl font-bold leading-none text-[#082b61] sm:text-4xl">SAMS</p><p className="mt-2 max-w-[650px] text-[10px] font-black uppercase leading-4 tracking-[0.13em] text-[#082b61] sm:text-xs sm:tracking-[0.16em]">Serawat Advanced Multispecialty Joint &amp; Spine Center</p></div></Link><div className="flex shrink-0 items-center gap-2 sm:gap-3"><div className="flex rounded-full border border-[#ded5c5] bg-[#f5efe3] p-1 text-[10px] font-black sm:text-xs"><button onClick={()=>setLang("en")} className={`rounded-full px-3 py-1.5 sm:px-4 sm:py-2 ${!hi?"bg-[#082b61] text-white":"text-slate-500"}`}>EN</button><button onClick={()=>setLang("hi")} className={`rounded-full px-3 py-1.5 sm:px-4 sm:py-2 ${hi?"bg-[#082b61] text-white":"text-slate-500"}`}>हिन्दी</button></div><Link href="/dashboard" className="hidden rounded-xl border border-[#d6dce7] bg-white px-4 py-2.5 text-xs font-black text-[#082b61] shadow-sm transition hover:border-[#082b61] sm:block">Command Center ↗</Link></div></div></header>
  <section className="relative overflow-hidden bg-[#243746] text-white"><div className="absolute -right-40 -top-40 h-[260px] w-[260px] rounded-full bg-blue-400/20 blur-3xl"/><div className="absolute -bottom-40 left-1/3 h-[220px] w-[220px] rounded-full bg-cyan-300/10 blur-3xl"/><div className="relative mx-auto max-w-[1400px] px-5 py-7 sm:px-8 sm:py-9 lg:py-10"><div className="max-w-4xl"><p className="font-serif text-[11px] font-semibold uppercase tracking-[0.18em] text-[#c5a7f2] sm:text-xs sm:tracking-[0.22em]">SAMS Serawat Advanced Multispecialty Joint &amp; Spine Center</p><h1 className="mt-3 font-serif text-4xl font-medium leading-[1] tracking-[-0.03em] sm:text-5xl">{hi?<>एक छत के नीचे।<br/><em className="text-blue-300">विशेषज्ञ देखभाल, बेहतर परिणाम।</em></>:<>Multispecialty care.<br/><em className="text-blue-300">One connected journey.</em></>}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100/80 sm:text-base">{hi?"दर्द, जोड़ों, रीढ़, न्यूरो और पुनर्वास के लिए विभिन्न विशेषज्ञताओं को एक समन्वित, व्यक्तिगत देखभाल योजना में जोड़ना।":"Bringing multiple specialist disciplines together for personalised care across pain, joints, spine, neurological conditions and rehabilitation."}</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/experts" className="mt-3 inline-flex rounded-xl border border-white px-7 py-4 text-sm font-semibold text-white transition hover:bg-white hover:text-[#082b61] sm:mt-0 sm:ml-3">Meet Our Experts Team</Link><a href="#director" className="rounded-xl border-2 border-white bg-[#314b5d] px-5 py-3 text-sm font-black text-white">{hi?"हमारे निदेशक से मिलें":"Meet Our Director"} ↓</a></div></div></div></section>
  <section id="director" className="border-b border-[#cfd4bd] bg-[#e8eadb]"><div className="mx-auto max-w-[1200px] px-5 py-9 sm:px-8 sm:py-12"><div className="mb-6 flex justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#58703b]">Meet Our Director</p><h2 className="mt-2 font-serif text-3xl font-medium text-[#082b61] sm:text-4xl">Meet Our Director</h2></div></div><div className="mx-auto max-w-[1050px]"><ClinicalLeadCard/></div></div></section>
  <section className="border-y border-[#ded5c5] bg-[#fbf7ee]"><div className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 sm:py-14"><div className="grid gap-7 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#0b63ce]">A Message From Director</p><h2 className="mt-3 font-serif text-4xl font-medium leading-tight text-[#082b61] sm:text-5xl">{hi?"हर मरीज की कहानी अलग है।":"Every patient has a different story."}</h2></div><div className="border-l border-[#ded5c5] pl-5 sm:pl-8"><p className="whitespace-pre-line font-serif text-xl leading-[1.5] text-[#203b5d] sm:text-2xl">{hi?"SAMS में हम सबसे पहले आपकी कहानी समझते हैं —\nवह दर्द जो आपकी रोज़मर्रा की ज़िंदगी को प्रभावित करता है, जिससे आपकी चलने-फिरने की क्षमता कम हो गई है, और वह चिंता जो इस अनिश्चितता से पैदा होती है कि आप फिर से कब बेहतर महसूस करेंगे।\n\nहम यह समझने की कोशिश करते हैं कि आपकी समस्या आपके लिए वास्तव में क्या मायने रखती है — आपके काम, आपके परिवार, आपकी आत्मनिर्भरता और उन गतिविधियों के लिए जिन्हें आप फिर से करना चाहते हैं।\n\nहमारा उद्देश्य केवल आपकी बीमारी या निदान का इलाज करना नहीं है, बल्कि आपको अधिक आत्मविश्वास के साथ बेहतर चलने-फिरने, बेहतर कार्य करने और उस जीवन में वापस लौटने में मदद करना है जो आपके लिए महत्वपूर्ण है।":"At SAMS, we understand your story first —\nthe pain that limits your everyday life, the movement you have lost, and the uncertainty that comes with not knowing when you will feel better.\n\nWe listen to what your condition means to you — your work, your family, your independence and the activities you want to return to.\n\nOur goal is not simply to treat a diagnosis, but to help you move with greater confidence, function better and get back to the life that matters to you."}</p><p className="mt-4 text-xs font-black uppercase tracking-[0.16em] text-slate-500">— Dr. Suraj Serawat</p></div></div></div></section>
  <section className="border-y border-[#ded5c5] bg-[#fbf8f1]"><div className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 sm:py-14"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#0b63ce]">Why SAMS</p><h2 className="mt-3 font-serif text-3xl font-medium leading-tight text-[#58703b] sm:text-4xl">{hi?"एक साथ कई विशेषज्ञताएँ। आपके लिए एक समन्वित योजना।":"Multispecialty expertise. One coordinated plan for you."}</h2><p className="mt-4 text-base leading-7 text-slate-500">SAMS connects specialist assessment, pain medicine, musculoskeletal and joint care, spine care, neurological rehabilitation and functional recovery around one personalised patient journey.</p></div></div></section>
  <section className="bg-[#071f46] text-white"><div className="mx-auto max-w-[1200px] px-5 py-[42px] text-center sm:px-8 sm:py-[62px]"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#e8d6b3]">Your next step</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-3xl font-medium leading-tight text-[#f6e7c4] sm:text-4xl">{hi?"बेहतर गति की शुरुआत यहीं से करें।":"Your journey toward better movement starts here."}</h2><Link href="/appointments" className="group mt-7 inline-flex items-center gap-3 rounded-2xl border border-[#e8d6b3] bg-gradient-to-r from-[#f3dfad] via-[#e8d6b3] to-[#c9a45c] px-7 py-3.5 font-serif text-base font-bold text-[#071f46] shadow-[0_8px_30px_rgba(232,214,179,0.22)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_12px_36px_rgba(232,214,179,0.32)] sm:px-9 sm:py-4 sm:text-lg"><span aria-hidden="true">✦</span><span>Book Your Appointment</span><span className="text-sm transition-transform duration-300 group-hover:translate-x-1" aria-hidden="true">→</span></Link></div></section>
 </main>;
}
