"use client";

import { FormEvent, useState } from "react";
import Navigation from "@/components/Navigation";
import Sidebar from "@/components/Sidebar";
import { useRouter } from "next/navigation";

export default function NewPatientPage() {
  const router = useRouter();

    const [saving, setSaving] = useState(false);
      const [error, setError] = useState("");

        async function handleSubmit(event: FormEvent<HTMLFormElement>) {
            event.preventDefault();

                setSaving(true);
                    setError("");

                        const formData = new FormData(event.currentTarget);

                            const data = {
                                  firstName: String(formData.get("firstName") || ""),
                                        lastName: String(formData.get("lastName") || ""),
                                              dateOfBirth: String(formData.get("dateOfBirth") || ""),
                                                    gender: String(formData.get("gender") || ""),
                                                          phone: String(formData.get("phone") || ""),
                                                                address: String(formData.get("address") || ""),
                                                                    };

                                                                        try {
                                                                              const response = await fetch("/api/patients", {
                                                                                      method: "POST",
                                                                                              headers: {
                                                                                                        "Content-Type": "application/json",
                                                                                                                },
                                                                                                                        body: JSON.stringify(data),
                                                                                                                              });

                                                                                                                                    const result = await response.json();

                                                                                                                                          if (!response.ok) {
                                                                                                                                                  throw new Error(result.error || "Unable to register patient.");
                                                                                                                                                        }

                                                                                                                                                              router.push("/patients/list");
                                                                                                                                                                  } catch (err) {
                                                                                                                                                                        setError(
                                                                                                                                                                                err instanceof Error ? err.message : "Unable to register patient."
                                                                                                                                                                                      );
                                                                                                                                                                                            setSaving(false);
                                                                                                                                                                                                }
                                                                                                                                                                                                  }

                                                                                                                                                                                                    return (
                                                                                                                                                                                                        <main>
                                                                                                                                                                                                              <Sidebar />

                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                            <Navigation />

                                                                                                                                                                                                                                    <header>
                                                                                                                                                                                                                                              <h1>Register New Patient</h1>
                                                                                                                                                                                                                                                        <p>Enter patient information</p>
                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                              <label htmlFor="firstName">First Name</label>
                                                                                                                                                                                                                                                                                                          <input id="firstName" name="firstName" type="text" required />
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                          <label htmlFor="lastName">Last Name</label>
                                                                                                                                                                                                                                                                                                                                                      <input id="lastName" name="lastName" type="text" required />
                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="dateOfBirth">Date of Birth</label>
                                                                                                                                                                                                                                                                                                                                                                                                  <input id="dateOfBirth" name="dateOfBirth" type="date" />
                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <label htmlFor="gender">Gender</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <select id="gender" name="gender">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="">Select</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="male">Male</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="female">Female</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="other">Other</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label htmlFor="phone">Phone</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input id="phone" name="phone" type="tel" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="address">Address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea id="address" name="address" rows={3} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error && <p>{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={saving}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {saving ? "Registering..." : "Register Patient"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }