import Link from "next/link";
import Navigation from "@/components/Navigation";

const cards = [
  { title: "Billing & Revenue", eyebrow: "FINANCE CONTROL", description: "Executive billing, collections, receivables, revenue trends and payment performance.", href: "/admin/billing", primary: "Open Finance", icon: "₹" },
  { title: "Doctors / Experts Team", eyebrow: "TEAM MANAGEMENT", description: "Add, edit, update profiles and manage doctors and experts displayed on the public Experts Team page.", href: "/settings#experts-team", primary: "Manage Team", icon: "✚" },
  { title: "Settings", eyebrow: "SYSTEM CONTROL", description: "Hospital configuration, users, preferences and security controls.", href: "/settings", primary: "Open Settings", icon: "⚙" },
  { title: "Investigation Master", eyebrow: "CLINICAL MASTER DATA", description: "Maintain investigation names, categories, biological/reference values and rates used across clinical and billing workflows.", href: "/investigation-master", primary: "Manage Master", icon: "⌁" },
  { title: "Master Approvals", eyebrow: "ADMIN APPROVAL", description: "Review and approve or reject proposed Investigation Master changes before they become live.", href: "/admin/investigation-master-approvals", primary: "Review Requests", icon: "✓", featured: true },
];

export default function AdminPage() {
  return (
    <main className="min-h-screen bg-[#080d16] text-slate-100"><Navigation /><div className="relative min-h-[calc(100vh-76px)] overflow-hidden bg-[#080d16]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_8%,rgba(201,168,92,.10),transparent_27%),radial-gradient(circle_at_88%_18%,rgba(38,107,184,.14),transparent_30%),linear-gradient(135deg,#080d16_0%,#0b1320_52%,#07101b_100%)]" /><div className="relative mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-10 lg:py-10">
      <header className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#101925]/90 shadow-[0_30px_100px_rgba(0,0,0,.42)]"><div className="relative grid gap-10 p-7 sm:p-10 lg:grid-cols-[1fr_auto] lg:p-12"><div><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-[#c9a85c]/30 bg-[#c9a85c]/10 text-xl font-black text-[#e0c27a]">S</div><div><p className="text-[9px] font-black uppercase tracking-[.34em] text-[#d9bb72]">SAMS · Executive Administration</p><p className="mt-1 text-[10px] font-semibold tracking-wide text-slate-400">Restricted management workspace</p></div></div><h1 className="mt-7 text-4xl font-black tracking-[-.045em] text-white sm:text-5xl lg:text-6xl">Administration</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">The executive control centre for hospital finance, team management, system configuration and clinical master data.</p><div className="mt-7 flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/[.07] px-3.5 py-2 text-[10px] font-black uppercase tracking-wider text-emerald-300"><i className="h-1.5 w-1.5 rounded-full bg-emerald-400" />System online</span><span className="rounded-full border border-white/10 bg-white/[.035] px-3.5 py-2 text-[10px] font-bold tracking-wide text-slate-400">Admin access</span></div></div><div className="flex items-end lg:justify-end"><div className="min-w-[230px] rounded-2xl border border-white/10 bg-black/20 p-5"><p className="text-[9px] font-black uppercase tracking-[.24em] text-slate-500">CONTROL CENTRE</p><p className="mt-2 text-lg font-black text-white">SAMS Administration</p><div className="mt-4 h-px bg-white/10" /><div className="mt-4 flex items-center justify-between text-[10px]"><span className="text-slate-500">Workspace</span><b className="text-[#d9bb72]">SECURE</b></div></div></div></div></header>
      <section className="mt-8"><div className="mb-4"><p className="text-[9px] font-black uppercase tracking-[.3em] text-[#c9a85c]">Executive Workspace</p><h2 className="mt-1 text-2xl font-black tracking-tight text-white">Management Controls</h2></div><div className="grid gap-5 lg:grid-cols-3">{cards.map((card) => <div key={card.href} className={`group relative overflow-hidden rounded-[1.7rem] border p-6 transition duration-300 hover:-translate-y-1 hover:shadow-[0_25px_70px_rgba(0,0,0,.35)] ${card.featured ? "border-[#c9a85c]/25 bg-[linear-gradient(145deg,#17150f,#111a27_72%)]" : "border-white/10 bg-white/[.045] hover:border-white/20 hover:bg-white/[.07]"}`}><div className={`absolute inset-x-0 top-0 h-px ${card.featured ? "bg-gradient-to-r from-transparent via-[#d9bb72] to-transparent" : "bg-gradient-to-r from-transparent via-white/20 to-transparent"}`} /><div className="flex items-start justify-between gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06] text-xl font-black text-slate-200">{card.icon}</div><span className="rounded-full border border-white/10 bg-black/20 px-2.5 py-1 text-[8px] font-black tracking-[.16em] text-slate-500">{card.eyebrow}</span></div><h3 className="mt-7 text-xl font-black tracking-tight text-white">{card.title}</h3><p className="mt-2 min-h-[48px] text-xs leading-5 text-slate-400">{card.description}</p><div className="mt-6 border-t border-white/10 pt-4"><Link href={card.href} className={`block rounded-xl px-3 py-2.5 text-center text-[9px] font-black uppercase tracking-wider transition ${card.featured ? "bg-[#c9a85c] text-[#10151d] hover:bg-[#e0c27a]" : "bg-white/[.09] text-white hover:bg-white/[.15]"}`}>{card.primary}</Link></div></div>)}</div></section>
      <footer className="mt-8 border-t border-white/10 py-5 text-[9px] font-bold uppercase tracking-[.2em] text-slate-600">SAMS · Secure Administration · Finance · Team · Configuration · Master Data · Approvals</footer>
    </div></div></main>
  );
}
