"use client";

import Image from "next/image";
import Link from "next/link";
import ClinicalLeadCard from "@/components/ClinicalLeadCard";
import { useState } from "react";

const fields = [
  ["01","🦵","Musculoskeletal & Joint","मस्क्युलोस्केलेटल एवं जोड़"],["02","🦴","Spine Related","रीढ़ से संबंधित"],["03","🧠","Brain Related","मस्तिष्क से संबंधित"],["04","⚡","Peripheral Nerve Related","पेरिफेरल नर्व से संबंधित"],["05","👶","Paediatric Rehabilitation","बाल पुनर्वास"],["06","🧠","Neuro Rehabilitation","न्यूरो पुनर्वास"],["07","♿","Spinal Cord Rehabilitation","स्पाइनल कॉर्ड पुनर्वास"],["08","🎯","Other Specialized Rehabilitation","अन्य विशेष पुनर्वास"],
];

export default function HomeV2() {
 const [lang,setLang]=useState<"en"|"hi">("en"); const hi=lang==="hi";
 return <main className="min-h-screen bg-[#f5efe3] text-[#10233f]">
  <header className="sticky top-0 z-30 border-b border-[#ded5c5] bg-[#fbf8f1]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-3 sm:px-8"><Link href="/home-v2" className="flex items-center gap-3"><Image src="/serawat-logo.png" alt="SAMS" width={76} height={44} className="h-11 w-auto object-contain" priority/><div><p className="font-serif text-xl font-bold text-[#082b61]">SAMS</p><p className="hidden text-[9px] font-bold uppercase tracking-[0.16em] text-slate-500 sm:block">Serawat Advanced Musculoskeletal, Joint & Spine Centre</p></div></Link><div className="flex items-center gap-3"><div className="flex rounded-full border border-[#ded5c5] bg-[#f5efe3] p-1 text-[10px] font-black"><button onClick={()=>setLang("en")} className={`rounded-full px-3 py-1.5 ${!hi?"bg-[#082b61] text-white":"text-slate-500"}`}>EN</button><button onClick={()=>setLang("hi")} className={`rounded-full px-3 py-1.5 ${hi?"bg-[#082b61] text-white":"text-slate-500"}`}>हिन्दी</button></div><Link href="/dashboard" className="hidden rounded-xl border border-[#d6dce7] bg-white px-4 py-2.5 text-xs font-black text-[#082b61] sm:block">Command Center ↗</Link></div></div></header>
  <section className="relative overflow-hidden bg-[#243746] text-white"><div className="absolute -right-40 -top-40 h-[260px] w-[260px] rounded-full bg-blue-400/20 blur-3xl"/><div className="absolute -bottom-40 left-1/3 h-[220px] w-[220px] rounded-full bg-cyan-300/10 blur-3xl"/><div className="relative mx-auto max-w-[1400px] px-5 py-7 sm:px-8 sm:py-9 lg:py-10"><div className="max-w-4xl"><p className="font-serif text-[11px] font-semibold uppercase tracking-[0.18em] text-[#c5a7f2] sm:text-xs sm:tracking-[0.22em]">Serawat Advanced Musculoskeletal, Joint & Spine Centre</p><h1 className="mt-3 font-serif text-4xl font-medium leading-[1] tracking-[-0.03em] sm:text-5xl">{hi?<>दर्द से आगे।<br/><em className="text-blue-300">बेहतर जीवन की ओर।</em></>:<>Advanced care for<br/><em className="text-blue-300">pain, movement & recovery.</em></>}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100/80 sm:text-base">{hi?"दर्द, गतिशीलता और पुनर्वास के लिए विशेषज्ञ, व्यक्तिगत और उद्देश्यपूर्ण देखभाल।":"Specialized, personalised care for pain, movement, function and recovery — bringing specialist rehabilitation together under one roof."}</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/patients" className="rounded-xl bg-[#0b63ce] px-5 py-3 text-sm font-black text-white shadow-xl hover:bg-[#0957b4]">{hi?"परामर्श शुरू करें":"Begin Your Consultation"} →</Link>
        <Link
          href="/experts"
          className="mt-3 inline-flex rounded-xl border border-white px-7 py-4 text-sm font-semibold text-white transition hover:bg-white hover:text-[#082b61] sm:mt-0 sm:ml-3"
        >
          Meet Our Experts Team
        </Link><a href="#doctor" className="rounded-xl border-2 border-white bg-[#314b5d] px-5 py-3 text-sm font-black text-white">{hi?"डॉक्टर से मिलें":"Meet Your Specialist"} ↓</a></div></div></div></section>
  <section id="doctor" className="border-b border-[#cfd4bd] bg-[#e8eadb]"><div className="mx-auto max-w-[1200px] px-5 py-9 sm:px-8 sm:py-12"><div className="mb-6 flex justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#58703b]">Meet the Clinical Lead</p><h2 className="mt-2 font-serif text-3xl font-medium text-[#082b61] sm:text-4xl">Meet the Clinical Lead</h2></div></div><div className="mx-auto max-w-[1050px]"><ClinicalLeadCard/></div></div></section>
  <section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 sm:py-14"><div className="grid gap-7 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#0b63ce]">A message from your doctor</p><h2 className="mt-3 font-serif text-4xl font-medium leading-tight text-[#082b61] sm:text-5xl">{hi?"हर मरीज की कहानी अलग है।":"Every patient has a different story."}</h2></div><div className="border-l border-[#ded5c5] pl-5 sm:pl-8"><p className="whitespace-pre-line font-serif text-xl leading-[1.5] text-[#203b5d] sm:text-2xl">{hi?"SAMS में हम सबसे पहले आपकी कहानी समझते हैं —\nवह दर्द जो आपकी रोज़मर्रा की ज़िंदगी को प्रभावित करता है, जिससे आपकी चलने-फिरने की क्षमता कम हो गई है, और वह चिंता जो इस अनिश्चितता से पैदा होती है कि आप फिर से कब बेहतर महसूस करेंगे।\n\nहम यह समझने की कोशिश करते हैं कि आपकी समस्या आपके लिए वास्तव में क्या मायने रखती है — आपके काम, आपके परिवार, आपकी आत्मनिर्भरता और उन गतिविधियों के लिए जिन्हें आप फिर से करना चाहते हैं।\n\nहमारा उद्देश्य केवल आपकी बीमारी या निदान का इलाज करना नहीं है, बल्कि आपको अधिक आत्मविश्वास के साथ बेहतर चलने-फिरने, बेहतर कार्य करने और उस जीवन में वापस लौटने में मदद करना है जो आपके लिए महत्वपूर्ण है।":"At SAMS, we understand your story first —\nthe pain that limits your everyday life, the movement you have lost, and the uncertainty that comes with not knowing when you will feel better.\n\nWe listen to what your condition means to you — your work, your family, your independence and the activities you want to return to.\n\nOur goal is not simply to treat a diagnosis, but to help you move with greater confidence, function better and get back to the life that matters to you."}</p><p className="mt-4 text-xs font-black uppercase tracking-[0.16em] text-slate-500">— Dr. Suraj Serawat</p></div></div></section>
  <section className="border-y border-[#ded5c5] bg-[#fbf8f1]"><div className="mx-auto max-w-[1200px] px-5 py-10 sm:px-8 sm:py-14"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#0b63ce]">Why SAMS</p><h2 className="mt-3 font-serif text-3xl font-medium leading-tight text-[#58703b] sm:text-4xl">{hi?"देखभाल जो निदान से आगे देखती है।":"Care that sees beyond the diagnosis."}</h2><p className="mt-4 text-base leading-7 text-slate-500">SAMS brings specialist assessment, pain medicine, rehabilitation and functional recovery together around one personalised plan.</p></div></div></section>
  <section className="mx-auto max-w-[1400px] px-5 py-16 sm:px-8 sm:py-24"><div><p className="text-[10px] font-black uppercase tracking-[0.24em] text-[#0b63ce]">Our areas of expertise</p><h2 className="mt-4 whitespace-nowrap font-serif text-3xl font-medium text-[#7a4f2d] sm:text-4xl lg:text-5xl">{hi?"पुनर्वास विशेषज्ञता का व्यापक दायरा":"Expertise across the spectrum of rehabilitation."}</h2><p className="mt-3 text-sm text-slate-500">From pain and joint care to neurological, paediatric and spinal rehabilitation — specialised care, connected.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{fields.map(([n,icon,en,hin])=><article key={n} className="rounded-[1.75rem] border border-[#ded5c5] bg-[#fbf8f1] p-6 shadow-sm"><span className="font-serif text-3xl text-[#0b63ce]/70">{n}</span><h3 className="mt-7 flex items-center gap-2 font-serif text-2xl font-medium text-[#082b61]"><span>{icon}</span>{hi?hin:en}</h3><p className="mt-4 text-xs leading-6 text-slate-500">Specialised assessment, treatment and rehabilitation tailored to individual goals.</p></article>)}</div></section>
  <section className="bg-[#071f46] text-white"><div className="mx-auto max-w-[1200px] px-5 py-16 text-center sm:px-8 sm:py-24"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-blue-300">Your next step</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-3xl font-medium leading-tight text-[#a8d9e6] sm:text-4xl">{hi?"बेहतर गति की शुरुआत यहीं से करें।":"Your journey toward better movement starts here."}</h2><Link href="/patients" className="mt-8 inline-flex rounded-xl bg-white px-7 py-4 text-sm font-black text-[#082b61]">Start Your Consultation →</Link></div></section>
 </main>;
}
