"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Department={id:number;name:string;code?:string};
type Doctor={id:number;name:string;departmentId?:number|null};
type Appointment={id:number;appointmentNo:string;appointmentDate:string;appointmentTime:string;source:string;status:string};
type Visit={id:number;tokenNumber:number;visitType:string;status:string;queuePriority:number;appointmentSlotMinutes:number|null;appointment?:Appointment|null;patient:{id:number;patientId:string;firstName:string;lastName:string}};
const STORAGE_KEY="sams-opd-queue-desk";
const statusOptions=(status:string)=>status==="WAITING"?["CALL_PATIENT","START_CONSULTATION","NO_SHOW","REQUEUE"]:status==="IN_CONSULTATION"?["COMPLETE_CONSULTATION"]:status==="COMPLETED"?["VIEW_STATUS"]:["REQUEUE"];
const label=(x:string)=>({CALL_PATIENT:"Call Patient",START_CONSULTATION:"Start Consultation",NO_SHOW:"Mark No-Show",REQUEUE:"Re-queue",COMPLETE_CONSULTATION:"Complete Consultation",VIEW_STATUS:"View Status"}[x]||x);

export default function OPDQueuePage(){
 const[departments,setDepartments]=useState<Department[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[departmentId,setDepartmentId]=useState(""),[doctorId,setDoctorId]=useState(""),[department,setDepartment]=useState<Department|null>(null),[doctor,setDoctor]=useState<Doctor|null>(null),[visits,setVisits]=useState<Visit[]>([]),[loading,setLoading]=useState(true),[loadingDepartments,setLoadingDepartments]=useState(true),[loadingDoctors,setLoadingDoctors]=useState(false),[error,setError]=useState(""),[actionId,setActionId]=useState<number|null>(null);
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/departments",{cache:"no-store"}),data=await r.json();if(!r.ok)throw Error(data?.error||"Unable to load departments.");setDepartments(Array.isArray(data)?data:[]);try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");if(s.departmentId)setDepartmentId(String(s.departmentId));if(s.doctorId)setDoctorId(String(s.doctorId))}catch{}}catch(e){setError(e instanceof Error?e.message:"Unable to load departments.")}finally{setLoadingDepartments(false)}})()},[]);
 useEffect(()=>{if(!departmentId){setDoctors([]);setDoctorId("");return}(async()=>{setLoadingDoctors(true);try{const r=await fetch(`/api/doctors?departmentId=${departmentId}`,{cache:"no-store"}),data=await r.json();if(!r.ok)throw Error(data?.error||"Unable to load consultants.");const rows=Array.isArray(data)?data:[];setDoctors(rows);if(doctorId&&!rows.some((d:Doctor)=>String(d.id)===doctorId))setDoctorId("")}catch(e){setDoctors([]);setError(e instanceof Error?e.message:"Unable to load consultants")}finally{setLoadingDoctors(false)}})()},[departmentId]);
 async function loadQueue(){if(!departmentId||!doctorId){setVisits([]);return}setLoading(true);try{const r=await fetch(`/api/opd/queue?departmentId=${departmentId}&doctorId=${doctorId}`,{cache:"no-store"}),data=await r.json();if(!r.ok)throw Error(data?.error||"Unable to load OPD queue.");setDepartment(data.department||null);setDoctor(data.doctor||null);setVisits(Array.isArray(data.visits)?data.visits:[]);setError("")}catch(e){setVisits([]);setError(e instanceof Error?e.message:"Unable to load OPD queue")}finally{setLoading(false)}}
 useEffect(()=>{if(!departmentId||!doctorId){setVisits([]);setLoading(false);return}localStorage.setItem(STORAGE_KEY,JSON.stringify({departmentId,doctorId}));loadQueue()},[departmentId,doctorId]);
 async function action(v:Visit,a:string){setActionId(v.id);setError("");try{if(a==="START_CONSULTATION"){await updateStatus(v.id,"IN_CONSULTATION");window.location.href=`/patients/profile/${v.patient.id}/consultation?opdVisitId=${v.id}`;return}if(a==="CALL_PATIENT"){await updateStatus(v.id,"IN_CONSULTATION");return}if(a==="COMPLETE_CONSULTATION"){await updateStatus(v.id,"COMPLETED",true);return}if(a==="NO_SHOW"){await updateStatus(v.id,"NO_SHOW");return}if(a==="REQUEUE"){await updateStatus(v.id,"WAITING");return}}catch(e){setError(e instanceof Error?e.message:"Unable to update queue")}finally{setActionId(null)}}
 async function updateStatus(id:number,status:string,finalize=false){const r=await fetch(`/api/opd/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,finalize})}),data=await r.json();if(!r.ok)throw Error(data?.error||"Unable to update queue status.");setVisits(old=>old.map(x=>x.id===id?{...x,status:data.status||status}:x))}
 function changeDesk(){localStorage.removeItem(STORAGE_KEY);setDepartmentId("");setDoctorId("");setDepartment(null);setDoctor(null);setVisits([])}
 const waiting=useMemo(()=>visits.filter(v=>v.status==="WAITING"),[visits]),called=useMemo(()=>visits.filter(v=>v.status==="IN_CONSULTATION"),[visits]),completed=useMemo(()=>visits.filter(v=>v.status==="COMPLETED"),[visits]);
 const active=called[0];
 return <main className="min-h-screen bg-[linear-gradient(180deg,#e8f6ff_0%,#f5fbff_42%,#eef8f3_100%)] px-4 py-6 text-slate-900 sm:px-7 sm:py-8"><div className="mx-auto max-w-7xl">
 <header className="relative overflow-hidden rounded-[2rem] bg-[linear-gradient(135deg,#05294a_0%,#087aa5_52%,#0c8b72_100%)] p-6 text-white shadow-[0_24px_70px_rgba(3,91,126,.25)] sm:p-8"><div className="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10 blur-2xl"/><div className="pointer-events-none absolute -bottom-20 left-1/3 h-48 w-72 rounded-full bg-cyan-200/10 blur-3xl"/><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/reception" className="inline-flex rounded-xl border border-white/25 bg-white/10 px-4 py-2.5 text-xs font-black backdrop-blur hover:bg-white/15">← Back to Reception</Link><p className="mt-7 text-[9px] font-black uppercase tracking-[.3em] text-cyan-100">SAMS · OPD FLOW</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">{department&&doctor?`${department.name} · ${doctor.name}`:"OPD Queue"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">A calm, live desk for moving patients from registration to consultation.</p></div>{departmentId&&doctorId&&<button onClick={changeDesk} className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-xs font-black backdrop-blur hover:bg-white/15">Change OPD</button>}</div></header>
 <section className="relative -mt-6 mx-2 rounded-[1.5rem] border border-white/70 bg-white/90 p-5 shadow-xl backdrop-blur sm:mx-6 sm:p-6"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-700">OPD Desk</p><h2 className="mt-1 text-xl font-black text-slate-800">Choose Department & Consultant</h2></div><span className="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-[9px] font-black uppercase tracking-wide text-emerald-700 sm:inline-flex">Queue ready</span></div><div className="grid gap-4 lg:grid-cols-2"><label className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4"><span className="text-[9px] font-black uppercase tracking-[.18em] text-slate-500">Department</span><select value={departmentId} disabled={loadingDepartments} onChange={e=>{setDepartmentId(e.target.value);setDoctorId("");setDoctor(null)}} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-800"><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4"><span className="text-[9px] font-black uppercase tracking-[.18em] text-slate-500">Consultant</span><select value={doctorId} disabled={!departmentId||loadingDoctors} onChange={e=>setDoctorId(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-800 disabled:bg-slate-100"><option value="">{loadingDoctors?"Loading consultants…":"Select consultant"}</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div></section>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 {departmentId&&doctorId&&<><section className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.15em] text-amber-700">Waiting</p><p className="mt-2 text-3xl font-black text-amber-950">{waiting.length}</p><p className="mt-1 text-[10px] font-bold text-amber-700">Ready to be called</p></div><div className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.15em] text-cyan-700">In Consultation</p><p className="mt-2 text-3xl font-black text-cyan-950">{called.length}</p><p className="mt-1 text-[10px] font-bold text-cyan-700">Currently with consultant</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.15em] text-emerald-700">Completed Today</p><p className="mt-2 text-3xl font-black text-emerald-950">{completed.length}</p><p className="mt-1 text-[10px] font-bold text-emerald-700">Consultations closed</p></div></section>
 <section className="mt-5 rounded-[1.75rem] border border-slate-200 bg-white/95 shadow-sm"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-teal-700">Current Flow</p><h2 className="mt-1 text-xl font-black text-slate-800">Patient journey</h2></div><button onClick={loadQueue} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-700 hover:bg-slate-50">↻ Refresh queue</button></div><div className="mt-5 grid grid-cols-4 gap-2 text-center"><div className="rounded-xl bg-slate-50 px-2 py-3 text-[9px] font-black text-slate-600">REGISTRATION</div><div className="rounded-xl bg-amber-50 px-2 py-3 text-[9px] font-black text-amber-700">WAITING</div><div className="rounded-xl bg-cyan-50 px-2 py-3 text-[9px] font-black text-cyan-700">CONSULTATION</div><div className="rounded-xl bg-emerald-50 px-2 py-3 text-[9px] font-black text-emerald-700">COMPLETED</div></div></div>
 {active&&<div className="m-5 overflow-hidden rounded-2xl bg-[linear-gradient(135deg,#063c5a,#087f92)] p-5 text-white shadow-lg sm:m-6 sm:p-6"><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-100">Now in consultation</p><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-2xl font-black">Token #{active.tokenNumber}</p><p className="mt-1 text-sm font-semibold text-white/75">{active.patient.firstName} {active.patient.lastName} · HID {active.patient.patientId}</p></div><button onClick={()=>action(active,"COMPLETE_CONSULTATION")} disabled={actionId===active.id} className="rounded-xl bg-white px-5 py-3 text-xs font-black text-slate-800 disabled:opacity-50">Complete Consultation</button></div></div>}
 <div className="divide-y divide-slate-100">{loading?<div className="p-8 text-sm font-semibold text-slate-500">Loading queue…</div>:visits.length===0?<div className="p-10 text-center text-sm font-semibold text-slate-500">No registered patients in this OPD today.</div>:visits.map(v=><div key={v.id} className="grid gap-4 p-5 sm:grid-cols-[minmax(0,1fr)_220px] sm:items-center"><div className="flex items-center gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-slate-900 text-lg font-black text-cyan-200 shadow-sm">{v.tokenNumber}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-black text-slate-800">{v.patient.firstName} {v.patient.lastName}</p>{v.appointment?<span className="rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-[9px] font-black uppercase tracking-wide text-blue-700">Appointment · {v.appointment.appointmentTime}</span>:<span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[9px] font-black uppercase tracking-wide text-slate-500">Walk-in</span>}</div><p className="mt-1 text-xs font-semibold text-slate-500">HID · {v.patient.patientId} · Token #{v.tokenNumber}</p>{v.appointment&&<p className="mt-1 text-[10px] font-bold text-slate-500">{v.appointment.appointmentNo} · {v.appointment.source}</p>}</div></div><select disabled={actionId===v.id} value={v.status} onChange={e=>action(v,e.target.value)} className={`w-full rounded-xl border px-3 py-3 text-xs font-black outline-none ${v.status==="WAITING"?"border-amber-200 bg-amber-50 text-amber-800":v.status==="IN_CONSULTATION"?"border-cyan-200 bg-cyan-50 text-cyan-800":v.status==="COMPLETED"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-slate-200 bg-slate-50 text-slate-700"}`}><option value={v.status}>{v.status.replaceAll("_"," ")} ▾</option>{statusOptions(v.status).map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>)}</div></section></>}
 </div></main>;
}
