"use client";

import Image from "next/image";
import Link from "next/link";

type ClinicalLeadCardProps = { name?: string; credentials?: string; specialty?: string; description?: string; imageSrc?: string };
const defaultLead = { name: "Dr. Suraj Serawat", credentials: "MBBS, MD Physical Medicine & Rehabilitation", specialty: "Pain Medicine • Joint & Spine Specialist", description: "Director and clinical lead at SAMS, bringing together multispecialty care across pain medicine, musculoskeletal and joint conditions, spine disorders, neurological rehabilitation and comprehensive functional recovery." };
const expertise = ["Musculoskeletal & joint conditions","Spine-related disorders","Pain medicine","Brain and neurological rehabilitation","Peripheral nerve-related conditions","Paediatric rehabilitation","Spinal cord rehabilitation","Specialized rehabilitation and functional recovery"];
export default function ClinicalLeadCard({ name=defaultLead.name, credentials=defaultLead.credentials, specialty=defaultLead.specialty, description=defaultLead.description, imageSrc="/doctor-photo.jpg" }: ClinicalLeadCardProps) {
 return <section className="overflow-hidden rounded-[1.5rem] border border-slate-200/80 bg-white shadow-[0_15px_50px_rgba(8,43,97,0.06)]"><div className="grid lg:grid-cols-[300px_1fr]"><div className="relative flex min-h-[320px] items-center justify-center overflow-hidden bg-[#082b61] sm:min-h-[350px] lg:min-h-[390px]"><Image src={imageSrc} alt={name} fill sizes="(max-width: 1024px) 100vw, 300px" className="object-cover object-top" priority/><div className="absolute inset-0 bg-gradient-to-t from-[#082b61]/55 via-transparent to-transparent"/><div className="absolute left-4 top-4 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[9px] font-black uppercase tracking-[0.2em] text-blue-100 backdrop-blur-md">Director</div><div className="absolute bottom-4 left-4 right-4 rounded-xl border border-white/10 bg-black/20 p-3 backdrop-blur-md"><p className="text-[8px] font-black uppercase tracking-[0.18em] text-blue-200">SAMS</p><p className="mt-1 text-[10px] font-bold leading-4 text-white">Serawat Advanced Multispecialty Joint & Spine Center</p></div></div><div className="flex flex-col justify-between p-5 sm:p-6"><div><p className="text-[9px] font-black uppercase tracking-[0.22em] text-[#0b63ce]">Meet Our Director</p><h2 className="mt-2 text-2xl font-black tracking-tight text-[#082b61] sm:text-3xl">{name}</h2><p className="mt-1 text-xs font-bold leading-5 text-slate-500">{credentials}</p><div className="mt-3 inline-flex rounded-full bg-blue-50 px-3 py-1.5 text-[9px] font-black uppercase tracking-[0.14em] text-[#0b63ce]">{specialty}</div><p className="mt-4 text-xs leading-6 text-slate-500">{description}</p><div className="mt-5"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#0b63ce]">Areas of expertise</p><div className="mt-2 grid gap-1.5 sm:grid-cols-2">{expertise.map(item=><div key={item} className="flex items-start gap-1.5 rounded-lg border border-slate-100 bg-[#f8fafc] px-2.5 py-2 text-[10px] font-bold leading-4 text-[#082b61]"><span className="text-[#0b63ce]">✓</span><span>{item}</span></div>)}</div></div></div><div className="mt-5 border-t border-slate-100 pt-4"><Link href="/patients" className="inline-flex rounded-lg border border-slate-200 bg-slate-50 px-4 py-2.5 text-xs font-black text-[#082b61] transition hover:bg-blue-50">Patient Workspace <span className="ml-1">↗</span></Link></div></div></div></section>;
}
