"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type Lang = "en" | "hi";

const content = {
  en: {
    nav: { doctor: "Doctor", expertise: "Expertise", why: "Why SAMS", appointment: "Book Consultation", workspace: "Clinical Workspace" },
    hero: { eyebrow: "Specialist care • Pain Medicine • Rehabilitation", title: "Advanced care for", accent: "pain, movement & recovery.", body: "Specialised clinical care designed around the person — from pain and spine disorders to neurological, paediatric and complex rehabilitation.", cta: "Book a Consultation", secondary: "Explore Our Expertise" },
    doctor: { eyebrow: "Meet your specialist", title: "Dr. Suraj Serawat", credentials: "MBBS, MD Physical Medicine & Rehabilitation", college: "SMS Medical College, Jaipur", specialty: "Pain Medicine • Joint & Spine Specialist", heading: "Areas of expertise", messageTitle: "A message from your doctor", message: "Every patient comes with a different story, a different challenge and a different goal. At SAMS, we begin by understanding that story — identifying the cause of the problem, how it affects movement and daily life, and what matters most to you. Whether you are living with pain, recovering from an injury, facing a neurological condition, or working toward greater independence, our goal is simple: to help you move better, function better and live better.", sign: "— Dr. Suraj Serawat" },
    intro: { eyebrow: "The SAMS approach", title: "Care that sees beyond the diagnosis.", p1: "SAMS — Serawat Advanced Musculoskeletal, Joint & Spine Centre — is built around a simple belief: meaningful healthcare should help people understand their problem, move with greater confidence and return to the life they value.", p2: "With expertise spanning Pain Medicine, musculoskeletal and joint conditions, spine disorders, brain and nerve-related conditions, paediatric rehabilitation and specialised functional recovery, we bring clinical assessment and rehabilitation together around the individual." },
    expertise: { eyebrow: "Conditions treated here", title: "Expertise across the spectrum of rehabilitation.", body: "From pain and movement disorders to neurological and paediatric rehabilitation, specialised care is brought together under one roof.", explore: "Explore" },
    why: { eyebrow: "Why choose SAMS", title: "Specialist thinking. Personalised care. Meaningful recovery.", body: "Our approach combines clinical expertise with a clear focus on function, independence and the goals that matter to each patient.", items: [["01", "Personalized assessment", "We begin by understanding the person, the condition and the goals that matter most."], ["02", "Specialist clinical thinking", "Pain medicine, musculoskeletal, spine and rehabilitation expertise come together in one clinical approach."], ["03", "Function, not just symptoms", "Our aim is meaningful improvement in movement, participation, independence and quality of life."], ["04", "Whole-person rehabilitation", "Musculoskeletal, neurological, paediatric and functional needs are considered as part of the bigger picture."], ["05", "Continuity of care", "Assessment, treatment, documentation and follow-up remain connected throughout the patient journey."], ["06", "Care built around your goals", "Your priorities help shape the treatment plan — from reducing pain to returning to everyday life."] ] as const },
    footer: "Serawat Advanced Musculoskeletal, Joint & Spine Centre"
  },
  hi: {
    nav: { doctor: "डॉक्टर", expertise: "विशेषज्ञता", why: "SAMS क्यों", appointment: "परामर्श बुक करें", workspace: "क्लिनिकल वर्कस्पेस" },
    hero: { eyebrow: "विशेषज्ञ चिकित्सा • पेन मेडिसिन • रिहैबिलिटेशन", title: "उन्नत उपचार", accent: "दर्द, गतिशीलता और रिकवरी के लिए।", body: "हर व्यक्ति की जरूरत के अनुसार विशेषज्ञ चिकित्सा — दर्द और रीढ़ की समस्याओं से लेकर न्यूरोलॉजिकल, बाल चिकित्सा और जटिल रिहैबिलिटेशन तक।", cta: "परामर्श बुक करें", secondary: "हमारी विशेषज्ञता देखें" },
    doctor: { eyebrow: "अपने विशेषज्ञ से मिलें", title: "डॉ. सूरज सेरावत", credentials: "MBBS, MD Physical Medicine & Rehabilitation", college: "SMS Medical College, Jaipur", specialty: "Pain Medicine • Joint & Spine Specialist", heading: "विशेषज्ञता के क्षेत्र", messageTitle: "आपके डॉक्टर का संदेश", message: "हर मरीज की कहानी, चुनौती और लक्ष्य अलग होता है। SAMS में हम सबसे पहले आपकी कहानी समझते हैं — समस्या के कारण, उसके आपके चलने-फिरने और दैनिक जीवन पर प्रभाव तथा आपके लिए सबसे महत्वपूर्ण लक्ष्य को समझकर। चाहे आप दर्द से जूझ रहे हों, चोट से उबर रहे हों, न्यूरोलॉजिकल समस्या का सामना कर रहे हों या अधिक स्वतंत्रता की ओर बढ़ रहे हों, हमारा लक्ष्य सरल है: आपको बेहतर चलने, बेहतर कार्य करने और बेहतर जीवन जीने में मदद करना।", sign: "— डॉ. सूरज सेरावत" },
    intro: { eyebrow: "SAMS का दृष्टिकोण", title: "उपचार जो केवल बीमारी नहीं, आपको देखता है।", p1: "SAMS — Serawat Advanced Musculoskeletal, Joint & Spine Centre — इस विश्वास पर आधारित है कि बेहतर चिकित्सा का उद्देश्य व्यक्ति को अपनी समस्या समझने, अधिक आत्मविश्वास से चलने-फिरने और अपने महत्वपूर्ण जीवन में वापस लौटने में मदद करना है।", p2: "Pain Medicine, मस्कुलोस्केलेटल और जोड़ों की समस्याओं, रीढ़, मस्तिष्क और नसों से जुड़ी स्थितियों, बाल चिकित्सा रिहैबिलिटेशन और विशेष कार्यात्मक रिकवरी में विशेषज्ञता के साथ हम क्लिनिकल मूल्यांकन और रिहैबिलिटेशन को व्यक्ति की जरूरत के अनुसार जोड़ते हैं।" },
    expertise: { eyebrow: "यहाँ उपचारित स्थितियाँ", title: "रिहैबिलिटेशन की व्यापक विशेषज्ञता।", body: "दर्द और मूवमेंट डिसऑर्डर से लेकर न्यूरोलॉजिकल और पीडियाट्रिक रिहैबिलिटेशन तक, विशेषज्ञ देखभाल एक ही स्थान पर।", explore: "विस्तार से देखें" },
    why: { eyebrow: "SAMS क्यों चुनें", title: "विशेषज्ञ सोच। व्यक्तिगत देखभाल। सार्थक रिकवरी।", body: "हमारा दृष्टिकोण क्लिनिकल विशेषज्ञता को कार्यक्षमता, स्वतंत्रता और प्रत्येक मरीज के महत्वपूर्ण लक्ष्यों के साथ जोड़ता है।", items: [["01", "व्यक्तिगत मूल्यांकन", "हम व्यक्ति, समस्या और सबसे महत्वपूर्ण लक्ष्यों को समझने से शुरुआत करते हैं।"], ["02", "विशेषज्ञ क्लिनिकल दृष्टिकोण", "Pain Medicine, मस्कुलोस्केलेटल, स्पाइन और रिहैबिलिटेशन विशेषज्ञता एक साथ आती है।"], ["03", "सिर्फ लक्षण नहीं, कार्यक्षमता", "हमारा लक्ष्य गतिशीलता, सहभागिता, स्वतंत्रता और जीवन की गुणवत्ता में सार्थक सुधार है।"], ["04", "समग्र रिहैबिलिटेशन", "मस्कुलोस्केलेटल, न्यूरोलॉजिकल, पीडियाट्रिक और कार्यात्मक जरूरतों को व्यापक रूप से देखा जाता है।"], ["05", "निरंतर देखभाल", "मूल्यांकन, उपचार, दस्तावेज़ीकरण और फॉलो-अप मरीज की यात्रा से जुड़े रहते हैं।"], ["06", "आपके लक्ष्य के अनुसार उपचार", "आपकी प्राथमिकताएँ उपचार योजना को दिशा देती हैं — दर्द कम करने से लेकर दैनिक जीवन में वापसी तक।"] ] as const },
    footer: "Serawat Advanced Musculoskeletal, Joint & Spine Centre"
  }
} as const;

const fields = {
  en: [
    ["Musculoskeletal & Joint", "Move better. Live better.", ["Osteoarthritis", "Rheumatoid arthritis", "Joint pain & stiffness", "Shoulder & knee disorders", "Sports injuries", "Tendon & ligament problems"]],
    ["Spine Related", "Relieve pain. Restore movement.", ["Sciatica", "Radiculopathy", "Mechanical neck & back pain", "Disc-related disorders", "Cervical & lumbar spondylosis", "Spinal stenosis"]],
    ["Brain Related", "Recovery after neurological injury & disease.", ["Stroke", "Traumatic Brain Injury (TBI)", "Parkinson’s disease", "Acquired brain injury", "Movement disorders", "Balance & coordination problems"]],
    ["Peripheral Nerve Related", "From nerve injury to functional recovery.", ["Peripheral neuropathy", "Peripheral nerve injuries", "Nerve compression disorders", "Entrapment neuropathies", "Brachial plexus injuries", "Foot drop"]],
    ["Paediatric Rehabilitation", "Helping children move, develop & participate.", ["Cerebral Palsy (CP)", "CTEV / Clubfoot", "Developmental delay", "Paediatric neurological conditions", "Paediatric musculoskeletal conditions", "Gait & movement disorders"]],
    ["Neuro Rehabilitation", "Rebuilding movement, balance & independence.", ["Stroke rehabilitation", "Parkinson’s rehabilitation", "Multiple sclerosis", "Guillain-Barré syndrome", "Ataxia & coordination disorders", "Balance & gait disorders"]],
    ["Spinal Cord Rehabilitation", "Maximising independence after spinal cord injury.", ["Spinal cord injury", "Paraplegia", "Tetraplegia", "Incomplete spinal cord injury", "Spinal cord-related weakness", "Mobility & wheelchair rehabilitation"]],
    ["Other Specialized Rehabilitation", "Complex problems. Individualised solutions.", ["Rheumatological conditions", "Chronic pain", "Amputation rehabilitation", "Prosthetic rehabilitation", "Orthotic & assistive-device needs", "Complex functional disabilities"]]
  ],
  hi: [
    ["मस्कुलोस्केलेटल और जोड़", "बेहतर चलें। बेहतर जीवन जिएँ।", ["ऑस्टियोआर्थराइटिस", "रूमेटॉइड आर्थराइटिस", "जोड़ों का दर्द और जकड़न", "कंधे और घुटने की समस्याएँ", "स्पोर्ट्स इंजरी", "टेंडन और लिगामेंट की समस्याएँ"]],
    ["रीढ़ से संबंधित", "दर्द कम करें। गतिशीलता लौटाएँ।", ["साइटिका", "रेडिकुलोपैथी", "मैकेनिकल गर्दन और कमर दर्द", "डिस्क संबंधी समस्याएँ", "सर्वाइकल और लम्बर स्पॉन्डिलोसिस", "स्पाइनल स्टेनोसिस"]],
    ["मस्तिष्क से संबंधित", "न्यूरोलॉजिकल बीमारी या चोट के बाद रिकवरी।", ["स्ट्रोक", "ट्रॉमेटिक ब्रेन इंजरी (TBI)", "पार्किन्सन रोग", "एक्वायर्ड ब्रेन इंजरी", "मूवमेंट डिसऑर्डर", "संतुलन और समन्वय की समस्याएँ"]],
    ["पेरिफेरल नर्व से संबंधित", "नस की चोट से कार्यात्मक रिकवरी तक।", ["पेरिफेरल न्यूरोपैथी", "पेरिफेरल नर्व इंजरी", "नर्व कम्प्रेशन", "एंट्रैपमेंट न्यूरोपैथी", "ब्रैकियल प्लेक्सस इंजरी", "फुट ड्रॉप"]],
    ["पीडियाट्रिक रिहैबिलिटेशन", "बच्चों को चलने, विकसित होने और भाग लेने में मदद।", ["सेरेब्रल पाल्सी (CP)", "CTEV / क्लबफुट", "विकास में देरी", "पीडियाट्रिक न्यूरोलॉजिकल स्थितियाँ", "पीडियाट्रिक मस्कुलोस्केलेटल समस्याएँ", "गैट और मूवमेंट डिसऑर्डर"]],
    ["न्यूरो रिहैबिलिटेशन", "गतिशीलता, संतुलन और स्वतंत्रता को फिर से बनाना।", ["स्ट्रोक रिहैबिलिटेशन", "पार्किन्सन रिहैबिलिटेशन", "मल्टीपल स्क्लेरोसिस", "गिलियन-बैरे सिंड्रोम", "एटैक्सिया और समन्वय समस्याएँ", "संतुलन और चाल की समस्याएँ"]],
    ["स्पाइनल कॉर्ड रिहैबिलिटेशन", "स्पाइनल कॉर्ड इंजरी के बाद अधिकतम स्वतंत्रता।", ["स्पाइनल कॉर्ड इंजरी", "पैराप्लेजिया", "टेट्राप्लेजिया", "अपूर्ण स्पाइनल कॉर्ड इंजरी", "स्पाइनल कॉर्ड से संबंधित कमजोरी", "मोबिलिटी और व्हीलचेयर रिहैबिलिटेशन"]],
    ["अन्य विशेष रिहैबिलिटेशन", "जटिल समस्याएँ। व्यक्तिगत समाधान।", ["रूमेटोलॉजिकल स्थितियाँ", "क्रॉनिक पेन", "एम्प्यूटेशन रिहैबिलिटेशन", "प्रोस्थेटिक रिहैबिलिटेशन", "ऑर्थोटिक और असिस्टिव डिवाइस जरूरतें", "जटिल कार्यात्मक अक्षमताएँ"]]
  ]
} as const;

const expertise = ["Pain Medicine", "Musculoskeletal & Joint Care", "Spine Disorders", "Brain & Neurological Rehabilitation", "Peripheral Nerve Conditions", "Paediatric Rehabilitation", "Spinal Cord Rehabilitation", "Functional Recovery"];

export default function SamsPublicHome() {
  const [lang, setLang] = useState<Lang>("en");
  const t = content[lang];
  const f = fields[lang];
  return <main className="min-h-screen bg-[#f6f8fb] text-[#082b61]">
    <header className="sticky top-0 z-30 border-b border-slate-200/70 bg-white/90 backdrop-blur-xl">
      <div className="mx-auto flex max-w-[1450px] items-center justify-between px-5 py-3 sm:px-8">
        <Link href="/home-v2" className="flex items-center gap-3"><Image src="/serawat-logo.png" alt="SAMS" width={82} height={46} className="h-11 w-auto object-contain" priority /><div><p className="text-lg font-black tracking-tight">SAMS</p><p className="hidden max-w-[310px] text-[9px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:block">{t.doctor.college} • Serawat Advanced Musculoskeletal, Joint & Spine Centre</p></div></Link>
        <nav className="hidden items-center gap-6 text-xs font-black text-slate-500 lg:flex"><a href="#doctor" className="hover:text-[#0b63ce]">{t.nav.doctor}</a><a href="#expertise" className="hover:text-[#0b63ce]">{t.nav.expertise}</a><a href="#why" className="hover:text-[#0b63ce]">{t.nav.why}</a></nav>
        <div className="flex items-center gap-2"><button onClick={() => setLang(lang === "en" ? "hi" : "en")} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-[10px] font-black tracking-wider text-[#082b61] shadow-sm">{lang === "en" ? "हिन्दी" : "ENGLISH"}</button><Link href="/dashboard" className="hidden rounded-xl bg-[#082b61] px-4 py-2.5 text-xs font-black text-white shadow-lg shadow-blue-950/10 transition hover:bg-[#0b63ce] sm:block">{t.nav.workspace}</Link></div>
      </div>
    </header>

    <div className="mx-auto max-w-[1450px] px-5 sm:px-8">
      <section className="relative mt-5 overflow-hidden rounded-[2.5rem] bg-[#082b61] px-7 py-12 text-white shadow-[0_30px_90px_rgba(8,43,97,0.2)] sm:px-12 sm:py-16 lg:px-16 lg:py-20"><div className="absolute -right-20 -top-24 h-96 w-96 rounded-full bg-[#0b63ce]/35 blur-3xl" /><div className="absolute bottom-0 left-1/2 h-72 w-72 rounded-full bg-blue-300/10 blur-3xl" /><div className="relative max-w-5xl"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-blue-200">{t.hero.eyebrow}</p><h1 className="mt-5 font-serif text-5xl font-semibold leading-[0.98] tracking-[-0.035em] sm:text-6xl lg:text-8xl">{t.hero.title}<br /><span className="text-blue-300">{t.hero.accent}</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-blue-100 sm:text-lg">{t.hero.body}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#doctor" className="rounded-xl bg-white px-5 py-3.5 text-sm font-black text-[#082b61] shadow-xl transition hover:-translate-y-0.5 hover:bg-blue-50">{t.hero.cta} <span className="ml-2">→</span></a><a href="#expertise" className="rounded-xl border border-white/20 bg-white/10 px-5 py-3.5 text-sm font-black text-white backdrop-blur transition hover:-translate-y-0.5 hover:bg-white/15">{t.hero.secondary} <span className="ml-2">↓</span></a></div></div></section>

      <section id="doctor" className="scroll-mt-24 py-10 sm:py-14"><div className="grid overflow-hidden rounded-[2.5rem] border border-slate-200/80 bg-white shadow-[0_20px_70px_rgba(8,43,97,0.07)] lg:grid-cols-[330px_1fr]"><div className="relative min-h-[420px] bg-[#082b61]"><Image src="/doctor-photo.jpg" alt="Dr. Suraj Serawat" fill sizes="(max-width: 1024px) 100vw, 330px" className="object-cover object-top" priority /><div className="absolute inset-0 bg-gradient-to-t from-[#082b61]/80 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/10 bg-black/20 p-4 backdrop-blur-md"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-blue-200">SAMS</p><p className="mt-1 text-xs font-bold text-white">{t.doctor.college}</p></div></div><div className="p-8 sm:p-10 lg:p-12"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#0b63ce]">{t.doctor.eyebrow}</p><h2 className="mt-3 font-serif text-4xl font-semibold tracking-tight text-[#082b61] sm:text-5xl">{t.doctor.title}</h2><p className="mt-3 text-sm font-bold text-slate-500">{t.doctor.credentials}</p><p className="mt-1 text-sm font-semibold text-slate-400">{t.doctor.college}</p><div className="mt-5 inline-flex rounded-full bg-blue-50 px-4 py-2 text-[10px] font-black uppercase tracking-[0.15em] text-[#0b63ce]">{t.doctor.specialty}</div><div className="mt-8"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-[#0b63ce]">{t.doctor.heading}</p><div className="mt-4 flex flex-wrap gap-2">{expertise.map(x => <span key={x} className="rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-[#082b61]">{x}</span>)}</div></div></div></div></section>

      <section className="grid gap-5 pb-10 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[2.5rem] bg-white p-8 shadow-[0_18px_60px_rgba(8,43,97,0.06)] sm:p-12"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#0b63ce]">{t.intro.eyebrow}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl font-semibold leading-tight tracking-tight text-[#082b61] sm:text-5xl">{t.intro.title}</h2><p className="mt-6 text-base leading-8 text-slate-600">{t.intro.p1}</p><p className="mt-4 text-base leading-8 text-slate-600">{t.intro.p2}</p></div><div className="rounded-[2.5rem] bg-[#eef5ff] p-8 sm:p-10"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#0b63ce]">SAMS</p><div className="mt-8 space-y-3">{["Listen & understand", "Assess the cause and impact", "Plan around individual goals", "Treat, rehabilitate & follow through"].map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-blue-100 bg-white px-4 py-4 text-sm font-bold text-[#082b61]"><span className="font-serif text-xl italic text-[#0b63ce]">0{i+1}</span>{lang === "en" ? x : ["सुनें और समझें", "कारण और प्रभाव का मूल्यांकन", "व्यक्तिगत लक्ष्यों के अनुसार योजना", "उपचार, रिहैबिलिटेशन और निरंतर फॉलो-अप"][i]}</div>)}</div></div></section>

      <section id="doctor-message" className="scroll-mt-24 py-10"><div className="relative overflow-hidden rounded-[2.5rem] bg-[#082b61] p-8 text-white shadow-[0_25px_80px_rgba(8,43,97,0.18)] sm:p-12 lg:p-16"><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full bg-[#0b63ce]/30 blur-3xl" /><div className="relative max-w-4xl"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-blue-200">{t.doctor.messageTitle}</p><blockquote className="mt-5 font-serif text-2xl font-medium leading-relaxed text-white sm:text-3xl">“{t.doctor.message}”</blockquote><p className="mt-7 text-sm font-black text-blue-200">{t.doctor.sign}</p><p className="mt-1 text-xs font-bold text-blue-300">{t.doctor.credentials} • {t.doctor.specialty}</p></div></div></section>

      <section id="expertise" className="scroll-mt-24 py-10"><div className="mb-7 max-w-4xl"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#0b63ce]">{t.expertise.eyebrow}</p><h2 className="mt-3 font-serif text-4xl font-semibold tracking-tight text-[#082b61] sm:text-5xl">{t.expertise.title}</h2><p className="mt-4 text-base leading-7 text-slate-500">{t.expertise.body}</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{f.map((field,index)=><article key={field[0]} className="group relative overflow-hidden rounded-[1.75rem] border border-slate-200/80 bg-white p-6 shadow-[0_14px_45px_rgba(8,43,97,0.05)] transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-[0_24px_65px_rgba(8,43,97,0.11)]"><div className="absolute -right-5 -top-5 h-28 w-28 rounded-full bg-blue-50 blur-2xl transition group-hover:bg-blue-100" /><div className="relative"><div className="flex items-center justify-between"><span className="font-serif text-2xl italic text-[#0b63ce]">{String(index+1).padStart(2,"0")}</span><span className="text-[9px] font-black uppercase tracking-[0.15em] text-slate-300 group-hover:text-[#0b63ce]">{t.expertise.explore} →</span></div><h3 className="mt-8 text-lg font-black leading-6 text-[#082b61]">{field[0]}</h3><p className="mt-2 text-xs font-bold leading-5 text-[#0b63ce]">{field[1]}</p><ul className="mt-5 space-y-2 border-t border-slate-100 pt-4">{field[2].map(item=><li key={item} className="flex gap-2 text-xs font-medium leading-5 text-slate-500"><span className="text-[#0b63ce]">•</span>{item}</li>)}</ul></div></article>)}</div></section>

      <section id="why" className="scroll-mt-24 py-10"><div className="relative overflow-hidden rounded-[2.5rem] bg-[#082b61] p-8 text-white shadow-[0_25px_80px_rgba(8,43,97,0.18)] sm:p-12 lg:p-14"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-[#0b63ce]/30 blur-3xl" /><div className="relative"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-blue-200">{t.why.eyebrow}</p><h2 className="mt-4 max-w-3xl font-serif text-4xl font-semibold leading-tight sm:text-5xl">{t.why.title}</h2><p className="mt-5 max-w-2xl text-base leading-7 text-blue-100">{t.why.body}</p><div className="mt-9 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{t.why.items.map(([n,title,body])=><div key={n} className="rounded-2xl border border-white/10 bg-white/10 p-5 backdrop-blur-sm"><span className="font-serif text-2xl italic text-blue-300">{n}</span><h3 className="mt-5 text-sm font-black">{title}</h3><p className="mt-2 text-xs leading-5 text-blue-100/75">{body}</p></div>)}</div></div></div></section>

      <section className="py-12"><div className="flex flex-col items-start justify-between gap-6 rounded-[2.25rem] border border-slate-200 bg-white p-8 shadow-[0_15px_50px_rgba(8,43,97,0.05)] sm:flex-row sm:items-center sm:p-10"><div><p className="text-[10px] font-black uppercase tracking-[0.28em] text-[#0b63ce]">SAMS</p><h2 className="mt-2 font-serif text-3xl font-semibold text-[#082b61]">{t.nav.appointment}</h2></div><Link href="/visits/new" className="rounded-xl bg-[#082b61] px-6 py-3.5 text-sm font-black text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#0b63ce]">{t.nav.appointment} <span className="ml-2">→</span></Link></div></section>
      <footer className="border-t border-slate-200 py-7 text-xs font-medium text-slate-400">© SAMS • {t.footer}</footer>
    </div>
  </main>;
}
