"use client";
import Link from "next/link";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

type Patient={id:number;patientId:string;firstName:string;lastName:string;phone?:string|null;gender?:string|null;dateOfBirth?:string|null};
type Investigation={id:number;code:string;name:string;category:string;department?:string|null;rate:number;specimen?:string|null};
type Mode="REGISTERED"|"CONSULTATION"|"WALKIN"|"EXTERNAL_REFERRAL";
const modes:[Mode,string,string,string,string][]=[["REGISTERED","Registered Patient","Search registered records","01","user"],["CONSULTATION","Consultation / Visit","Link to an existing Visit","02","calendar"],["WALKIN","Walk-in / Outsider","Enter patient information","03","walk"],["EXTERNAL_REFERRAL","External Referral","Referral-based order","04","users"]];
const patientName=(p:Patient)=>`${p.firstName||""} ${p.lastName||""}`.trim()||"Patient";
const visitDateValue=(v:any)=>v?.visitDate||v?.date||v?.createdAt||v?.updatedAt||null;
const visitTimestamp=(v:any)=>{const raw=visitDateValue(v);const t=raw?Date.parse(String(raw)):NaN;return Number.isFinite(t)?t:Number(v?.id||0)};
const visitDateLabel=(v:any)=>{const raw=visitDateValue(v);if(!raw)return "Date/time not available";const d=new Date(raw);return Number.isNaN(d.getTime())?"Date/time not available":d.toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true})};
function Icon({name,size=20}:{name:string;size?:number}){const c={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round" as const,strokeLinejoin:"round" as const};if(name==="search")return <svg {...c}><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>;if(name==="user")return <svg {...c}><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4 3.3-6 8-6s7.2 2 8 6"/></svg>;if(name==="calendar")return <svg {...c}><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>;if(name==="walk")return <svg {...c}><circle cx="13" cy="4" r="2"/><path d="m10 8 3 3 3-2M10 8l-2 5 3 1 1 6M13 11l-2 3M14 12l4 4M6 21l3-5"/></svg>;if(name==="users")return <svg {...c}><circle cx="9" cy="8" r="3"/><path d="M3 20c.5-3.5 2.5-5 6-5s5.5 1.5 6 5M16 5a3 3 0 0 1 0 6M17 15c2.5.4 3.8 2 4 5"/></svg>;if(name==="filter")return <svg {...c}><path d="M4 6h16M7 12h10M10 18h4"/></svg>;if(name==="flask")return <svg {...c}><path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3"/><path d="M8 15h8"/></svg>;if(name==="cart")return <svg {...c}><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.5L21 8H6"/></svg>;return <svg {...c}><circle cx="12" cy="12" r="9"/></svg>}
function Orders(){
 const search=useSearchParams();
 const [mode,setMode]=useState<Mode>(search.get("opdVisitId")?"CONSULTATION":"REGISTERED");
 const [patientSearch,setPatientSearch]=useState("");const [patients,setPatients]=useState<Patient[]>([]);const [patient,setPatient]=useState<Patient|null>(null);const [visitId,setVisitId]=useState(search.get("opdVisitId")||"");
 const [catalogue,setCatalogue]=useState<Investigation[]>([]);const [query,setQuery]=useState("");const [category,setCategory]=useState("ALL");const [selected,setSelected]=useState<Investigation[]>([]);const [existingOrderIds,setExistingOrderIds]=useState<number[]>([]);
 const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [consultations,setConsultations]=useState<any[]>([]);const [consultationSearch,setConsultationSearch]=useState("");const [walkIn,setWalkIn]=useState({firstName:"",lastName:"",age:"",gender:"",phone:""});
 useEffect(()=>{Promise.all([fetch("/api/patients",{cache:"no-store"}).then(r=>r.ok?r.json():[]),fetch("/api/investigation-master",{cache:"no-store"}).then(r=>r.ok?r.json():[])]).then(([p,i])=>{setPatients(Array.isArray(p)?p:[]);setCatalogue(Array.isArray(i)?i:[])}).catch(()=>setError("Unable to load patient or Investigation Master data."))},[]);
 useEffect(()=>{if(!visitId)return;fetch(`/api/investigation-orders?opdVisitId=${encodeURIComponent(visitId)}`,{cache:"no-store"}).then(r=>r.json()).then(rows=>{if(Array.isArray(rows)&&rows.length){const first=rows[0];setPatient(first.opdVisit?.patient||null);const items=rows.filter((x:any)=>x.status!=="CANCELLED").map((x:any)=>({id:x.investigationId,code:x.master?.code||"",name:x.investigation,category:x.master?.category||"",department:x.master?.department||null,rate:Number(x.netAmount||x.price||0),specimen:x.specimen||x.master?.specimen||null}));setSelected(items);setExistingOrderIds(rows.filter((x:any)=>x.status!=="CANCELLED").map((x:any)=>x.id))}}).catch(()=>{})},[visitId]);
 useEffect(()=>{if(mode!=="CONSULTATION")return;fetch("/api/investigation-orders/consultations",{cache:"no-store"}).then(r=>r.ok?r.json():[]).then(x=>setConsultations(Array.isArray(x)?x:[])).catch(()=>setConsultations([]))},[mode]);
 const patientOptions=useMemo(()=>{const q=patientSearch.toLowerCase().trim();return(q?patients.filter(p=>`${patientName(p)} ${p.patientId} ${p.phone||""}`.toLowerCase().includes(q)):patients).slice(0,20)},[patients,patientSearch]);
 const cats=useMemo(()=>Array.from(new Set(catalogue.map(x=>x.category).filter(Boolean))).sort(),[catalogue]);
 const hasFilter=query.trim().length>0||category!=="ALL";
 const options=useMemo(()=>{const ids=new Set(selected.map(x=>x.id));const q=query.toLowerCase().trim();return catalogue.filter(x=>!ids.has(x.id)).filter(x=>category==="ALL"||x.category===category).filter(x=>!q||`${x.name} ${x.code} ${x.category} ${x.department||""}`.toLowerCase().includes(q)).slice(0,hasFilter?40:4)},[catalogue,selected,category,query,hasFilter]);
 const consultationOptions=useMemo(()=>{const q=consultationSearch.toLowerCase().trim();return [...consultations].filter((v:any)=>{if(!q)return true;const p=v?.patient;return `${patientName(p||{firstName:"",lastName:""})} ${p?.patientId||""} ${p?.phone||""} ${v?.id||""} ${v?.tokenNumber||""} ${visitDateLabel(v)}`.toLowerCase().includes(q)}).sort((a:any,b:any)=>visitTimestamp(b)-visitTimestamp(a))},[consultations,consultationSearch]);
 const total=selected.reduce((s,x)=>s+Number(x.rate||0),0);
 function reset(){setPatient(null);setPatientSearch("");setVisitId("");setSelected([]);setExistingOrderIds([]);setWalkIn({firstName:"",lastName:"",age:"",gender:"",phone:""})}
 function chooseMode(m:Mode){setMode(m);setError("");setMessage("");if(m!=="WALKIN")setWalkIn({firstName:"",lastName:"",age:"",gender:"",phone:""});if(m!=="CONSULTATION")setVisitId("");if(m==="WALKIN")setPatient(null)}
 function continueWalkIn(){setError("");const first=walkIn.firstName.trim(),last=walkIn.lastName.trim(),age=Number(walkIn.age);if(!first||!last)return setError("First name and last name are required for a Walk-in / Outsider patient.");if(walkIn.age&&(!Number.isInteger(age)||age<0||age>120))return setError("Please enter a valid age between 0 and 120 years.");if(walkIn.phone&&walkIn.phone.length!==10)return setError("Please enter a valid 10-digit mobile number.");setPatient({id:0,patientId:"WALK-IN",firstName:first,lastName:last,gender:walkIn.gender||null,phone:walkIn.phone||null});setMessage("Patient information completed.")}
 function add(i:Investigation){setSelected(v=>[...v,i]);setMessage("")}
 async function remove(i:Investigation,index:number){if(existingOrderIds[index]){try{const r=await fetch(`/api/investigation-orders?orderId=${existingOrderIds[index]}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to remove order");setExistingOrderIds(v=>v.filter((_,n)=>n!==index))}catch(e){setError(e instanceof Error?e.message:"Unable to remove investigation");return}}setSelected(v=>v.filter((_,n)=>n!==index))}
 async function place(){setSaving(true);setError("");try{if(!patient)throw new Error("Complete patient information first.");if(!selected.length)throw new Error("Select at least one investigation.");const body:any={sourceType:mode,patientId:mode==="WALKIN"?undefined:patient.patientId,opdVisitId:visitId?Number(visitId):undefined,investigations:selected.map(x=>({id:x.id}))};if(mode==="WALKIN"){body.firstName=walkIn.firstName.trim();body.lastName=walkIn.lastName.trim();body.gender=walkIn.gender||undefined;body.phone=walkIn.phone||undefined}const r=await fetch("/api/investigation-orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to place investigation order.");window.location.href=`/billing?patientId=${encodeURIComponent(d.visit.patientId)}&visitId=${Number(d.visit.id)}&from=investigation&bill=${encodeURIComponent(d.bill?.billNumber||"")}`}catch(e){setError(e instanceof Error?e.message:"Unable to place investigation order")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#FDC823] text-[#061a38]">
  <header className="bg-[#031a38] text-white shadow-[0_10px_35px_rgba(3,26,56,.3)]"><div className="mx-auto max-w-[1500px] px-5 py-4 sm:px-8"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl border border-[#FDC823]/60 bg-[#082b61] text-lg font-black text-[#FDC823]">⚕</div><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#FDC823]">SAMS · DIAGNOSTICS</p><p className="text-xs font-semibold text-white/90">Serawat Advanced Multispeciality Joint & Spine Centre</p></div></div><div className="flex gap-2"><Link href="/reception" className="rounded-xl border border-[#FDC823]/70 px-4 py-2.5 text-xs font-black text-[#FDC823] hover:bg-[#FDC823] hover:text-[#031a38]">← Back</Link><Link href="/billing" className="rounded-xl border border-[#FDC823]/70 px-4 py-2.5 text-xs font-black text-[#FDC823] hover:bg-[#FDC823] hover:text-[#031a38]">Billing</Link><Link href="/investigation-room" className="rounded-xl bg-[#FDC823] px-4 py-2.5 text-xs font-black text-[#031a38] hover:bg-white">♜ Investigation Room</Link></div></div></div></header>
  <div className="mx-auto max-w-[1500px] px-5 pb-10 pt-7 sm:px-8"><div className="mb-7"><h1 className="text-4xl font-black tracking-[-.04em] text-[#061a38] sm:text-5xl">Investigation Order</h1><p className="mt-2 text-sm font-semibold text-[#24354d]">Create a precise diagnostic order, review charges and move directly to the billing workflow.</p><div className="mt-6 flex max-w-[900px] items-center gap-3"><Step n="01" label="PATIENT" sub="Select or enter patient details"/><div className="h-px flex-1 bg-[#061a38]/35"/><Step n="02" label="INVESTIGATIONS" sub="Choose investigations"/><div className="h-px flex-1 bg-[#061a38]/35"/><Step n="03" label="ORDER & BILL" sub="Review & proceed to billing"/></div></div>
   <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="space-y-5">
    <section className="rounded-[1.25rem] border border-white/80 bg-[#fff8df] p-5 shadow-[0_12px_35px_rgba(61,43,0,.12)] sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#5b4300]">STEP 01 · ORDER SOURCE</p><h2 className="mt-1 text-2xl font-black">Who is this order for?</h2><p className="mt-1 text-xs font-semibold text-[#4c4c42]">Registered, Visit, Walk-in and Referral orders use the same downstream investigation and billing workflow.</p><div className="mt-5 grid gap-3 md:grid-cols-4">{modes.map(([m,title,sub,num,ico])=><button key={m} type="button" onClick={()=>chooseMode(m)} className={`rounded-xl border p-4 text-left transition ${mode===m?"border-[#061a38] bg-white shadow-[0_8px_20px_rgba(6,26,56,.12)]":"border-[#d9bd55] bg-[#fffdf3] hover:border-[#061a38]"}`}><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#061a38] text-white"><Icon name={ico} size={18}/></span><span className={`h-3 w-3 rounded-full border-2 border-[#061a38] ${mode===m?"bg-[#061a38]":"bg-transparent"}`}/></div><p className="mt-3 text-sm font-black">{title}</p><p className="mt-1 text-[10px] font-semibold text-[#5b5b52]">{sub}</p></button>)}</div>
      <div className="mt-4 rounded-xl border border-[#d9bd55] bg-[#fffdf4] p-4">{mode==="REGISTERED"&&<><label className="mb-2 block text-[10px] font-black uppercase tracking-wider">REGISTERED PATIENT</label><div className="relative"><div className="flex items-center gap-3 rounded-xl border border-[#d6c27a] bg-white px-4 py-3.5"><Icon name="search" size={19}/><input value={patient?patientName(patient):patientSearch} onChange={e=>{if(patient){reset();setPatientSearch(e.target.value)}else setPatientSearch(e.target.value)}} placeholder="Search by patient name, ID or mobile number…" className="w-full bg-transparent text-sm font-bold outline-none placeholder:text-slate-500"/></div>{!patient&&patientSearch&&<div className="absolute left-0 right-0 top-full z-30 mt-2 max-h-64 overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-2xl">{patientOptions.map(p=><button key={p.id} type="button" onClick={()=>{setPatient(p);setPatientSearch("")}} className="block w-full rounded-lg px-4 py-3 text-left hover:bg-[#fff5c9]"><b>{patientName(p)}</b><span className="ml-2 text-xs text-slate-500">{p.patientId}{p.phone?` · ${p.phone}`:""}</span></button>)}</div>}</div>{patient&&<PatientCard patient={patient} onChange={reset}/>}</>}
       {mode==="CONSULTATION"&&<><label className="mb-2 block text-[10px] font-black uppercase tracking-wider">CONSULTATION / VISIT</label><div className="flex items-center gap-3 rounded-xl border border-[#d6c27a] bg-white px-4 py-3.5"><Icon name="search" size={19}/><input value={consultationSearch} onChange={e=>setConsultationSearch(e.target.value)} placeholder="Search patient, Visit number, token or date…" className="w-full bg-transparent text-sm font-bold outline-none"/></div><div className="mt-3 max-h-56 space-y-2 overflow-auto">{consultationOptions.slice(0,12).map((v:any)=><button key={v.id} type="button" onClick={()=>{setPatient(v.patient);setVisitId(String(v.id))}} className={`w-full rounded-xl border p-3 text-left ${visitId===String(v.id)?"border-[#061a38] bg-white":"border-[#e0ca73] bg-[#fffdf4]"}`}><b>{patientName(v.patient)}</b><span className="ml-2 text-xs text-slate-500">Visit #{v.id} · {v.patient?.patientId||"—"} · {visitDateLabel(v)}</span></button>)}</div></>}
       {mode==="WALKIN"&&<WalkInForm data={walkIn} setData={setWalkIn} patient={patient} onContinue={continueWalkIn} onChange={reset}/>} {mode==="EXTERNAL_REFERRAL"&&<WalkInForm data={walkIn} setData={setWalkIn} patient={patient} onContinue={continueWalkIn} onChange={reset} referral/>}</div></section>
    <section className="rounded-[1.25rem] border border-white/80 bg-[#fff8df] p-5 shadow-[0_12px_35px_rgba(61,43,0,.12)] sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#5b4300]">STEP 02 · INVESTIGATION SELECTION</p><h2 className="mt-1 text-2xl font-black">Choose investigations</h2><p className="mt-1 text-xs font-semibold text-[#4c4c42]">Search the Investigation Master and add tests to the order.</p><div className="mt-5 grid gap-3 md:grid-cols-[1fr_230px]"><div className="flex items-center gap-3 rounded-xl border border-[#d6c27a] bg-white px-4 py-3.5"><Icon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search investigation, code or category…" className="w-full bg-transparent text-sm font-bold outline-none placeholder:text-slate-500"/></div><div className="flex items-center gap-2 rounded-xl border border-[#d6c27a] bg-white px-4"><Icon name="filter" size={18}/><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full bg-transparent py-3.5 text-sm font-bold outline-none"><option value="ALL">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select></div></div>{!patient&&<p className="mt-3 rounded-lg bg-[#fff0b0] px-3 py-2 text-[11px] font-bold text-[#5a4200]">Complete Step 01 patient information before choosing investigations.</p>}<div className="mt-4 grid gap-3 md:grid-cols-2">{options.map(i=><button key={i.id} type="button" disabled={!patient} onClick={()=>add(i)} className="flex items-center gap-3 rounded-xl border border-[#dec46b] bg-[#fffdf4] p-3.5 text-left transition hover:-translate-y-0.5 hover:bg-white disabled:cursor-not-allowed disabled:opacity-45"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-[#d7bc59] bg-white text-[#061a38]"><span className="text-2xl leading-none">+</span></span><span className="min-w-0 flex-1"><b className="block truncate text-sm font-black">{i.name}</b><small className="mt-1 block truncate text-[10px] font-semibold text-[#686458]">{i.code} · {i.category}{i.specimen?` · ${i.specimen}`:""}</small></span><strong className="text-sm font-black">₹{Number(i.rate||0).toFixed(0)}</strong></button>)}</div>{patient&&options.length===0&&<p className="mt-4 text-center text-xs font-bold text-[#625a42]">No matching investigations found.</p>}</section>
    <section className="rounded-[1.25rem] border border-white/80 bg-[#fff8df] p-5 shadow-[0_12px_35px_rgba(61,43,0,.12)] sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#5b4300]">STEP 03 · ORDER & BILL</p><h2 className="mt-1 text-2xl font-black">Review selected investigations</h2>{selected.length===0?<div className="mt-5 rounded-xl border border-dashed border-[#d1b95e] bg-[#fffdf4] p-8 text-center text-sm font-bold text-[#655d45]">No investigations selected. Add investigations from Step 02.</div>:<div className="mt-5 overflow-hidden rounded-xl border border-[#d8c16c] bg-white">{selected.map((i,n)=><div key={`${i.id}-${n}`} className="flex items-center gap-3 border-b border-[#eee2b6] px-4 py-3.5 last:border-0"><div className="min-w-0 flex-1"><b className="block text-sm font-black">{i.name}</b><small className="text-[10px] font-semibold text-slate-500">{i.code} · {i.category}</small></div><b className="text-sm">₹{Number(i.rate||0).toFixed(2)}</b><button type="button" onClick={()=>void remove(i,n)} className="rounded-lg px-2 py-1 text-xs font-black text-red-700 hover:bg-red-50">Remove</button></div>)}</div>}</section>
   </div>
   <aside className="h-fit rounded-[1.25rem] border border-white/80 bg-[#fff8df] p-5 shadow-[0_14px_40px_rgba(61,43,0,.16)] lg:sticky lg:top-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#5b4300]">STEP 03 · ORDER & BILL</p><h2 className="mt-1 text-2xl font-black">Order Summary</h2><div className="flex min-h-[260px] flex-col items-center justify-center border-b border-[#d7c26e] text-center"><div className="grid h-20 w-20 place-items-center rounded-2xl bg-[#061a38] text-[#FDC823]"><Icon name="flask" size={42}/></div>{selected.length===0?<><p className="mt-5 text-base font-black">No investigations selected</p><p className="mt-1 max-w-[210px] text-xs font-semibold text-[#655d45]">Add investigations to review and proceed to billing.</p></>:<p className="mt-5 text-sm font-bold">{selected.length} investigation{selected.length===1?"":"s"} selected</p>}</div><div className="space-y-4 border-b border-[#d7c26e] py-5 text-sm"><div className="flex justify-between gap-4"><span className="font-semibold">Total Investigations</span><b>{selected.length}</b></div><div className="flex justify-between gap-4"><span className="font-semibold">Estimated Amount</span><b>₹{total.toFixed(2)}</b></div><div className="flex justify-between gap-4"><span className="font-semibold">Discount</span><b>₹0.00</b></div></div><div className="flex items-end justify-between gap-3 py-5"><span className="text-sm font-black">Total Payable</span><b className="text-3xl font-black">₹{total.toFixed(2)}</b></div><button type="button" disabled={saving||!patient||!selected.length} onClick={()=>void place()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#061a38] px-5 py-4 text-sm font-black text-white shadow-lg transition hover:bg-[#0b315f] disabled:cursor-not-allowed disabled:opacity-45"><Icon name="cart" size={18}/>{saving?"Creating Draft Bill…":"Review & Continue to Billing"}</button>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}{message&&<p className="mt-3 rounded-lg bg-emerald-50 p-3 text-xs font-bold text-emerald-700">{message}</p>}</aside>
  </div></div></main>
}
function Step({n,label,sub}:{n:string;label:string;sub:string}){return <div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#061a38] text-xs font-black text-white shadow-md">{n}</div><div className="min-w-0"><p className="text-[10px] font-black tracking-[.12em]">{label}</p><p className="text-[10px] font-semibold text-[#354257]">{sub}</p></div></div>}
function PatientCard({patient,onChange}:{patient:Patient;onChange:()=>void}){return <div className="mt-3 flex items-center justify-between gap-3 rounded-xl border border-[#d8c16c] bg-[#fff7d4] p-3"><div><p className="text-[9px] font-black uppercase tracking-wider text-[#5a4200]">Selected patient</p><p className="mt-1 text-sm font-black">{patientName(patient)} <span className="font-semibold text-slate-500">· {patient.patientId}</span></p><p className="text-[10px] font-semibold text-slate-500">{patient.gender||"Gender not provided"}{patient.phone?` · ${patient.phone}`:""}</p></div><button type="button" onClick={onChange} className="rounded-lg border border-[#cbb45e] bg-white px-3 py-2 text-xs font-black">Change</button></div>}
function WalkInForm({data,setData,patient,onContinue,onChange,referral=false}:{data:{firstName:string;lastName:string;age:string;gender:string;phone:string};setData:React.Dispatch<React.SetStateAction<{firstName:string;lastName:string;age:string;gender:string;phone:string}>>;patient:Patient|null;onContinue:()=>void;onChange:()=>void;referral?:boolean}){return <div><div className="grid gap-3 sm:grid-cols-2"><input value={data.firstName} onChange={e=>setData(v=>({...v,firstName:e.target.value}))} placeholder="First name *" className="rounded-xl border border-[#d6c27a] bg-white px-4 py-3 text-sm font-bold outline-none focus:border-[#061a38]"/><input value={data.lastName} onChange={e=>setData(v=>({...v,lastName:e.target.value}))} placeholder="Last name *" className="rounded-xl border border-[#d6c27a] bg-white px-4 py-3 text-sm font-bold outline-none focus:border-[#061a38]"/><input value={data.age} onChange={e=>setData(v=>({...v,age:e.target.value.replace(/\D/g,"").slice(0,3)}))} placeholder="Age" inputMode="numeric" className="rounded-xl border border-[#d6c27a] bg-white px-4 py-3 text-sm font-bold outline-none focus:border-[#061a38]"/><select value={data.gender} onChange={e=>setData(v=>({...v,gender:e.target.value}))} className="rounded-xl border border-[#d6c27a] bg-white px-4 py-3 text-sm font-bold outline-none"><option value="">Gender</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select><input value={data.phone} onChange={e=>setData(v=>({...v,phone:e.target.value.replace(/\D/g,"").slice(0,10)}))} placeholder="Mobile number" inputMode="numeric" className="rounded-xl border border-[#d6c27a] bg-white px-4 py-3 text-sm font-bold outline-none sm:col-span-2"/></div>{!patient?<button type="button" onClick={onContinue} className="mt-4 rounded-xl bg-[#061a38] px-5 py-3 text-sm font-black text-white">Continue to Investigations →</button>:<PatientCard patient={patient} onChange={onChange}/>}<p className="mt-2 text-[10px] font-semibold text-[#665f48]">{referral?"Referral patient information will follow the same investigation and billing workflow.":"Walk-in / Outsider patient information will follow the same investigation and billing workflow."}</p></div>}
export default function Page(){return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-[#FDC823] font-black text-[#061a38]">Loading Investigation Orders…</main>}><Orders/></Suspense>}
