"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useSearchParams } from "next/navigation";

type Line={id:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;discount:number;netAmount:number;paymentStatus:string;paymentMethod:string|null;paidAmount:number;balanceAmount:number};
type Data={visit:{id:number;tokenNumber:number;visitType:string;status:string;department:string|null};patient:{patientId:string;name:string;phone:string|null};lineItems:Line[];totals:{subtotal:number};bill:Bill|null;consultationFee:number};
const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",OTHER:"Other Service"}[x]||x);
export default function BillingReview(){const s=useSearchParams();const visitId=Number(s.get("visitId")||0);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [discount,setDiscount]=useState("");const [pay,setPay]=useState("");const [method,setMethod]=useState("CASH");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);const d=await r.json();if(!r.ok)throw new Error(d.error||"Billing request failed.");return d};
 const load=async()=>{if(!visitId)return;setLoading(true);setError("");try{let d=await run(`/api/billing?visitId=${visitId}`);if(!d.bill){d=await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId})});d=await run(`/api/billing?visitId=${visitId}`)}setData(d)}catch(e){setError(e instanceof Error?e.message:"Unable to load invoice review.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[visitId]);
 const action=async(body:any)=>{setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId, ...body})});await load();setMessage("Bill updated successfully.")}catch(e){setError(e instanceof Error?e.message:"Unable to update bill.")}finally{setLoading(false)}};
 const process=async()=>{setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId,action:"processBill"})});await load();setMessage("Invoice processed. You can now take payment.")}catch(e){setError(e instanceof Error?e.message:"Unable to process invoice.")}finally{setLoading(false)}};
 const remove=async(id:number)=>{setLoading(true);try{const r=await fetch(`/api/billing?lineId=${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to remove charge");await load();setMessage("Charge removed from this invoice.")}catch(e){setError(e instanceof Error?e.message:"Unable to remove charge")}finally{setLoading(false)}};
 const applyDiscount=async()=>{if(!data?.bill)return;setLoading(true);setError("");try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discount",billId:data.bill.id,discount:Number(discount)})});await load();setMessage("Discount applied.")}catch(e){setError(e instanceof Error?e.message:"Unable to apply discount.")}finally{setLoading(false)}};
 const payment=async()=>{if(!data?.bill)return;const amount=Number(pay);const balance=Math.max(0,Number(data.bill.balanceAmount||0));if(balance<=0){setError("");setMessage("No payment is due for this invoice.");return}if(!Number.isFinite(amount)||amount<=0||amount>balance){setError("Enter a payment amount within the outstanding balance.");return}setLoading(true);setError("");try{const d=await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billId:data.bill.id,paidAmount:amount,paymentMethod:method})});setData(x=>x?{...x,bill:d.bill}:x);setPay("");setMessage(d.bill.paymentStatus==="PAID"?"Payment completed. Receipt is ready.":"Partial payment recorded.")}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.")}finally{setLoading(false)}};
 if(!visitId)return <main className="p-8">Invalid Visit.</main>;
 const bill=data?.bill;const paid=bill?.paymentStatus==="PAID";const subtotal=bill?.subtotal??data?.totals.subtotal??0;const net=bill?.netAmount??subtotal;const outstanding=Math.max(0,Number(bill?.balanceAmount??net));const noPaymentDue=Boolean(bill)&&outstanding<=0;return <main className="min-h-screen bg-[#fffaf0] p-4 text-[#172b3a] sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl space-y-5">
  <header className="rounded-[2rem] bg-gradient-to-br from-[#08483d] via-[#0d5b4c] to-[#176f5e] p-6 text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[.28em] text-[#f5d47b]">SAMS · Hospital Finance</p><h1 className="mt-2 text-3xl font-black">Invoice & Payment</h1><p className="mt-1 text-sm text-emerald-50">Selected Charges → Invoice → Payment → Receipt</p></header>
  {data&&<><section className="grid gap-3 sm:grid-cols-3"><Card t="Patient" v={data.patient.name}/><Card t="HID" v={data.patient.patientId}/><Card t="Visit" v={`#${data.visit.id} · Token #${data.visit.tokenNumber}`}/></section><section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Invoice</p><h2 className="text-2xl font-black text-[#0b2748]">{bill?.billNumber||"Draft Bill"}</h2></div><span className={`rounded-full px-4 py-2 text-xs font-black ${bill?.paymentStatus==="WAIVED"?"bg-emerald-50 text-emerald-700":"bg-[#edf5ee] text-[#0d5b4c]"}`}>{bill?.paymentStatus||"DRAFT"}</span></div><div className="mt-5 overflow-hidden rounded-2xl border"><div className="grid grid-cols-[1fr_130px_110px_90px] bg-[#fbf7ed] px-4 py-3 text-[9px] font-black uppercase text-slate-500"><span>Service</span><span>Type</span><span>Amount</span><span></span></div>{data.lineItems.map(l=><div key={l.id} className="grid grid-cols-[1fr_130px_110px_90px] items-center border-t px-4 py-3"><div><b className="text-sm text-[#0b2748]">{l.description}</b><p className="text-[10px] text-slate-400">Qty {l.quantity} × {money(l.unitPrice)}</p></div><span className="text-[10px] font-bold text-slate-500">{label(l.serviceType)}</span><b>{money(l.amount)}</b><button onClick={()=>void remove(l.id)} disabled={loading||paid||noPaymentDue} className="text-right text-[10px] font-black text-red-600 disabled:opacity-30">Remove</button></div>)}</div><div className="mt-5 flex flex-col items-end gap-3"><div className="flex w-full max-w-sm justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="flex w-full max-w-sm items-center justify-between gap-3"><span>Discount</span><span className="flex gap-2"><input value={discount} onChange={e=>setDiscount(e.target.value)} disabled={loading||paid||bill?.paymentStatus==="WAIVED"} placeholder="₹" className="w-24 rounded-lg border px-2 py-1"/><button onClick={()=>void applyDiscount()} disabled={loading||paid||bill?.paymentStatus==="WAIVED"||discount===""} className="rounded-lg bg-amber-500 px-3 py-1 text-xs font-black text-white disabled:opacity-40">Apply</button></span></div><div className="flex w-full max-w-sm justify-between border-t pt-3 text-xl font-black text-[#0b2748]"><span>Net Amount</span><span>{money(net)}</span></div><div className="flex w-full max-w-sm justify-between text-sm"><span>Paid</span><b>{money(bill?.paidAmount||0)}</b></div><div className={`flex w-full max-w-sm justify-between text-lg font-black ${noPaymentDue?"text-emerald-700":"text-red-700"}`}><span>Outstanding</span><span>{money(outstanding)}</span></div></div></section>
  {!paid&&bill&&!noPaymentDue&&<section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><div className="grid gap-4 lg:grid-cols-[1fr_160px_180px_auto]"><input value={pay} onChange={e=>setPay(e.target.value)} type="number" min="0" step="0.01" placeholder="Payment amount ₹" className="rounded-xl border px-4 py-3"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border px-3 py-3 font-bold"><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select><button onClick={()=>void payment()} disabled={loading||!pay} className="rounded-xl bg-[#0d5b4c] px-5 py-3 font-black text-white disabled:opacity-40">Record Payment</button><button onClick={()=>void process()} disabled={loading} className="rounded-xl border border-[#0d5b4c] px-5 py-3 font-black text-[#0d5b4c]">Process Invoice</button></div></section>}
  {!paid&&bill&&noPaymentDue&&<section className="rounded-[1.5rem] border border-emerald-200 bg-emerald-50 p-5"><p className="text-[9px] font-black uppercase tracking-widest text-emerald-700">No Payment Due</p><h3 className="mt-1 text-xl font-black text-emerald-900">This invoice is fully covered by discount.</h3><p className="mt-1 text-sm text-emerald-800">Outstanding balance is ₹0.00. No payment amount needs to be entered.</p></section>}
  {paid&&<section className="rounded-[1.5rem] border border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-emerald-700">Payment Complete</p><h3 className="text-xl font-black text-emerald-900">Receipt {bill?.receiptNumber||"generated"}</h3></div><Link href={`/billing/receipt?visitId=${data.visit.id}`} target="_blank" className="rounded-xl bg-[#0d5b4c] px-5 py-3 text-center text-xs font-black text-white">Open / Print Receipt →</Link></div></section>}
  <Link href="/billing" className="inline-flex rounded-xl border border-[#eadfca] bg-white px-5 py-3 text-xs font-black text-[#0d5b4c]">← Back to Patient Charges</Link></>}
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading&&!data&&<div className="rounded-2xl bg-white p-10 text-center font-bold">Loading invoice…</div>}
 </div></main>}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-[#eadfca] bg-white p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t}</p><p className="mt-1 font-black text-[#0b2748]">{v}</p></div>}
