"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type RequestItem = { id: number; action: string; requestedBy: string; createdAt: string; proposedData: Record<string, unknown>; current: { name: string; code: string } | null };

export default function InvestigationMasterApprovalsPage() {
  const [items, setItems] = useState<RequestItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const r = await fetch("/api/investigation-master/approvals", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setItems(d); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load approvals"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const decide = async (id: number, decision: "APPROVE" | "REJECT") => { const note = decision === "REJECT" ? window.prompt("Reason for rejection (optional):") || "Rejected by administrator" : "Approved by administrator"; const r = await fetch("/api/investigation-master/approvals", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, decision, reviewedBy: "ADMIN", reviewNote: note }) }); const d = await r.json(); if (!r.ok) { alert(d.error || "Unable to process request"); return; } await load(); };
  return <main className="min-h-screen bg-[#080d16] px-5 py-7 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-[1400px]"><header className="flex flex-wrap items-center justify-between gap-4 rounded-[1.7rem] border border-white/10 bg-[#101925] p-6"><div><p className="text-[9px] font-black uppercase tracking-[.28em] text-[#d9bb72]">SAMS · Administration</p><h1 className="mt-2 text-3xl font-black">Investigation Master Approvals</h1><p className="mt-2 text-sm text-slate-400">No Investigation Master change becomes live until an administrator approves it.</p></div><Link href="/admin" className="rounded-xl border border-white/10 bg-white/[.06] px-4 py-2 text-xs font-black">← Admin</Link></header>{error && <div className="mt-5 rounded-xl bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}<section className="mt-6 space-y-4">{loading ? <div className="rounded-2xl bg-white/[.05] p-8 text-slate-400">Loading approval requests…</div> : items.length === 0 ? <div className="rounded-2xl border border-white/10 bg-white/[.04] p-12 text-center text-slate-400">No pending Investigation Master changes.</div> : items.map((item) => <article key={item.id} className="rounded-[1.6rem] border border-white/10 bg-[#101925] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-[#d9bb72]/10 px-3 py-1 text-[9px] font-black uppercase tracking-wider text-[#e0c27a]">{item.action} · Pending</span><h2 className="mt-3 text-xl font-black">{String(item.proposedData.name || item.current?.name || "Investigation")}</h2><p className="mt-1 text-xs text-slate-500">{String(item.proposedData.code || item.current?.code || "")} · Requested by {item.requestedBy} · {new Date(item.createdAt).toLocaleString("en-IN")}</p></div><div className="flex gap-2"><button onClick={() => decide(item.id, "REJECT")} className="rounded-xl border border-red-400/20 bg-red-500/10 px-4 py-2.5 text-xs font-black text-red-200">Reject</button><button onClick={() => decide(item.id, "APPROVE")} className="rounded-xl bg-[#d9bb72] px-5 py-2.5 text-xs font-black text-[#10151d]">Approve & Publish</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["category","specimen","method","unit","referenceRange","maleReferenceRange","femaleReferenceRange","ageSpecificRange","criticalValue","rate"].map((key) => <div key={key} className="rounded-xl border border-white/10 bg-black/15 p-3"><p className="text-[8px] font-black uppercase tracking-wider text-slate-500">{key}</p><p className="mt-1 text-xs font-semibold text-slate-200">{String(item.proposedData[key] ?? "—")}</p></div>)}</div></article>)}</section></div></main>;
}
