import { NextRequest, NextResponse } from "next/server";
import { ensureAuthTables, hashPassword, verifySessionCookie, audit, generateTemporaryPassword, type SamsRole } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const roles: SamsRole[] = ["SUPER_ADMIN","ADMIN","DOCTOR","RECEPTION","BILLING","CLINICAL","LAB","PATIENT"];
function actor(req: NextRequest) { const s = verifySessionCookie(req.cookies.get("sams_session")?.value); return s && ["SUPER_ADMIN","ADMIN"].includes(s.role) ? s : null; }

export async function GET(req:NextRequest){try{if(!actor(req))return NextResponse.json({error:"Administrator permission required."},{status:403});await ensureAuthTables();const rows=await prisma.$queryRawUnsafe<Array<{id:number;username:string;displayName:string;role:string;active:boolean;departmentId:string|null;doctorId:string|null;forcePasswordChange:boolean;createdAt:string}>>(`SELECT "id","username","displayName","role","active","departmentId","doctorId","forcePasswordChange","createdAt" FROM "SamsUser" ORDER BY "username"`);return NextResponse.json(rows)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load users."},{status:500})}}

export async function POST(req:NextRequest){try{const a=actor(req);if(!a)return NextResponse.json({error:"Administrator permission required."},{status:403});await ensureAuthTables();const b=await req.json();const username=String(b.username||"").trim().toLowerCase(),displayName=String(b.displayName||username).trim(),role=b.role as SamsRole;let password=String(b.password||"");if(!username||!displayName||!roles.includes(role))return NextResponse.json({error:"Employee name, username and valid role are required."},{status:400});if(!password)password=generateTemporaryPassword();if(password.length<12)return NextResponse.json({error:"Password must be at least 12 characters."},{status:400});const existing=await prisma.$queryRawUnsafe<Array<{id:number}>>(`SELECT "id" FROM "SamsUser" WHERE "username"=? LIMIT 1`,username);if(existing.length)return NextResponse.json({error:"Username already exists."},{status:409});await prisma.$executeRawUnsafe(`INSERT INTO "SamsUser" ("username","displayName","passwordHash","role","departmentId","doctorId","forcePasswordChange","createdAt","updatedAt") VALUES (?,?,?,?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,username,displayName,hashPassword(password),role,b.departmentId?String(b.departmentId):null,b.doctorId?String(b.doctorId):null);await audit(a.userId,a.username,"CREATE","SamsUser",`${username} · ${role}`);return NextResponse.json({ok:true,username,temporaryPassword:password,requiresPasswordChange:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to create employee account."},{status:500})}}

export async function PATCH(req:NextRequest){try{const a=actor(req);if(!a)return NextResponse.json({error:"Administrator permission required."},{status:403});await ensureAuthTables();const b=await req.json(),id=Number(b.id);if(!id)return NextResponse.json({error:"Invalid employee account."},{status:400});if(b.active!==undefined)await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "active"=?,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,Boolean(b.active),id);if(b.role&&roles.includes(b.role as SamsRole))await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "role"=?,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,String(b.role),id);if(b.departmentId!==undefined)await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "departmentId"=?,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,b.departmentId?String(b.departmentId):null,id);if(b.doctorId!==undefined)await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "doctorId"=?,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,b.doctorId?String(b.doctorId):null,id);if(b.resetPassword){const password=generateTemporaryPassword();await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "passwordHash"=?,"forcePasswordChange"=1,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,hashPassword(password),id);await audit(a.userId,a.username,"RESET_PASSWORD","SamsUser",String(id));return NextResponse.json({ok:true,temporaryPassword:password,requiresPasswordChange:true})}if(b.password){const password=String(b.password);if(password.length<12)return NextResponse.json({error:"Password must be at least 12 characters."},{status:400});await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "passwordHash"=?,"forcePasswordChange"=1,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,hashPassword(password),id)}if(b.forcePasswordChange!==undefined)await prisma.$executeRawUnsafe(`UPDATE "SamsUser" SET "forcePasswordChange"=?,"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=?`,Boolean(b.forcePasswordChange),id);await audit(a.userId,a.username,"UPDATE","SamsUser",String(id));return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update employee account."},{status:500})}}
