"use client";

import { useState } from "react";

type Visit = { id:number; tokenNumber:number; visitType:string; status:string; department:string|null; createdAt:string };
type Bill = { id:number; billNumber:string; receiptNumber:string|null; netAmount:number; paymentStatus:string; paymentMethod:string|null; paidAmount:number; balanceAmount:number; paidAt:string|null };
type Data = { visit:Visit; patient:{id:number;patientId:string;name:string;phone:string|null}; investigations:{id:number;name:string;amount:number;paymentStatus:string}[]; prescriptions:{id:number;name:string;quantity:number;unitPrice:number;amount:number;billingStatus:string}[]; totals:{subtotal:number}; bill:Bill|null };
type Tab="charges"|"invoices"|"payments"|"reports";
const money=(n:number)=>`₹${n.toFixed(2)}`;

export default function BillingPage(){
 const [patientId,setPatientId]=useState(""); const [visits,setVisits]=useState<Visit[]>([]); const [patient,setPatient]=useState<{id:number;patientId:string;name:string;phone:string|null}|null>(null); const [data,setData]=useState<Data|null>(null); const [tab,setTab]=useState<Tab>("charges"); const [amount,setAmount]=useState(""); const [method,setMethod]=useState("CASH"); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 async function findPatient(){ setLoading(true);setError("");setMessage("");setData(null);setVisits([]);try{const r=await fetch(`/api/billing?patientId=${encodeURIComponent(patientId.trim())}`);const x=await r.json();if(!r.ok)throw new Error(x.error);setPatient(x.patient);setVisits(x.visits);if(!x.visits.length)setMessage("Patient found, but no OPD visits are recorded yet.");}catch(e){setPatient(null);setError(e instanceof Error?e.message:"Unable to find patient.");}finally{setLoading(false)} }
 async function loadVisit(id:number){setLoading(true);setError("");setMessage("");try{const r=await fetch(`/api/billing?visitId=${id}`);const x=await r.json();if(!r.ok)throw new Error(x.error);setData(x);setPatient(x.patient);setTab("charges");}catch(e){setError(e instanceof Error?e.message:"Unable to load visit.");}finally{setLoading(false)} }
 async function generateBill(){if(!data)return;setLoading(true);setError("");try{const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:data.visit.id})});const x=await r.json();if(!r.ok)throw new Error(x.error);setData({...data,bill:x.bill});setMessage(x.existing?"Existing invoice loaded.":"Invoice generated successfully.");setTab("invoices");}catch(e){setError(e instanceof Error?e.message:"Unable to generate bill.");}finally{setLoading(false)} }
 async function pay(){if(!data?.bill)return;const n=Number(amount);if(!Number.isFinite(n)||n<=0){setError("Enter a valid payment amount.");return}if(n>data.bill.balanceAmount){setError("Payment cannot exceed the outstanding balance.");return}setLoading(true);setError("");try{const r=await fetch("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billId:data.bill.id,paidAmount:n,paymentMethod:method})});const x=await r.json();if(!r.ok)throw new Error(x.error);setData({...data,bill:x.bill});setAmount("");setMessage("Payment recorded successfully.");setTab("payments");}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.");}finally{setLoading(false)} }
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl space-y-6"><header><p className="text-xs font-black uppercase tracking-widest text-blue-600">SAMS · Hospital Finance</p><h1 className="mt-1 text-3xl font-black text-[#082b61]">Billing & Payments</h1><p className="mt-1 text-sm text-slate-500">Patient charges, invoices, payments and billing reports.</p></header>
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><input value={patientId} onChange={e=>setPatientId(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void findPatient()} placeholder="Enter Patient ID (e.g. SAMS-0004)" className="flex-1 rounded-xl border px-4 py-3"/><button onClick={()=>void findPatient()} disabled={loading||!patientId.trim()} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-50">{loading?"Loading...":"Load Patient"}</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}</section>
 {patient&&!data&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-[#082b61]">{patient.name}</h2><p className="text-sm text-slate-500">Patient ID: <b>{patient.patientId}</b>{patient.phone?` · ${patient.phone}`:""}</p></div><span className="rounded-full bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">{visits.length} OPD visit{visits.length===1?"":"s"}</span></div><div className="mt-5 space-y-3">{visits.map(v=><button key={v.id} onClick={()=>void loadVisit(v.id)} className="flex w-full items-center justify-between rounded-xl border p-4 text-left hover:border-blue-400 hover:bg-blue-50"><span><b>OPD Visit #{v.id}</b><span className="ml-3 text-xs text-slate-500">Token {v.tokenNumber} · {v.visitType} · {v.department||"Department not specified"}</span></span><span className="text-xs font-bold text-blue-600">Select →</span></button>)}</div></section>}
 {data&&<><section className="grid gap-3 sm:grid-cols-4"><Card t="Patient" v={data.patient.name}/><Card t="Patient ID" v={data.patient.patientId}/><Card t="OPD Visit" v={`#${data.visit.id}`}/><Card t="Balance" v={money(data.bill?.balanceAmount??data.totals.subtotal)}/></section><nav className="grid grid-cols-2 gap-2 rounded-2xl border bg-white p-2 sm:grid-cols-4">{([["charges","Patient Charges"],["invoices","Invoices"],["payments","Payments"],["reports","Billing Reports"]] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-3 py-3 text-sm font-bold ${tab===k?"bg-blue-600 text-white":"hover:bg-slate-50"}`}>{l}</button>)}</nav>
 {tab==="charges"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Patient Charges</h2><div className="mt-4 space-y-2">{data.investigations.map(x=><Line key={`i${x.id}`} n={x.name} d={`Investigation · ${x.paymentStatus}`} a={x.amount}/>)}{data.prescriptions.map(x=><Line key={`p${x.id}`} n={x.name} d={`Medicine · ${x.quantity} × ${money(x.unitPrice)}`} a={x.amount}/>)}{!data.investigations.length&&!data.prescriptions.length&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No billable charges found for this OPD visit.</p>}</div><div className="mt-5 flex justify-between border-t pt-5 font-black"><span>Total</span><span>{money(data.totals.subtotal)}</span></div><button onClick={()=>void generateBill()} disabled={loading||!!data.bill} className="mt-5 rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white disabled:opacity-50">{data.bill?"Invoice Already Generated":"Generate Invoice"}</button></section>}
 {tab==="invoices"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Invoices</h2>{!data.bill?<><p className="mt-3 text-sm text-slate-500">No invoice generated for this visit.</p><button onClick={()=>void generateBill()} disabled={loading} className="mt-5 rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white">Generate Invoice</button></>:<div className="mt-5 grid gap-3 sm:grid-cols-4"><Card t="Invoice" v={data.bill.billNumber}/><Card t="Net Amount" v={money(data.bill.netAmount)}/><Card t="Paid" v={money(data.bill.paidAmount)}/><Card t="Status" v={data.bill.paymentStatus}/></div>}</section>}
 {tab==="payments"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Payments</h2>{!data.bill?<p className="mt-3 text-sm text-slate-500">Generate an invoice first.</p>:data.bill.balanceAmount<=0?<p className="mt-4 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">Fully paid · Receipt {data.bill.receiptNumber}</p>:<div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="number" min="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={`Amount (max ${money(data.bill!.balanceAmount)})`} className="rounded-xl border px-4 py-3"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border px-4 py-3"><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select><button onClick={()=>void pay()} disabled={loading} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Record Payment</button></div>}</section>}
 {tab==="reports"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Billing Reports</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Card t="Charges" v={money(data.totals.subtotal)}/><Card t="Invoice" v={data.bill?.billNumber||"Not generated"}/><Card t="Outstanding" v={money(data.bill?.balanceAmount??data.totals.subtotal)}/></div></section>}
 </>}
 </div></main>;
}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{t}</p><p className="mt-2 truncate font-black text-[#082b61]">{v}</p></div>}
function Line({n,d,a}:{n:string;d:string;a:number}){return <div className="flex justify-between border-b py-3"><div><b>{n}</b><p className="text-xs text-slate-500">{d}</p></div><b>{money(a)}</b></div>}
