import Navigation from "@/components/Navigation";
import Sidebar from "@/components/Sidebar";
import { prisma } from "@/lib/prisma";

export default async function PatientListPage() {
  const patients = await prisma.patient.findMany({
      orderBy: {
            createdAt: "desc",
                },
                  });

                    return (
                        <main>
                              <Sidebar />

                                    <div>
                                            <Navigation />

                                                    <header>
                                                              <h1>Patient List</h1>
                                                                        <p>Patient registry and records</p>
                                                                                </header>

                                                                                        <section>
                                                                                                  <input
                                                                                                              type="search"
                                                                                                                          placeholder="Search patients..."
                                                                                                                                      aria-label="Search patients"
                                                                                                                                                />
                                                                                                                                                        </section>

                                                                                                                                                                <section>
                                                                                                                                                                          <h2>Registered Patients</h2>

                                                                                                                                                                                    {patients.length === 0 ? (
                                                                                                                                                                                                <p>No patients registered yet.</p>
                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                      <table>
                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                      <th>Patient ID</th>
                                                                                                                                                                                                                                                                                        <th>Name</th>
                                                                                                                                                                                                                                                                                                          <th>Gender</th>
                                                                                                                                                                                                                                                                                                                            <th>Phone</th>
                                                                                                                                                                                                                                                                                                                                              <th>Registration Date</th>
                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                            </thead>

                                                                                                                                                                                                                                                                                                                                                                                          <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                          {patients.map((patient) => (
                                                                                                                                                                                                                                                                                                                                                                                                                            <tr key={patient.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>{patient.patientId}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href={`/patients/profile/${patient.id}`}>{patient.firstName} {patient.lastName}</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>{patient.gender || "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>{patient.phone || "-"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>{patient.createdAt.toLocaleDateString()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="/patients/new">+ Register New Patient</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }