"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";

type PatientIndex={id:number;patientId:string;firstName:string;lastName:string;gender:string|null;phone:string|null;dateOfBirth:string|null};
type Investigation={id:number;investigation:string;status:string;reportText:string|null;createdAt:string};
type Visit={id:number;tokenNumber:number;visitType:string;status:string;createdAt:string;departmentMaster:{name:string}|null;doctor:{name:string}|null;investigationOrders:Investigation[]};
type Encounter={id:number;encounterDate:string;speciality:string|null;chiefComplaint:string|null;diagnosis:string|null;clinicalNotes:string|null;treatmentPlan:string|null;followUpDate:string|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;netAmount:number;paymentStatus:string;paidAmount:number;balanceAmount:number;createdAt:string;lineItems:{id:number;description:string;quantity:number;unitPrice:number;amount:number}[]};
type Patient=PatientIndex&{encounters:Encounter[];opdVisits:Visit[];billingRecords:Bill[]};
type Doctor={id:number;name:string;qualification:string|null;departmentId:number|null;department:{id:number;name:string;code:string}|null};
type Appointment={id:number;appointmentNo:string;appointmentDate:string;appointmentTime:string;doctorName:string;departmentName:string|null;status:string;reason:string|null;tokenNumber:number|null};

const dateText=(v:string|null)=>v?new Date(v).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const money=(v:number)=>`₹${Number(v||0).toFixed(2)}`;

export default function PatientPortalPage(){
 const [patients,setPatients]=useState<PatientIndex[]>([]),[query,setQuery]=useState(""),[patient,setPatient]=useState<Patient|null>(null),[appointments,setAppointments]=useState<Appointment[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[active,setActive]=useState("overview"),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[showBooking,setShowBooking]=useState(false),[doctorId,setDoctorId]=useState(""),[appointmentDate,setAppointmentDate]=useState(""),[appointmentTime,setAppointmentTime]=useState(""),[reason,setReason]=useState(""),[booking,setBooking]=useState(false);
 useEffect(()=>{Promise.all([fetch("/api/patients",{cache:"no-store"}).then(r=>r.json()),fetch("/api/doctors",{cache:"no-store"}).then(r=>r.json())]).then(([p,d])=>{setPatients(Array.isArray(p)?p:[]);setDoctors(Array.isArray(d)?d:[])}).catch(()=>setError("Unable to load administrative portal data.")).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return patients.slice(0,30);return patients.filter(p=>`${p.patientId} ${p.firstName} ${p.lastName} ${p.phone||""}`.toLowerCase().includes(q)).slice(0,30)},[patients,query]);
 const doctor=useMemo(()=>doctors.find(d=>String(d.id)===doctorId)||null,[doctors,doctorId]);
 async function openPatient(id:string){setOpening(true);setError("");setMessage("");try{const r=await fetch(`/api/patients/${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to open patient record.");setPatient(d);const ar=await fetch(`/api/appointments?patientId=${d.id}`,{cache:"no-store"});const ad=await ar.json();setAppointments(Array.isArray(ad)?ad:[]);setActive("overview")}catch(e){setError(e instanceof Error?e.message:"Unable to open patient record.")}finally{setOpening(false)}}
 function backToSearch(){setPatient(null);setAppointments([]);setActive("overview");setMessage("")}
 async function book(e:FormEvent){e.preventDefault();if(!patient||!doctor||!appointmentDate||!appointmentTime)return;setBooking(true);setError("");try{const dep=doctor.department;const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:patient.id,patientType:"existing",patientName:`${patient.firstName} ${patient.lastName}`,mobile:patient.phone||null,doctorId:doctor.id,doctorName:doctor.name,departmentId:dep?.id||null,departmentName:dep?.name||null,appointmentDate,appointmentTime,reason,source:"ADMIN"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to book appointment.");setAppointments(a=>[...a,d]);setShowBooking(false);setDoctorId("");setAppointmentDate("");setAppointmentTime("");setReason("");setMessage(`Appointment ${d.appointmentNo} created successfully.`)}catch(e){setError(e instanceof Error?e.message:"Unable to book appointment.")}finally{setBooking(false)}}
 if(!patient)return <main className="min-h-screen bg-[#f4f7fb] px-5 py-7 text-slate-900"><div className="mx-auto max-w-7xl"><header className="rounded-[1.6rem] border border-slate-200 bg-white px-6 py-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#0b63ce]">SAMS · Administrative Workspace</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black text-[#082b61]">Patient Portal</h1><p className="mt-1 text-sm text-slate-500">Administrative patient overview. This page is staff-only and is not a patient login portal.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-emerald-700">Administrative access</span></div></header><section className="mt-5 rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Patient ID, name or mobile…" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold outline-none focus:border-[#0b63ce]"/><button onClick={()=>setQuery("")} className="rounded-xl border border-slate-200 px-5 py-3 text-xs font-black">Clear</button></div>{error&&<p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-4 overflow-x-auto rounded-xl border border-slate-100"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-[9px] font-black uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Patient ID</th><th className="px-4 py-3">Mobile</th><th className="px-4 py-3">DOB</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-4 py-3"><b className="text-[#082b61]">{p.firstName} {p.lastName}</b><p className="text-[10px] text-slate-400">{p.gender||"—"}</p></td><td className="px-4 py-3 font-mono text-xs">{p.patientId}</td><td className="px-4 py-3 text-slate-600">{p.phone||"—"}</td><td className="px-4 py-3 text-slate-600">{dateText(p.dateOfBirth)}</td><td className="px-4 py-3 text-right"><button disabled={opening} onClick={()=>openPatient(p.patientId)} className="rounded-lg bg-[#082b61] px-3 py-2 text-[10px] font-black text-white disabled:opacity-50">Open Portal</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={5} className="px-4 py-12 text-center text-sm text-slate-400">No matching patients found.</td></tr>}</tbody></table></div><p className="mt-3 text-[10px] font-semibold text-slate-400">Showing {filtered.length} patient{filtered.length===1?"":"s"}. Select a patient to open the integrated administrative record.</p></section></div></main>;
 const investigations=patient.opdVisits.flatMap(v=>v.investigationOrders.map(i=>({...i,date:v.createdAt,doctor:v.doctor?.name||"SAMS"})));const outstanding=patient.billingRecords.reduce((s,b)=>s+Number(b.balanceAmount||0),0);
 return <main className="min-h-screen bg-[#f4f7fb] text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#0b63ce]">SAMS · Administrative Patient Portal</p><h1 className="text-lg font-black text-[#082b61]">{patient.firstName} {patient.lastName}</h1><p className="text-xs text-slate-400">Patient ID · {patient.patientId}</p></div><button onClick={backToSearch} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black">← Patient Search</button></div></header><div className="mx-auto max-w-7xl px-5 py-7"><section className="rounded-[2rem] bg-gradient-to-br from-[#082b61] to-[#0b63ce] p-7 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-200">Administrative view</p><h2 className="mt-2 text-3xl font-black">{patient.firstName} {patient.lastName}</h2><p className="mt-2 text-sm text-blue-100">{patient.gender||"—"} · DOB {dateText(patient.dateOfBirth)} · Mobile {patient.phone||"Not registered"}</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-wider">Staff workspace</span></div><div className="mt-5 flex flex-wrap gap-3"><Stat label="Visits" value={String(patient.opdVisits.length)}/><Stat label="Bills" value={String(patient.billingRecords.length)}/><Stat label="Outstanding" value={money(outstanding)}/><Stat label="Investigations" value={String(investigations.length)}/></div></section><div className="mt-6 flex flex-wrap gap-2">{[["overview","Overview"],["appointments","Appointments"],["records","Clinical / Visits"],["reports","Investigations"],["billing","Billing & Payments"]].map(([k,l])=><button key={k} onClick={()=>setActive(k)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${active===k?"bg-[#082b61] text-white":"border border-slate-200 bg-white text-slate-600"}`}>{l}</button>)}<button onClick={()=>setShowBooking(true)} className="rounded-xl bg-[#0b63ce] px-4 py-2.5 text-xs font-black text-white">+ New Appointment</button></div>{message&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}
 {active==="overview"&&<div className="mt-6 grid gap-4 md:grid-cols-2"><Info title="Patient Information"><Row label="Patient ID" value={patient.patientId}/><Row label="Name" value={`${patient.firstName} ${patient.lastName}`}/><Row label="Gender" value={patient.gender||"—"}/><Row label="DOB" value={dateText(patient.dateOfBirth)}/><Row label="Mobile" value={patient.phone||"—"}/></Info><Info title="Latest Activity"><Row label="Visits" value={String(patient.opdVisits.length)}/><Row label="Appointments" value={String(appointments.length)}/><Row label="Investigations" value={String(investigations.length)}/><Row label="Outstanding" value={money(outstanding)}/></Info></div>}
 {active==="appointments"&&<Panel title="Appointments">{appointments.length?appointments.map(a=><article key={a.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b className="text-[#082b61]">{a.doctorName}</b><p className="mt-1 text-sm text-slate-500">{a.departmentName||"Consultation"} · {a.reason||"General consultation"}</p><p className="mt-2 text-xs text-slate-400">{a.appointmentNo} · {a.appointmentDate} · {a.appointmentTime}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase text-[#0b63ce]">{a.status}</span></div></article>):<Empty text="No appointments found."/>}</Panel>}
 {active==="records"&&<Panel title="Clinical / Visit Records">{patient.encounters.length?patient.encounters.map(e=><article key={e.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><b className="text-[#082b61]">{e.speciality||"Clinical Visit"}</b><span className="text-xs text-slate-400">{dateText(e.encounterDate)}</span></div>{e.chiefComplaint&&<p className="mt-3 text-sm"><b>Chief complaint:</b> {e.chiefComplaint}</p>}{e.diagnosis&&<p className="mt-2 text-sm"><b>Diagnosis:</b> {e.diagnosis}</p>}{e.clinicalNotes&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{e.clinicalNotes}</p>}{e.treatmentPlan&&<p className="mt-2 text-sm"><b>Plan:</b> {e.treatmentPlan}</p>}{e.followUpDate&&<p className="mt-3 text-xs font-bold text-[#0b63ce]">Follow-up: {dateText(e.followUpDate)}</p>}</article>):<Empty text="No clinical records are available yet."/>}</Panel>}
 {active==="reports"&&<Panel title="Investigation Reports">{investigations.length?investigations.map(i=><article key={i.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-[#082b61]">{i.investigation}</b><p className="mt-1 text-xs text-slate-400">{dateText(i.date)} · {i.doctor}</p></div><span className="text-xs font-black">{i.reportText?"Report available":i.status}</span></div>{i.reportText&&<p className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{i.reportText}</p>}</article>):<Empty text="No investigation reports are available yet."/>}</Panel>}
 {active==="billing"&&<Panel title="Billing & Payments">{patient.billingRecords.length?patient.billingRecords.map(b=><article key={b.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-[#082b61]">{b.billNumber}</b><p className="mt-1 text-xs text-slate-400">{dateText(b.createdAt)} · {b.paymentStatus}</p></div><div className="text-right"><b>{money(b.netAmount)}</b><p className="text-xs text-slate-500">Paid {money(b.paidAmount)} · Balance {money(b.balanceAmount)}</p></div></div>{b.lineItems.length>0&&<div className="mt-4 space-y-1 text-sm text-slate-600">{b.lineItems.map(i=><p key={i.id}>{i.description} × {i.quantity} — {money(i.amount)}</p>)}</div>}</article>):<Empty text="No billing records are available yet."/>}</Panel>}
 {showBooking&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5"><form onSubmit={book} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-wider text-[#0b63ce]">Administrative action</p><h3 className="text-xl font-black text-[#082b61]">New Appointment</h3></div><button type="button" onClick={()=>setShowBooking(false)} className="text-xl">×</button></div><select value={doctorId} onChange={e=>setDoctorId(e.target.value)} required className="mt-5 w-full rounded-xl border px-4 py-3"><option value="">Select doctor</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name} · {d.department?.name||"Department"}</option>)}</select><input type="date" value={appointmentDate} onChange={e=>setAppointmentDate(e.target.value)} required className="mt-3 w-full rounded-xl border px-4 py-3"/><input type="time" value={appointmentTime} onChange={e=>setAppointmentTime(e.target.value)} required className="mt-3 w-full rounded-xl border px-4 py-3"/><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for visit (optional)" className="mt-3 min-h-24 w-full rounded-xl border px-4 py-3"/><button disabled={booking} className="mt-4 w-full rounded-xl bg-[#082b61] px-4 py-3 font-black text-white">{booking?"Creating…":"Create Appointment"}</button></form></div>}
 </div></main>;
}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="mt-6 space-y-3"><h3 className="text-xl font-black text-[#082b61]">{title}</h3>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">{text}</div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/10 px-5 py-3"><p className="text-[10px] font-black uppercase text-blue-200">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function Info({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border bg-white p-5"><h3 className="font-black text-[#082b61]">{title}</h3><div className="mt-4 divide-y">{children}</div></section>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 py-3 text-sm"><span className="text-slate-500">{label}</span><b className="text-right text-slate-800">{value}</b></div>}
