"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";

type Investigation={id:number;investigation:string;status:string;reportText:string|null;reportedAt:string|null;createdAt:string};
type Visit={id:number;tokenNumber:number;visitType:string;status:string;createdAt:string;departmentMaster:{name:string}|null;doctor:{name:string}|null;investigationOrders:Investigation[]};
type Encounter={id:number;encounterDate:string;speciality:string|null;chiefComplaint:string|null;diagnosis:string|null;clinicalNotes:string|null;treatmentPlan:string|null;followUpDate:string|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;netAmount:number;paymentStatus:string;paidAmount:number;balanceAmount:number;createdAt:string;lineItems:{id:number;description:string;quantity:number;unitPrice:number;amount:number}[]};
type Patient={id:number;patientId:string;firstName:string;lastName:string;dateOfBirth:string|null;gender:string|null;phone:string|null;encounters:Encounter[];opdVisits:Visit[];billingRecords:Bill[]};
type Doctor={id:number;name:string;qualification:string|null;departmentId:number|null;department:{id:number;name:string;code:string}|null};
type Appointment={id:number;appointmentNo:string;appointmentDate:string;appointmentTime:string;doctorName:string;departmentName:string|null;status:string;reason:string|null;tokenNumber:number|null};

const dateText=(v:string|null)=>v?new Date(v).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const money=(v:number)=>`₹${Number(v||0).toFixed(2)}`;

export default function PatientPortalPage(){
 const[patient,setPatient]=useState<Patient|null>(null),[patientId,setPatientId]=useState(""),[appointments,setAppointments]=useState<Appointment[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[active,setActive]=useState("appointments"),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[showBooking,setShowBooking]=useState(false),[doctorId,setDoctorId]=useState(""),[appointmentDate,setAppointmentDate]=useState(""),[appointmentTime,setAppointmentTime]=useState(""),[reason,setReason]=useState(""),[booking,setBooking]=useState(false);
 useEffect(()=>{fetch("/api/doctors").then(r=>r.json()).then(d=>setDoctors(Array.isArray(d)?d:[])).catch(()=>undefined)},[]);
 const doctor=useMemo(()=>doctors.find(d=>String(d.id)===doctorId)||null,[doctors,doctorId]);
 async function loadPortal(e?:FormEvent){e?.preventDefault();setLoading(true);setError("");setMessage("");try{const id=patientId.trim();if(!id)throw new Error("Patient ID is required.");const r=await fetch(`/api/patients/${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to verify patient.");setPatient(d);const ar=await fetch(`/api/appointments?patientId=${d.id}`);const ad=await ar.json();setAppointments(Array.isArray(ad)?ad:[]);setActive("appointments")}catch(e){setPatient(null);setAppointments([]);setError(e instanceof Error?e.message:"Unable to open patient portal.")}finally{setLoading(false)}}
 function signOut(){setPatient(null);setPatientId("");setAppointments([]);setError("");setMessage("")}
 async function book(e:FormEvent){e.preventDefault();if(!patient||!doctor||!appointmentDate||!appointmentTime)return;setBooking(true);setError("");setMessage("");try{const dep=doctor.department;const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:patient.id,patientType:"existing",patientName:`${patient.firstName} ${patient.lastName}`,mobile:patient.phone||null,doctorId:doctor.id,doctorName:doctor.name,departmentId:dep?.id||null,departmentName:dep?.name||null,appointmentDate,appointmentTime,reason,source:"ONLINE"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to book appointment.");setAppointments(a=>[...a,d]);setShowBooking(false);setDoctorId("");setAppointmentDate("");setAppointmentTime("");setReason("");setMessage(`Appointment ${d.appointmentNo} booked successfully.`)}catch(e){setError(e instanceof Error?e.message:"Unable to book appointment.")}finally{setBooking(false)}}
 if(!patient)return <main className="min-h-screen bg-[#f4f7fb] px-5 py-10 text-slate-900"><div className="mx-auto max-w-xl"><div className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl"><div className="bg-gradient-to-br from-[#082b61] to-[#0b63ce] p-8 text-white"><p className="text-[10px] font-black uppercase tracking-[.25em] text-blue-200">SAMS · Patient Services</p><h1 className="mt-3 text-3xl font-black">Patient Portal</h1><p className="mt-2 text-sm leading-6 text-blue-100">Access appointments, medical records, investigation reports and billing information.</p></div><form onSubmit={loadPortal} className="space-y-4 p-8"><label className="block text-xs font-black uppercase tracking-wider text-slate-500">Patient ID<input value={patientId} onChange={e=>setPatientId(e.target.value)} placeholder="e.g. SAMS-0001" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-[#0b63ce]"/></label><p className="text-xs text-slate-500">Registered mobile number is <b>not required</b> to access the portal.</p>{error&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#082b61] px-5 py-3 font-black text-white disabled:opacity-50">{loading?"Opening…":"Open My Portal"}</button></form></div></div></main>;
 const investigations=patient.opdVisits.flatMap(v=>v.investigationOrders.map(i=>({...i,date:v.createdAt,doctor:v.doctor?.name||"SAMS"})));const outstanding=patient.billingRecords.reduce((s,b)=>s+Number(b.balanceAmount||0),0);
 return <main className="min-h-screen bg-[#f4f7fb] text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#0b63ce]">SAMS · Patient Portal</p><h1 className="text-lg font-black text-[#082b61]">Welcome, {patient.firstName}</h1></div><button onClick={signOut} className="rounded-xl border px-4 py-2 text-xs font-black">Sign out</button></div></header><div className="mx-auto max-w-7xl px-5 py-7"><section className="rounded-[2rem] bg-gradient-to-br from-[#082b61] to-[#0b63ce] p-7 text-white shadow-lg"><p className="text-[10px] font-black uppercase tracking-[.22em] text-blue-200">Patient ID · {patient.patientId}</p><h2 className="mt-2 text-3xl font-black">{patient.firstName} {patient.lastName}</h2><p className="mt-2 text-sm text-blue-100">{patient.gender||"—"} · DOB {dateText(patient.dateOfBirth)} · Mobile {patient.phone?`•••• ${patient.phone.slice(-4)}`:"Not registered"}</p><div className="mt-5 flex flex-wrap gap-3"><Stat label="Visits" value={String(patient.opdVisits.length)}/><Stat label="Outstanding" value={money(outstanding)}/></div></section><div className="mt-6 flex flex-wrap gap-2">{[["appointments","Appointments"],["records","Medical Records"],["reports","Reports"],["billing","Billing & Payments"]].map(([k,l])=><button key={k} onClick={()=>setActive(k)} className={`rounded-xl px-4 py-2.5 text-xs font-black ${active===k?"bg-[#082b61] text-white":"border bg-white text-slate-600"}`}>{l}</button>)}<button onClick={()=>setShowBooking(true)} className="rounded-xl bg-[#0b63ce] px-4 py-2.5 text-xs font-black text-white">+ Book Appointment</button></div>{message&&<p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}
 {active==="appointments"&&<Panel title="My Appointments">{appointments.length?appointments.map(a=><article key={a.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b className="text-[#082b61]">{a.doctorName}</b><p className="mt-1 text-sm text-slate-500">{a.departmentName||"Consultation"} · {a.reason||"General consultation"}</p><p className="mt-2 text-xs text-slate-400">{a.appointmentNo} · {a.appointmentDate} · {a.appointmentTime}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase text-[#0b63ce]">{a.status}</span></div></article>):<Empty text="No appointments found."/>}</Panel>}
 {active==="records"&&<Panel title="Medical Records">{patient.encounters.length?patient.encounters.map(e=><article key={e.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><b className="text-[#082b61]">{e.speciality||"Clinical Visit"}</b><span className="text-xs text-slate-400">{dateText(e.encounterDate)}</span></div>{e.chiefComplaint&&<p className="mt-3 text-sm"><b>Chief complaint:</b> {e.chiefComplaint}</p>}{e.diagnosis&&<p className="mt-2 text-sm"><b>Diagnosis:</b> {e.diagnosis}</p>}{e.clinicalNotes&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{e.clinicalNotes}</p>}{e.treatmentPlan&&<p className="mt-2 text-sm"><b>Plan:</b> {e.treatmentPlan}</p>}{e.followUpDate&&<p className="mt-3 text-xs font-bold text-[#0b63ce]">Follow-up: {dateText(e.followUpDate)}</p>}</article>):<Empty text="No clinical records are available yet."/>}</Panel>}
 {active==="reports"&&<Panel title="Investigation Reports">{investigations.length?investigations.map(i=><article key={i.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-[#082b61]">{i.investigation}</b><p className="mt-1 text-xs text-slate-400">{dateText(i.date)} · {i.doctor}</p></div><span className="text-xs font-black">{i.reportText?"Report available":i.status}</span></div>{i.reportText&&<p className="mt-4 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{i.reportText}</p>}</article>):<Empty text="No investigation reports are available yet."/>}</Panel>}
 {active==="billing"&&<Panel title="Billing & Payments">{patient.billingRecords.length?patient.billingRecords.map(b=><article key={b.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-[#082b61]">{b.billNumber}</b><p className="mt-1 text-xs text-slate-400">{dateText(b.createdAt)} · {b.paymentStatus}</p></div><div className="text-right"><b>{money(b.netAmount)}</b><p className="text-xs text-slate-500">Balance {money(b.balanceAmount)}</p></div></div>{b.lineItems.length>0&&<div className="mt-4 space-y-1 text-sm text-slate-600">{b.lineItems.map(i=><p key={i.id}>{i.description} × {i.quantity} — {money(i.amount)}</p>)}</div>}</article>):<Empty text="No billing records are available yet."/>}</Panel>}
 {showBooking&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-5"><form onSubmit={book} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-xl font-black text-[#082b61]">Book Appointment</h3><button type="button" onClick={()=>setShowBooking(false)} className="text-xl">×</button></div><select value={doctorId} onChange={e=>setDoctorId(e.target.value)} required className="mt-5 w-full rounded-xl border px-4 py-3"><option value="">Select doctor</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name} · {d.department?.name||"Department"}</option>)}</select><input type="date" value={appointmentDate} onChange={e=>setAppointmentDate(e.target.value)} required className="mt-3 w-full rounded-xl border px-4 py-3"/><input type="time" value={appointmentTime} onChange={e=>setAppointmentTime(e.target.value)} required className="mt-3 w-full rounded-xl border px-4 py-3"/><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for visit (optional)" className="mt-3 min-h-24 w-full rounded-xl border px-4 py-3"/><button disabled={booking} className="mt-4 w-full rounded-xl bg-[#082b61] px-4 py-3 font-black text-white">{booking?"Booking…":"Confirm Appointment"}</button></form></div>}</div>;
}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="mt-6 space-y-3"><h3 className="text-xl font-black text-[#082b61]">{title}</h3>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">{text}</div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/10 px-5 py-3"><p className="text-[10px] font-black uppercase text-blue-200">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
