"use client";
import {useMemo,useState} from "react";
type Visit={id:number;tokenNumber:number;visitType:string;status:string;department:string|null;doctor:string|null;createdAt:string};
type Patient={id:number;patientId:string;name:string;age:number|null;gender:string|null;phone:string|null;outstanding:number;visits:Visit[]};
type Line={id:number;visitId:number;visitDate:string;doctor:string|null;department:string|null;tokenNumber:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null;sourceId:number|null;billStatus:string;billingRecordId:number|null};
type Profile={patient:{id:number;patientId:string;name:string;age:number|null;gender:string|null;phone:string|null};visits:Visit[];lines:Line[];bills:{id:number;billNumber:string;visitId:number|null;paymentStatus:string;netAmount:number;paidAmount:number;balanceAmount:number;discount:number;createdAt:string}[];outstanding:number};
const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
const status=(s:string)=>({PAID:"Paid",PARTIAL:"Partially Unpaid",UNPAID:"Unpaid",UNBILLED:"Unpaid",DISCARDED:"Discarded"}[s]||s);
const source=(s:string|null)=>s==="INVESTIGATION_ORDER"?"Investigation Order":s==="OPD_VISIT"?"OPD Visit":s==="PRESCRIPTION"?"Prescription":s==="MANUAL"?"Manual":"Service";
const service=(s:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",IPD:"IPD",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",OTHER:"Other Service"}[s]||s);
const buckets=[{key:"PAID",title:"Paid",sub:"Fully settled charges",badge:"bg-emerald-50 text-emerald-700",border:"border-emerald-200"},{key:"PARTIAL",title:"Partially Unpaid",sub:"Part payment received · balance remains",badge:"bg-amber-50 text-amber-700",border:"border-amber-200"},{key:"UNPAID",title:"Unpaid",sub:"Not yet paid / not yet billed",badge:"bg-red-50 text-red-700",border:"border-red-200"}] as const;
export default function PatientChargesPage(){
 const [by,setBy]=useState("hid"),[query,setQuery]=useState(""),[results,setResults]=useState<Patient[]>([]),[profile,setProfile]=useState<Profile|null>(null),[selected,setSelected]=useState<number[]>([]),[visit,setVisit]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [manualType,setManualType]=useState("PROCEDURE"),[manualDesc,setManualDesc]=useState(""),[manualQty,setManualQty]=useState("1"),[manualRate,setManualRate]=useState("");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init),d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d};
 const search=async()=>{if(!query.trim()){setError("Enter HID, patient name or mobile number.");return}setLoading(true);setError("");setMessage("");setProfile(null);try{const d=await run(`/api/billing-search?by=${by}&q=${encodeURIComponent(query.trim())}`);setResults(d.patients||[]);if(!d.patients?.length)setMessage("No patient found for this search.")}catch(e){setError(e instanceof Error?e.message:"Unable to search patients.")}finally{setLoading(false)}};
 const open=async(p:Patient)=>{setLoading(true);setError("");setMessage("");try{const d=await run(`/api/billing-profile?patientId=${p.id}`);setProfile(d);setVisit(d.visits?.[0]?.id||0);setSelected([])}catch(e){setError(e instanceof Error?e.message:"Unable to open billing profile.")}finally{setLoading(false)}};
 const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const selectedLines=useMemo(()=>profile?.lines.filter(l=>selected.includes(l.id)&&l.billStatus!=="PAID")||[],[profile,selected]);
 const total=selectedLines.reduce((s,l)=>s+l.amount,0);
 const grouped=useMemo(()=>{const g:{PAID:Line[];PARTIAL:Line[];UNPAID:Line[]}={PAID:[],PARTIAL:[],UNPAID:[]};for(const l of profile?.lines||[]){if(l.billStatus==="PAID")g.PAID.push(l);else if(l.billStatus==="PARTIAL")g.PARTIAL.push(l);else if(l.billStatus!=="DISCARDED")g.UNPAID.push(l)}return g},[profile]);
 const groups=(lines:Line[])=>{const g:Record<string,Line[]>={};for(const l of lines)(g[l.serviceType]??=[]).push(l);return g};
 const review=async()=>{if(!selectedLines.length){setError("Select at least one Unpaid charge to review.");return}const ids=[...new Set(selectedLines.map(l=>l.visitId))];if(ids.length!==1){setError("Please select charges from one Visit at a time.");return}setLoading(true);setError("");try{const d=await run("/api/billing-selected",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:ids[0],lineIds:selectedLines.map(l=>l.id)})});window.location.href=`/billing/review-selected?billId=${d.bill.id}`}catch(e){setError(e instanceof Error?e.message:"Unable to create selected-charge invoice.")}finally{setLoading(false)}};
 const addManual=async()=>{if(!profile||!visit||!manualDesc.trim()||!Number(manualQty)||Number(manualQty)<=0||manualRate===""||Number(manualRate)<0){setError("Select a Visit and enter service, quantity and valid rate.");return}setLoading(true);setError("");try{let d=await run(`/api/billing?visitId=${visit}`);if(!d.bill)await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:visit})});await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:visit,action:"addLine",serviceType:manualType,description:manualDesc.trim(),quantity:Number(manualQty),unitPrice:Number(manualRate)})});const fresh=await run(`/api/billing-profile?patientId=${profile.patient.id}`);setProfile(fresh);setManualDesc("");setManualQty("1");setManualRate("");setMessage("Manual charge added to the selected Visit.")}catch(e){setError(e instanceof Error?e.message:"Unable to add manual charge.")}finally{setLoading(false)}};
 return <main className="min-h-screen bg-[#fffaf0] p-4 text-[#172b3a] sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-5">
 <header className="rounded-[2rem] border border-[#d7a93d]/40 bg-gradient-to-br from-[#08483d] via-[#0d5b4c] to-[#176f5e] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.28em] text-[#f5d47b]">SAMS · Hospital Finance</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Patient Charges</h1><p className="mt-2 max-w-3xl text-sm text-emerald-50">Search the patient, open the billing profile, verify payment status and create an invoice only from the exact selected Unpaid charges.</p></header>
 <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Step 01</p><h2 className="text-xl font-black text-[#0b2748]">Search Patient</h2><div className="mt-4 flex flex-wrap gap-2">{[["hid","HID / Patient ID"],["name","Patient Name"],["mobile","Mobile Number"]].map(([k,t])=><button key={k} onClick={()=>setBy(k)} className={`rounded-xl px-4 py-2 text-[10px] font-black ${by===k?"bg-[#0d5b4c] text-white":"bg-[#fbf7ed] text-[#0b2748]"}`}>{t}</button>)}</div><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder={by==="hid"?"Enter HID / Patient ID":by==="name"?"Enter patient name":"Enter mobile number"} className="flex-1 rounded-xl border bg-[#fbfcfb] px-4 py-3"/><button onClick={()=>void search()} disabled={loading} className="rounded-xl bg-[#0d5b4c] px-7 py-3 font-black text-white disabled:opacity-50">{loading?"Searching…":"Search Patient"}</button></div>{results.length>0&&<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{results.map(p=><button key={p.id} onClick={()=>void open(p)} className="rounded-2xl border border-[#eadfca] bg-[#fffdf8] p-4 text-left shadow-sm hover:border-[#0d5b4c]"><div className="flex justify-between gap-3"><div><p className="font-black text-[#0b2748]">{p.name}</p><p className="mt-1 text-[10px] font-black text-[#0d5b4c]">{p.patientId}</p></div><span className="rounded-full bg-[#fff7dd] px-2 py-1 text-[9px] font-black">{p.visits.length} visit{p.visits.length===1?"":"s"}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><span className="rounded-lg bg-white p-2"><b>Age/Gender</b><br/>{p.age??"—"} · {p.gender||"—"}</span><span className="rounded-lg bg-white p-2"><b>Mobile</b><br/>{p.phone||"—"}</span></div><div className="mt-3 flex justify-between border-t pt-3 text-xs"><span className="text-slate-500">Outstanding</span><b className={p.outstanding>0?"text-red-600":"text-emerald-700"}>{money(p.outstanding)}</b></div></button>)}</div>}</section>
 {profile&&<><section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Step 02</p><h2 className="text-2xl font-black text-[#0b2748]">Patient Billing Profile</h2><p className="mt-1 text-xs text-slate-500">Every charge has one payment status: Paid, Partially Unpaid or Unpaid.</p></div><div className="rounded-2xl bg-[#edf5ee] px-5 py-3 text-right"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Outstanding Balance</p><p className="text-xl font-black text-[#0b2748]">{money(profile.outstanding)}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info t="Patient" v={profile.patient.name}/><Info t="HID" v={profile.patient.patientId}/><Info t="Age / Gender" v={`${profile.patient.age??"—"} · ${profile.patient.gender||"—"}`}/><Info t="Mobile" v={profile.patient.phone||"—"}/></div></section>
 <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Visit Context</p><p className="mt-1 text-xs text-slate-500">Select the Visit used for any manual charge.</p></div><select value={visit} onChange={e=>setVisit(Number(e.target.value))} className="rounded-xl border bg-white px-3 py-2 text-xs font-black">{profile.visits.map(v=><option key={v.id} value={v.id}>Visit #{v.id} · {new Date(v.createdAt).toLocaleDateString()} · {v.doctor||"Doctor not recorded"}</option>)}</select></div></section>
 <section className="grid gap-4 lg:grid-cols-3">{buckets.map(b=>{const lines=grouped[b.key];const amount=lines.reduce((s,l)=>s+l.amount,0);return <div key={b.key} className={`rounded-[1.5rem] border ${b.border} bg-white p-5 shadow-sm`}><div className="flex items-start justify-between gap-3"><div><span className={`inline-flex rounded-full px-3 py-1 text-[10px] font-black ${b.badge}`}>{b.title}</span><h3 className="mt-3 text-xl font-black text-[#0b2748]">{money(amount)}</h3><p className="mt-1 text-[10px] text-slate-500">{b.sub}</p></div><span className="rounded-full bg-[#fbf7ed] px-2 py-1 text-[9px] font-black">{lines.length} charge{lines.length===1?"":"s"}</span></div>{lines.length===0?<div className="mt-5 rounded-xl border border-dashed p-5 text-center text-xs text-slate-400">No charges in this status.</div>:<div className="mt-5 space-y-3">{Object.entries(groups(lines)).map(([type,items])=><div key={type}><p className="mb-2 text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">{service(type)}</p><div className="space-y-2">{items.map(l=><label key={l.id} className={`flex items-center gap-3 rounded-xl border p-3 ${selected.includes(l.id)?"border-[#0d5b4c] bg-[#edf5ee]":"border-[#eee5d4] bg-[#fffdf8]"}`}><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>toggle(l.id)} disabled={l.billStatus==="PAID"||b.key!=="UNPAID"} className="h-4 w-4 accent-[#0d5b4c] disabled:opacity-30"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-black text-[#0b2748]">{l.description}</p><p className="mt-1 text-[9px] text-slate-400">Visit #{l.visitId} · {new Date(l.visitDate).toLocaleDateString()} · {source(l.sourceType)}</p><p className="text-[9px] text-slate-400">{status(l.billStatus)}</p></div><b className="text-xs">{money(l.amount)}</b></label>)}</div></div>)}</div>}</div>})}</section>
 <section className="sticky bottom-3 z-10 rounded-[1.5rem] border border-[#eadfca] bg-white/95 p-4 shadow-xl backdrop-blur"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Selected Unpaid Charges</p><p className="text-xl font-black text-[#0b2748]">{selectedLines.length} charge{selectedLines.length===1?"":"s"} · {money(total)}</p></div><button onClick={()=>void review()} disabled={!selectedLines.length||loading} className="rounded-xl bg-[#0d5b4c] px-6 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Review Selected Charges →</button></div></section>
 <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Manual Charge</p><h3 className="text-lg font-black text-[#0b2748]">Add Charge to Selected Visit</h3><div className="mt-3 grid gap-3 lg:grid-cols-[180px_1fr_100px_130px_auto]"><select value={manualType} onChange={e=>setManualType(e.target.value)} className="rounded-xl border px-3 py-3 font-bold"><option>PROCEDURE</option><option>IPD</option><option>INVESTIGATION</option><option>ELECTRODIAGNOSIS</option><option>PHYSIOTHERAPY</option><option>PHARMACY</option><option>OTHER</option></select><input value={manualDesc} onChange={e=>setManualDesc(e.target.value)} placeholder="Service / procedure description" className="rounded-xl border px-3 py-3"/><input value={manualQty} onChange={e=>setManualQty(e.target.value)} type="number" min="0.01" step="0.01" className="rounded-xl border px-3 py-3"/><input value={manualRate} onChange={e=>setManualRate(e.target.value)} type="number" min="0" step="0.01" placeholder="Rate ₹" className="rounded-xl border px-3 py-3"/><button onClick={()=>void addManual()} disabled={loading} className="rounded-xl bg-[#0d5b4c] px-5 py-3 font-black text-white disabled:opacity-40">＋ Add Charge</button></div></section></>}
 {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
 </div></main>}
function Info({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-[#eadfca] bg-[#fffdf8] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t}</p><p className="mt-1 font-black text-[#0b2748]">{v}</p></div>}
