"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

type Visit={id:number;tokenNumber:number;visitType:string;status:string;department:string|null;createdAt:string};
type Line={id:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null;sourceId:number|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;discount:number;netAmount:number;paymentStatus:string;paymentMethod:string|null;paidAmount:number;balanceAmount:number};
type Data={visit:Visit;patient:{id:number;patientId:string;name:string;phone:string|null};lineItems:Line[];totals:{subtotal:number};bill:Bill|null;consultationFee:number};
const TYPES=["PROCEDURE","ELECTRODIAGNOSIS","PHYSIOTHERAPY","PHARMACY","OTHER"];
const CATEGORY:Record<string,{title:string;icon:string;desc:string}>={CONSULTATION:{title:"Consultation Charges",icon:"◉",desc:"Doctor consultation charges"},INVESTIGATION:{title:"Investigation Charges",icon:"⌁",desc:"Lab, radiology and diagnostic charges"},PROCEDURE:{title:"Procedure Charges",icon:"◇",desc:"Procedure / surgery charges"},IPD:{title:"IPD Charges",icon:"▣",desc:"Admission and inpatient charges"},ELECTRODIAGNOSIS:{title:"Other Services Charges",icon:"⌁",desc:"Electrodiagnosis and related services"},PHYSIOTHERAPY:{title:"Other Services Charges",icon:"＋",desc:"Physiotherapy / rehabilitation services"},PHARMACY:{title:"Other Services Charges",icon:"✚",desc:"Medicines and pharmacy charges"},OTHER:{title:"Other Services Charges",icon:"•",desc:"Other billable services"}};
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",IPD:"IPD",OTHER:"Other Service"}[x]||x); const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
export default function PatientChargesPage(){
 const router=useRouter(),search=useSearchParams(); const [patientId,setPatientId]=useState(search.get("patientId")||""),[visits,setVisits]=useState<Visit[]>([]),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[type,setType]=useState("PROCEDURE"),[desc,setDesc]=useState(""),[qty,setQty]=useState("1"),[rate,setRate]=useState(""),[discount,setDiscount]=useState("");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init),d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d};
 const load=async(id:number)=>{setLoading(true);setError("");try{let d:Data=await run(`/api/billing?visitId=${id}`);let created=false;if(!d.bill){await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:id})});d=await run(`/api/billing?visitId=${id}`);created=true}if(created&&!d.bill?.paidAmount&&!d.lineItems.some(l=>l.serviceType==="CONSULTATION"&&l.sourceType==="OPD_VISIT")){await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:id,action:"addConsultation"})});d=await run(`/api/billing?visitId=${id}`)}setData(d);setPatientId(d.patient.patientId)}catch(e){setError(e instanceof Error?e.message:"Unable to load patient charges")}finally{setLoading(false)}};
 const find=async()=>{if(!patientId.trim()){setError("Enter Patient ID first.");return}setLoading(true);setError("");setData(null);try{const d=await run(`/api/billing?patientId=${encodeURIComponent(patientId.trim())}`);setVisits(d.visits||[]);if(!d.visits?.length)setMessage("Patient found, but no OPD Visit is available.")}catch(e){setError(e instanceof Error?e.message:"Unable to find patient")}finally{setLoading(false)}};
 useEffect(()=>{const id=Number(search.get("visitId")||0);if(id>0)void load(id)},[]);
 const editable=!!data?.bill&&!data.bill.paidAmount&&data.bill.paymentStatus!=="PAID"&&data.bill.paymentStatus!=="DISCARDED"; const subtotal=useMemo(()=>data?.lineItems.reduce((a,l)=>a+l.amount,0)||0,[data]),disc=data?.bill?.discount||0,net=data?.bill?.netAmount??Math.max(0,subtotal-disc),ready=!!desc.trim()&&Number(qty)>0&&rate!==""&&Number(rate)>=0;
 const groups=useMemo(()=>{const m=new Map<string,Line[]>();for(const l of data?.lineItems||[]){const k=l.serviceType||"OTHER";(m.get(k)||m.set(k,[]).get(k)!).push(l)}return [...m].map(([key,lines])=>({key,lines,total:lines.reduce((s,l)=>s+l.amount,0)}))},[data]);
 const add=async()=>{if(!data||!editable||!ready)return;setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:data.visit.id,action:"addLine",serviceType:type,description:desc.trim(),quantity:Number(qty),unitPrice:Number(rate)})});setDesc("");setQty("1");setRate("");await load(data.visit.id);setMessage("Charge added.")}catch(e){setError(e instanceof Error?e.message:"Unable to add charge");setLoading(false)}};
 const remove=async(id:number)=>{if(!data||!editable)return;setLoading(true);setError("");try{await run(`/api/billing?lineId=${id}`,{method:"DELETE"});await load(data.visit.id);setMessage("Charge removed from this bill only.")}catch(e){setError(e instanceof Error?e.message:"Unable to remove charge");setLoading(false)}};
 const applyDiscount=async()=>{if(!data?.bill||!editable)return;const d=Number(discount);if(!Number.isFinite(d)||d<0||d>subtotal){setError("Enter a valid discount within the subtotal.");return}setLoading(true);try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discount",billId:data.bill.id,discount:d})});await load(data.visit.id);setMessage("Discount updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to update discount");setLoading(false)}};
 const process=async()=>{if(!data?.bill)return;setLoading(true);try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:data.visit.id,action:"processBill"})});router.push(`/billing?visitId=${data.visit.id}`)}catch(e){setError(e instanceof Error?e.message:"Unable to process bill");setLoading(false)}};
 return <main className="min-h-screen bg-[#fffaf0] p-4 text-[#172b3a] sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-5">
  <header className="rounded-[2rem] border border-[#d7a93d]/40 bg-gradient-to-br from-[#08483d] via-[#0d5b4c] to-[#176f5e] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.28em] text-[#f5d47b]">SAMS · Patient Charges</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Patient Charges</h1><p className="mt-2 text-sm text-emerald-50">Only charge categories containing actual billable items are displayed.</p></header>
  <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Step 01</p><h2 className="text-xl font-black text-[#0b2748]">Find Patient & Select OPD Visit</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={patientId} onChange={e=>setPatientId(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void find()} placeholder="Enter Patient ID" className="flex-1 rounded-xl border bg-[#fbfcfb] px-4 py-3"/><button onClick={()=>void find()} disabled={loading} className="rounded-xl bg-[#0d5b4c] px-6 py-3 font-black text-white disabled:opacity-50">{loading?"Loading…":"Find Patient"}</button></div>{visits.length>0&&<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visits.map(v=><button key={v.id} onClick={()=>void load(v.id)} className={`rounded-2xl border p-4 text-left hover:border-[#0d5b4c] hover:shadow-md ${data?.visit.id===v.id?"border-[#0d5b4c] bg-[#edf5ee]":"border-[#eadfca] bg-white"}`}><div className="flex justify-between"><b>OPD Visit #{v.id}</b><span className="rounded-full bg-[#fff7dd] px-2 py-1 text-[9px] font-black">Token #{v.tokenNumber}</span></div><p className="mt-2 text-xs text-slate-500">{v.visitType} · {v.department||"General"}</p></button>)}</div>}</section>
  {data&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info t="Patient" v={data.patient.name}/><Info t="Patient ID" v={data.patient.patientId}/><Info t="OPD Visit" v={`#${data.visit.id} · Token #${data.visit.tokenNumber}`}/><Info t="Bill" v={data.bill?.billNumber||"Not created"}/></section>
   <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Step 02</p><h2 className="text-xl font-black text-[#0b2748]">Patient Billing Profile</h2><p className="mt-1 text-xs text-slate-500">Empty categories are hidden automatically.</p>{groups.length?<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(g=>{const c=CATEGORY[g.key]||CATEGORY.OTHER;const title=["ELECTRODIAGNOSIS","PHYSIOTHERAPY","PHARMACY","OTHER"].includes(g.key)?"Other Services Charges":c.title;return <div key={g.key} className="rounded-2xl border border-[#eadfca] bg-[#fffdf8] p-5 shadow-sm"><div className="flex justify-between"><div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf5ee] text-lg font-black text-[#0d5b4c]">{c.icon}</span><h3 className="mt-3 font-black text-[#0b2748]">{title}</h3><p className="mt-1 text-[10px] text-slate-500">{c.desc}</p></div><span className="rounded-full bg-[#fff7dd] px-2 py-1 text-[9px] font-black text-[#8a6713]">{g.lines.length} item{g.lines.length>1?"s":""}</span></div><p className="mt-4 text-2xl font-black text-[#0d5b4c]">{money(g.total)}</p><div className="mt-3 space-y-2">{g.lines.map(l=><div key={l.id} className="flex items-center justify-between gap-3 rounded-xl bg-white p-3"><div className="min-w-0"><p className="truncate text-xs font-black text-[#0b2748]">{l.description}</p><p className="text-[9px] text-slate-400">{label(l.serviceType)} · {l.sourceType==="INVESTIGATION_ORDER"?"Investigation Order":l.sourceType==="OPD_VISIT"?"OPD Visit":l.sourceType==="PRESCRIPTION"?"Prescription":"Manual"}</p></div><div className="text-right"><p className="text-xs font-black">{money(l.amount)}</p>{editable&&<button onClick={()=>void remove(l.id)} className="text-[9px] font-black text-red-600">Remove</button>}</div></div>)}</div></div>})}</div>:<div className="mt-5 rounded-2xl border border-dashed border-[#d7c8a8] bg-[#fffdf8] p-10 text-center"><h3 className="font-black text-[#0b2748]">No billable charges yet</h3><p className="mt-1 text-sm text-slate-500">A category will appear only when an actual charge exists.</p></div>}
    {editable&&<div className="mt-5 rounded-2xl border bg-[#fbf7ed] p-4"><p className="mb-3 text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Add manual charge</p><div className="grid gap-3 lg:grid-cols-[180px_1fr_100px_130px_auto]"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border bg-white px-3 py-3 font-bold">{TYPES.map(t=><option key={t}>{t}</option>)}</select><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Service description" className="rounded-xl border bg-white px-3 py-3"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.01" step="0.01" className="rounded-xl border bg-white px-3 py-3"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" min="0" step="0.01" placeholder="Rate ₹" className="rounded-xl border bg-white px-3 py-3"/><button onClick={()=>void add()} disabled={loading||!ready} className="rounded-xl bg-[#0d5b4c] px-5 py-3 font-black text-white disabled:opacity-40">＋ Add Charge</button></div></div>}
   </section>
   <section className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl bg-[#edf5ee] p-4 text-xs"><p className="font-black uppercase tracking-widest text-[#0d5b4c]">Charge integrity</p><p className="mt-2">✓ Investigation lines remain linked to their Investigation Order.</p><p>✓ Removing a line affects this bill only.</p><p>✓ Paid bills are locked.</p></div><div className="rounded-2xl border bg-white p-5"><div className="flex justify-between text-sm"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="mt-3 flex justify-between text-sm"><span>Discount</span><span className="flex gap-2"><input value={discount} onChange={e=>setDiscount(e.target.value)} disabled={!editable} placeholder={money(disc)} className="w-28 rounded-lg border px-2 py-1.5 text-right"/><button onClick={()=>void applyDiscount()} disabled={loading||!editable} className="rounded-lg bg-[#d7a93d] px-3 py-1.5 text-xs font-black text-white disabled:opacity-40">Apply</button></span></div><div className="mt-4 flex justify-between border-t pt-3 text-xl font-black text-[#0b2748]"><span>Net Payable</span><span>{money(net)}</span></div></div></section>
   <section className="rounded-[1.5rem] border border-[#eadfca] bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-[#0d5b4c]">Step 03</p><h2 className="text-xl font-black text-[#0b2748]">Confirm & Continue to Payment</h2><div className="mt-4 flex flex-wrap gap-2"><Link href={`/billing?visitId=${data.visit.id}`} className="rounded-xl border px-5 py-3 text-xs font-black">Open Bill</Link><button onClick={()=>void process()} disabled={loading||!data.bill||data.bill.paymentStatus==="PAID"||data.bill.paymentStatus==="DISCARDED"} className="rounded-xl bg-[#0d5b4c] px-6 py-3 text-xs font-black text-white disabled:opacity-40">✓ Confirm Charges & Continue</button></div></section></>}
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
 </div></main>;
}
function Info({t,v}:{t:string;v:string}){return <div className="rounded-2xl border border-[#eadfca] bg-white p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t}</p><p className="mt-1 font-black text-[#0b2748]">{v}</p></div>}
