"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";

type Patient = { id?: string; patientId?: string; firstName?: string; lastName?: string; name?: string; age?: number | string; gender?: string; phone?: string; mobile?: string };
type Department = { id: number; name: string };
type Doctor = { id: number; name?: string; firstName?: string; lastName?: string };
type Visit = { id: number; department?: string | null; doctorId?: number | null; tokenNumber?: number; visitType?: string; status?: string };
type Medicine = { id: number; name: string; dose: string; frequency: string; food: string; duration: string };

type Vital = { label: string; value: string; unit: string };
const units: Record<string,string> = { "Blood Pressure":"mmHg", Pulse:"bpm", "Respiratory Rate":"/min", Temperature:"°F", "SpO₂":"%", Weight:"kg", Height:"cm", BMI:"kg/m²" };
const investigations = ["CBC — Complete Blood Count","ESR — Erythrocyte Sedimentation Rate","CRP — C-Reactive Protein","HbA1c — Glycated Hemoglobin","Blood Sugar — Fasting","Blood Sugar — PP","Lipid Profile","Liver Function Test","Kidney Function Test","Urine Routine & Microscopy","Vitamin B12","Vitamin D","TSH","X-Ray","Ultrasound","MRI","CT Scan","NCV / EMG","Nerve Conduction Study","Electrodiagnostic Study"];
const links = [{label:"Dashboard",path:"/dashboard",icon:"⌂"},{label:"Patient Directory",path:"/patients",icon:"P"},{label:"Appointments",path:"/appointments",icon:"A"},{label:"OPD",path:"/opd",icon:"O"},{label:"Billing & Payments",path:"/billing",icon:"₹"}];

export default function ConsultationPage() {
  const params = useParams<{id:string}>(); const search = useSearchParams(); const router = useRouter(); const patientId = String(params.id); const opdVisitId = search.get("opdVisitId");
  const [patient,setPatient]=useState<Patient|null>(null); const [visit,setVisit]=useState<Visit|null>(null); const [department,setDepartment]=useState("—"); const [doctor,setDoctor]=useState("—"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [chiefComplaint,setChiefComplaint]=useState(""); const [diagnosis,setDiagnosis]=useState(""); const [clinicalFindings,setClinicalFindings]=useState(""); const [generalAdvice,setGeneralAdvice]=useState(""); const [treatmentPlan,setTreatmentPlan]=useState(""); const [followUpDate,setFollowUpDate]=useState("");
  const [investigationInput,setInvestigationInput]=useState(""); const [selectedInvestigations,setSelectedInvestigations]=useState<string[]>([]);
  const [vitals,setVitals]=useState<Vital[]>(Object.keys(units).map(label=>({label,value:"",unit:units[label]})));
  const [medicines,setMedicines]=useState<Medicine[]>([{id:1,name:"",dose:"",frequency:"",food:"",duration:""}]); const [saving,setSaving]=useState(false);

  useEffect(()=>{(async()=>{try{const p=await fetch(`/api/patients/${patientId}`);if(!p.ok)throw new Error("Unable to load patient.");setPatient(await p.json());if(!opdVisitId)return;const v=await fetch(`/api/opd/${opdVisitId}`);if(!v.ok)throw new Error("Unable to load OPD visit.");const vd:Visit=await v.json();setVisit(vd);fetch(`/api/opd/${opdVisitId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"IN_CONSULTATION"})}).catch(()=>undefined);const [dr,dc]=await Promise.all([fetch("/api/departments"),fetch(vd.department?`/api/doctors?departmentId=${vd.department}`:"/api/doctors")]);const deps:Department[]=dr.ok?await dr.json():[];const docs:Doctor[]=dc.ok?await dc.json():[];setDepartment(deps.find(x=>String(x.id)===String(vd.department))?.name||vd.department||"—");const d=docs.find(x=>x.id===Number(vd.doctorId));setDoctor(d?.name||`${d?.firstName||""} ${d?.lastName||""}`.trim()||"—");}catch(e){setError(e instanceof Error?e.message:"Unable to load consultation.");}finally{setLoading(false)}})()},[patientId,opdVisitId]);

  const suggestions=useMemo(()=>{const q=investigationInput.trim().toLowerCase();return q?investigations.filter(x=>x.toLowerCase().includes(q)&&!selectedInvestigations.includes(x)).slice(0,8):[]},[investigationInput,selectedInvestigations]);
  const patientName=patient?.name||`${patient?.firstName||""} ${patient?.lastName||""}`.trim()||"Patient";
  function updateVital(i:number,value:string){setVitals(v=>v.map((x,n)=>n===i?{...x,value}:x))}; function updateMedicine(id:number,key:keyof Medicine,value:string){setMedicines(m=>m.map(x=>x.id===id?{...x,[key]:value}:x))};
  async function save(){setSaving(true);setError("");try{const response=await fetch("/api/patients/encounters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId,chiefComplaint,diagnosis,clinicalNotes:`${clinicalFindings}\nVitals: ${vitals.filter(x=>x.value).map(x=>`${x.label}: ${x.value} ${x.unit}`).join(" | ")}\nInvestigations: ${selectedInvestigations.join(", ")}\nAdvice: ${generalAdvice}`,treatmentPlan,followUpDate:followUpDate||null,opdVisitId:opdVisitId?Number(opdVisitId):null})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Unable to save consultation.");if(opdVisitId)await fetch(`/api/opd/${opdVisitId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"COMPLETED"})});router.push(`/patients/profile/${patientId}/opd-slip`)}catch(e){setError(e instanceof Error?e.message:"Unable to save consultation.");setSaving(false)}}
  if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#f4f7fb]"><div className="rounded-2xl bg-white p-8 text-center shadow-xl"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#082b61] text-xl font-black text-white">S</div><p className="mt-3 text-sm font-bold text-slate-500">Loading consultation…</p></div></main>;
  return <main className="consultation-screen min-h-screen bg-[#eef2f7] text-slate-900"><header className="no-print sticky top-0 z-40 border-b border-white/10 bg-[#071f46] text-white shadow-lg"><div className="flex min-h-[82px] items-center justify-between gap-4 px-4 py-4 sm:px-7"><div className="flex items-center gap-3"><button onClick={()=>router.back()} className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/15 bg-white/10 text-xl font-black">←</button><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-[#d4af37]/70 bg-white/5 text-2xl font-black text-[#f1d27a]">S</div><div><p className="text-[9px] font-black uppercase tracking-[.3em] text-[#f1d27a]">SAMS · Clinical Consultation</p><h1 className="text-2xl font-black sm:text-3xl" style={{fontFamily:"'Palatino Linotype','Book Antiqua',Georgia,serif"}}>Consultation</h1></div></div><div className="hidden text-right sm:block"><p className="text-[9px] uppercase tracking-widest text-blue-200">Patient</p><p className="text-sm font-black">{patientName} · {patient?.patientId||patientId}</p></div></div></header>
    <div className="mx-auto flex max-w-[1600px] gap-5 px-4 py-5 sm:px-6 lg:px-8"><aside className="no-print hidden w-[225px] shrink-0 rounded-3xl border border-slate-200 bg-white p-3 shadow-lg lg:block lg:sticky lg:top-[102px] lg:h-fit"><p className="px-3 pb-3 pt-2 text-[9px] font-black uppercase tracking-[.22em] text-slate-400">Clinical Operations</p>{links.map(x=><button key={x.label} onClick={()=>router.push(x.path)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-xs font-black ${x.label==="OPD"?"bg-[#082b61] text-white":"text-slate-600 hover:bg-blue-50 hover:text-[#0b63ce]"}`}><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-50 text-[#082b61]">{x.icon}</span>{x.label}</button>)}</aside>
      <section className="consultation-paper min-w-0 flex-1 overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-xl"><div className="border-b border-slate-200 px-6 py-6 sm:px-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#0b63ce]">Clinical Record</p><h2 className="mt-1 text-3xl font-black text-[#082b61]" style={{fontFamily:"'Palatino Linotype','Book Antiqua',Georgia,serif"}}>Consultation Note</h2></div><div className="grid grid-cols-3 gap-2 text-center text-[9px] font-black uppercase"><div className="rounded-xl bg-blue-50 px-3 py-2 text-[#0b63ce]">Visit<br/><span className="text-xs">#{visit?.id||"—"}</span></div><div className="rounded-xl bg-blue-50 px-3 py-2 text-[#0b63ce]">Department<br/><span className="text-xs normal-case">{department}</span></div><div className="rounded-xl bg-blue-50 px-3 py-2 text-[#0b63ce]">Consultant<br/><span className="text-xs normal-case">{doctor}</span></div></div></div></div>
        <div className="space-y-6 p-6 sm:p-9"><section className="rounded-2xl border border-slate-200 bg-[#fbfcfe] p-5"><p className="mb-4 text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Patient Vitals</p><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{vitals.map((v,i)=><label key={v.label} className="rounded-xl border border-slate-200 bg-white p-3"><span className="block text-[10px] font-black text-slate-500">{v.label}</span><div className="mt-2 flex items-center gap-2"><input value={v.value} onChange={e=>updateVital(i,e.target.value)} className="h-9 min-w-0 flex-1 rounded-lg border border-slate-200 px-2 text-sm font-bold outline-none focus:border-blue-500"/><span className="text-[10px] font-black text-[#0b63ce]">{v.unit}</span></div></label>)}</div></section>
        <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Chief Complaint</p><textarea value={chiefComplaint} onChange={e=>setChiefComplaint(e.target.value)} rows={4} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Reason for consultation"/></div><div className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Clinical Findings</p><textarea value={clinicalFindings} onChange={e=>setClinicalFindings(e.target.value)} rows={4} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="History and examination findings"/></div></section>
        <section className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Investigation</p><div className="relative mt-3"><input value={investigationInput} onChange={e=>setInvestigationInput(e.target.value)} className="w-full rounded-xl border border-slate-200 p-3 text-sm font-semibold outline-none focus:border-blue-500" placeholder="Type investigation name or initials…"/>{suggestions.length>0&&<div className="absolute left-0 right-0 top-full z-20 mt-1 overflow-hidden rounded-xl border bg-white shadow-xl">{suggestions.map(x=><button type="button" key={x} onClick={()=>{setSelectedInvestigations(v=>[...v,x]);setInvestigationInput("")}} className="block w-full border-b border-slate-100 px-4 py-3 text-left text-sm font-semibold hover:bg-blue-50">{x}</button>)}</div>}</div><div className="mt-3 flex flex-wrap gap-2">{selectedInvestigations.map(x=><button type="button" key={x} onClick={()=>setSelectedInvestigations(v=>v.filter(i=>i!==x))} className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-[#0b63ce]">{x} ×</button>)}</div></section>
        <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Diagnosis</p><textarea value={diagnosis} onChange={e=>setDiagnosis(e.target.value)} rows={4} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Diagnosis / differential diagnosis"/></div><div className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Treatment / Plan</p><textarea value={treatmentPlan} onChange={e=>setTreatmentPlan(e.target.value)} rows={4} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" placeholder="Treatment and plan"/></div></section>
        <section className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">Medicines / Prescription</p><button type="button" onClick={()=>setMedicines(v=>[...v,{id:Date.now(),name:"",dose:"",frequency:"",food:"",duration:""}])} className="no-print rounded-lg bg-[#082b61] px-3 py-2 text-xs font-black text-white">+ Add Medicine</button></div><div className="mt-3 space-y-3">{medicines.map((m,i)=><div key={m.id} className="grid gap-2 rounded-xl bg-slate-50 p-3 sm:grid-cols-5"><input value={m.name} onChange={e=>updateMedicine(m.id,"name",e.target.value)} placeholder={`Medicine ${i+1}`} className="rounded-lg border p-2 text-xs"/><input value={m.dose} onChange={e=>updateMedicine(m.id,"dose",e.target.value)} placeholder="Dose" className="rounded-lg border p-2 text-xs"/><input value={m.frequency} onChange={e=>updateMedicine(m.id,"frequency",e.target.value)} placeholder="Frequency" className="rounded-lg border p-2 text-xs"/><input value={m.food} onChange={e=>updateMedicine(m.id,"food",e.target.value)} placeholder="Food" className="rounded-lg border p-2 text-xs"/><input value={m.duration} onChange={e=>updateMedicine(m.id,"duration",e.target.value)} placeholder="Duration" className="rounded-lg border p-2 text-xs"/></div>)}</div></section>
        <section className="rounded-2xl border border-slate-200 p-5"><p className="text-[9px] font-black uppercase tracking-[.22em] text-[#0b63ce]">General Advice & Follow-up</p><textarea value={generalAdvice} onChange={e=>setGeneralAdvice(e.target.value)} rows={3} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Advice / precautions"/><input type="date" value={followUpDate} onChange={e=>setFollowUpDate(e.target.value)} className="mt-3 rounded-xl border border-slate-200 p-3 text-sm"/></section>
        {error&&<div className="no-print rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
        <div className="print-signature hidden border-t border-slate-300 pt-10 sm:flex sm:justify-end"><div className="w-56 text-center"><div className="h-10 border-b border-slate-400"/><p className="mt-2 text-sm font-black text-[#082b61]">Consultant</p><p className="text-xs font-semibold text-slate-500">{doctor}</p></div></div>
        <div className="no-print flex justify-end gap-3 border-t pt-5"><button onClick={()=>window.print()} className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-black text-slate-600">Print A4</button><button onClick={save} disabled={saving} className="rounded-xl bg-[#0b63ce] px-6 py-3 text-sm font-black text-white disabled:opacity-60">{saving?"Saving…":"Save Consultation"}</button></div></div></section></div>
    <style jsx global>{`@media print{@page{size:A4;margin:12mm}html,body{background:#fff!important}.no-print{display:none!important}.consultation-screen{background:#fff!important;min-height:auto!important}.consultation-paper{width:186mm!important;min-height:273mm!important;margin:0!important;border:0!important;border-radius:0!important;box-shadow:none!important}.consultation-paper>div{padding:0!important}.print-signature{display:flex!important;break-inside:avoid}section{break-inside:avoid}}`}</style></main>;
}
