"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type Order={id:number;investigation:string;price:number;netAmount:number;paymentStatus:string;status:string;specimen:string|null;accessionNumber:string|null;barcodeValue:string|null;sampleCollectedAt:string|null;sampleCollectedBy:string|null;processingStartedAt:string|null;processingCompletedAt:string|null;reportText:string|null;resultData:string|null;abnormalFlag:boolean;criticalFlag:boolean;verificationStatus:string;verifiedBy:string|null;verifiedAt:string|null;publishedAt:string|null;master:{code:string;specimen:string|null;unit:string|null;referenceRange:string|null;criticalValue:string|null}|null;opdVisit:{id:number;tokenNumber:number;patient:{patientId:string;firstName:string;lastName:string;gender:string|null}};workflow:{paymentStatus:string;outstandingAmount:number;samplingEligible:boolean}};
const stages=["ORDERED","APPROVED_FOR_SAMPLING","ACCEPTED","SAMPLE_COLLECTED","PROCESSING","COMPLETED","VERIFIED","PUBLISHED"];
export default function InvestigationRoomPage(){const[orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[loading,setLoading]=useState(true),[busy,setBusy]=useState<number|null>(null),[edit,setEdit]=useState<number|null>(null),[draft,setDraft]=useState("");
 async function load(){setLoading(true);const p=new URLSearchParams();if(q)p.set("q",q);if(status!=="ALL")p.set("status",status);const r=await fetch(`/api/investigation-room?${p}`,{cache:"no-store"});const d=await r.json();setOrders(Array.isArray(d)?d:[]);setLoading(false)}
 useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[q,status]);
 async function advance(o:Order,next:string,extra:any={}){setBusy(o.id);const r=await fetch("/api/investigation-room",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:o.id,status:next,...extra})});const d=await r.json();setBusy(null);if(!r.ok){alert(d?.error||"Unable to update order");return}setEdit(null);setDraft("");await load()}
 return <main className="min-h-screen bg-[#07111c] text-slate-100 px-4 py-5 sm:px-7"><div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-center justify-between gap-4 rounded-[1.7rem] border border-white/10 bg-[#0d1b2a]/95 p-5 shadow-2xl"><div className="flex items-center gap-3"><Link href="/investigations" className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-black">← Back</Link><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#d6a443]">SAMS · Laboratory</p><h1 className="text-xl font-black">Investigation Room</h1></div></div><button onClick={()=>void load()} className="rounded-xl bg-[#d6a443] px-4 py-2.5 text-xs font-black text-[#07111c]">Refresh</button></header>
 <section className="mt-5 rounded-[2rem] border border-[#d6a443]/25 bg-gradient-to-br from-[#0c2740] to-[#081522] p-7 shadow-2xl"><p className="text-[9px] font-black uppercase tracking-[.28em] text-[#d6a443]">Laboratory Command Centre</p><h2 className="mt-2 text-3xl font-black">Order → Sample → Process → Result → Verify → Publish</h2><p className="mt-2 text-sm text-slate-400">Routine laboratory reports are generated from verified results. External PDF upload remains a fallback, not the primary workflow.</p></section>
 <section className="mt-5 flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#0d1b2a] p-4 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient ID, name or investigation…" className="flex-1 rounded-xl border border-white/10 bg-[#07111c] px-4 py-3 text-sm outline-none"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-[#07111c] px-4 py-3 text-sm">{["ALL",...stages,"CANCELLED"].map(s=><option key={s}>{s}</option>)}</select></section>
 <section className="mt-5 space-y-4">{loading?<div className="rounded-2xl bg-[#0d1b2a] p-8">Loading…</div>:orders.length===0?<div className="rounded-2xl bg-[#0d1b2a] p-8 text-center text-slate-400">No investigation orders found.</div>:orders.map(o=>{const patient=`${o.opdVisit.patient.firstName} ${o.opdVisit.patient.lastName}`.trim();const idx=stages.indexOf(o.status);const paid=o.workflow.outstandingAmount<=0||o.workflow.paymentStatus==="PAID";return <article key={o.id} className="rounded-[1.8rem] border border-white/10 bg-[#0d1b2a] p-5 shadow-xl sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#d6a443]/10 px-3 py-1 text-[9px] font-black text-[#f4d58c]">LAB #{o.id}</span><span className="rounded-full bg-white/5 px-3 py-1 text-[9px] font-black">{o.status.replaceAll("_"," ")}</span><span className={`rounded-full px-3 py-1 text-[9px] font-black ${paid?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-300"}`}>{paid?"PAID":"PENDING"}</span></div><h3 className="mt-3 text-xl font-black">{o.investigation}</h3><p className="text-xs text-slate-400">{patient} · {o.opdVisit.patient.patientId} · Visit #{o.opdVisit.id} · Token {o.opdVisit.tokenNumber}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div><p className="label">Specimen</p><p>{o.specimen||o.master?.specimen||"—"}</p></div><div><p className="label">Accession</p><p className="font-mono text-[#f4d58c]">{o.accessionNumber||"Pending"}</p></div><div><p className="label">Reference</p><p>{o.master?.referenceRange||"—"}</p></div></div><div className="mt-5 flex items-center gap-1 overflow-hidden">{stages.map((s,i)=><div key={s} className="flex min-w-0 flex-1 items-center gap-1"><div className={`h-2 w-2 shrink-0 rounded-full ${i<=idx?"bg-[#d6a443]":"bg-white/15"}`}/><span className={`hidden truncate text-[8px] font-black uppercase xl:block ${i<=idx?"text-[#d6a443]":"text-slate-600"}`}>{s.replaceAll("_"," ")}</span>{i<stages.length-1&&<div className={`h-px flex-1 ${i<idx?"bg-[#d6a443]/60":"bg-white/10"}`}/>}</div>)}</div></div><div className="flex flex-wrap gap-2 xl:max-w-[430px] xl:justify-end xl:self-start">
 {o.status==="ORDERED"&&!paid&&<button disabled={busy===o.id} onClick={()=>advance(o,"APPROVED_FOR_SAMPLING")} className="action amber">Approve Sampling</button>}
 {(o.status==="ORDERED"&&paid||o.status==="APPROVED_FOR_SAMPLING")&&<button disabled={busy===o.id} onClick={()=>advance(o,"ACCEPTED")} className="action blue">Accept Order</button>}
 {o.status==="ACCEPTED"&&<button disabled={busy===o.id} onClick={()=>advance(o,"SAMPLE_COLLECTED",{specimen:o.specimen||o.master?.specimen||"Sample",sampleCollectedBy:"Laboratory"})} className="action blue">Collect Sample</button>}
 {o.status==="SAMPLE_COLLECTED"&&<button disabled={busy===o.id} onClick={()=>advance(o,"PROCESSING")} className="action blue">Start Processing</button>}
 {!["VERIFIED","PUBLISHED","CANCELLED"].includes(o.status)&&<button onClick={()=>{setEdit(o.id);setDraft(o.reportText||"")}} className="action ghost">Enter Result</button>}
 {o.status==="PROCESSING"&&o.reportText&&<button disabled={busy===o.id} onClick={()=>advance(o,"COMPLETED",{reportText:o.reportText})} className="action green">Finalize Result</button>}
 {o.status==="COMPLETED"&&<button disabled={busy===o.id} onClick={()=>advance(o,"VERIFIED",{verifiedBy:"Authorized Laboratory User"})} className="action green">Verify Report</button>}
 {o.status==="VERIFIED"&&<button disabled={busy===o.id} onClick={()=>advance(o,"PUBLISHED")} className="action gold">Publish Report</button>}
 {(o.status==="VERIFIED"||o.status==="PUBLISHED")&&<Link href={`/investigation-reports/${o.id}`} className="action ghost">View / Print Report</Link>}
 </div></div>{edit===o.id&&<div className="mt-5 rounded-2xl border border-[#d6a443]/20 bg-[#07111c] p-4"><div className="grid gap-3 sm:grid-cols-2"><input value={o.specimen||o.master?.specimen||""} readOnly className="field"/><input value={o.master?.unit||""} readOnly className="field"/></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={6} placeholder="Enter verified laboratory result / findings…" className="mt-3 w-full rounded-xl border border-white/10 bg-[#0d1b2a] p-4 text-sm outline-none"/><div className="mt-3 flex gap-2"><button disabled={!draft.trim()||busy===o.id} onClick={()=>advance(o,"COMPLETED",{reportText:draft})} className="action green">Save & Finalize Result</button><button onClick={()=>setEdit(null)} className="action ghost">Cancel</button></div></div>}{o.reportText&&<div className="mt-5 rounded-2xl border border-white/10 bg-[#07111c] p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">Result</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-300">{o.reportText}</p>{o.criticalFlag&&<p className="mt-3 rounded-lg bg-red-500/10 p-2 text-xs font-black text-red-300">CRITICAL RESULT</p>}</div>}</article>})}</section></div><style jsx>{`.label{font-size:9px;text-transform:uppercase;letter-spacing:.15em;font-weight:900;color:#64748b;margin-bottom:4px}.action{border-radius:.75rem;padding:.65rem .9rem;font-size:10px;font-weight:900}.amber{background:#451f08;color:#fbbf24}.blue{background:#0b63ce;color:white}.green{background:#047857;color:white}.gold{background:#d6a443;color:#07111c}.ghost{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#cbd5e1}.field{border:1px solid rgba(255,255,255,.1);background:#0d1b2a;border-radius:.75rem;padding:.7rem;font-size:.8rem;color:#cbd5e1}`}</style></main>}
