"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const dateTime=(v:string)=>new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true});
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehab",PHARMACY:"Pharmacy / Medicine",OTHER:"Other"}[x]||x);
type Row={billNumber:string;patient:string;patientId:string;amount:number;paid:number;balance:number;status:string;createdAt:string};
type Trend={label:string;revenue:number;billing:number};
type Data={asOf:string;summary:{todayCollection:number;todayBilling:number;monthRevenue:number;monthBilling:number;yearRevenue:number;yearBilling:number;pendingBills:number;outstanding:number;paidBills:number;partialBills:number};revenue:{day:number;month:number;year:number};trends:{last7Days:Trend[];yearMonths:Trend[]};serviceTotals:Record<string,number>;paymentMethods:Record<string,number>;recent:Row[]};

function Chart({items}:{items:Trend[]}){const max=Math.max(1,...items.map(x=>Math.max(x.revenue,x.billing)));return <div className="mt-6 overflow-x-auto"><div className="flex min-w-[650px] items-end gap-3" style={{height:220}}>{items.map((x,i)=><div key={`${x.label}-${i}`} className="flex h-full min-w-[52px] flex-1 flex-col justify-end"><div className="flex h-[180px] items-end justify-center gap-1.5"><div title={`Revenue ${money(x.revenue)}`} className="w-4 rounded-t-md bg-[#c6a15b]" style={{height:`${Math.max(4,x.revenue/max*100)}%`}}/><div title={`Billing ${money(x.billing)}`} className="w-4 rounded-t-md bg-[#91a4ba]" style={{height:`${Math.max(4,x.billing/max*100)}%`}}/></div><p className="mt-3 text-center text-[10px] font-bold text-slate-500">{x.label}</p></div>)}</div><div className="mt-4 flex justify-center gap-6 text-[10px] font-bold text-slate-500"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#c6a15b]"/>Revenue collected</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#91a4ba]"/>Billing raised</span></div></div>}

export default function AdminBillingDashboard(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/billing",{cache:"no-store"}),x=await r.json();if(!r.ok)throw new Error(x.error);setData(x);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);const maxService=useMemo(()=>Math.max(1,...Object.values(data?.serviceTotals||{})),[data]);
 const kpis=data?[['Today Collection',data.summary.todayCollection,'Cash received today'],['Today Billing',data.summary.todayBilling,'Invoices raised today'],['Outstanding',data.summary.outstanding,'Receivable balance'],['Pending Bills',data.summary.pendingBills,'Awaiting settlement'],['Paid Bills',data.summary.paidBills,'Fully settled invoices'],['Partial Bills',data.summary.partialBills,'Partially settled invoices']]:[];
 return <main className="min-h-screen bg-[#e7ecf2] text-[#172536]"><div className="mx-auto max-w-[1580px] p-4 sm:p-6 lg:p-8">
  <header className="relative overflow-hidden rounded-[2rem] border border-[#263f60] bg-[#071a33] text-white shadow-[0_28px_70px_rgba(7,26,51,.25)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(198,161,91,.22),transparent_28%),radial-gradient(circle_at_15%_90%,rgba(38,91,155,.24),transparent_35%)]"/><div className="relative p-7 sm:p-9 lg:p-11"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-[#c6a15b]/50 bg-[#c6a15b]/10 text-xl font-black text-[#d9ba78]">₹</span><div><p className="text-[9px] font-black uppercase tracking-[.34em] text-[#d9ba78]">SAMS · Administration · Finance</p><p className="mt-1 text-[10px] font-semibold tracking-wide text-slate-300">Executive hospital finance control centre</p></div></div><h1 className="mt-6 text-4xl font-black tracking-[-.04em] sm:text-5xl lg:text-6xl">Billing & Revenue</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Consolidated hospital billing, collections, receivables and revenue performance.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-xs font-black text-white">← Admin</Link><button onClick={()=>void load()} className="rounded-xl bg-[#c6a15b] px-5 py-3 text-xs font-black text-[#071a33] shadow-lg">↻ Refresh</button></div></div><div className="mt-9 grid gap-4 border-t border-white/10 pt-5 sm:grid-cols-3"><div><p className="text-[9px] uppercase tracking-[.2em] text-slate-400">Reporting year</p><p className="mt-1.5 text-sm font-black">{data?new Date(data.asOf).getFullYear():"—"}</p></div><div><p className="text-[9px] uppercase tracking-[.2em] text-slate-400">System status</p><p className="mt-1.5 text-sm font-black text-emerald-300">● Finance data online</p></div><div><p className="text-[9px] uppercase tracking-[.2em] text-slate-400">Last refreshed</p><p className="mt-1.5 text-sm font-black">{data?dateTime(data.asOf):"Loading…"}</p></div></div></div></header>

  <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{kpis.map(([t,v,n],i=0)=><div key={String(t)} className="relative overflow-hidden rounded-[1.35rem] border border-slate-200 bg-white p-5 shadow-[0_12px_35px_rgba(25,45,70,.09)] transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(25,45,70,.14)]"><div className={`absolute left-0 top-0 h-1 w-full ${i===0?'bg-[#c6a15b]':i===2?'bg-rose-500':i===3?'bg-amber-500':i===4?'bg-emerald-500':i===5?'bg-violet-500':'bg-[#285f9f]'}`}/><p className="text-[9px] font-black uppercase tracking-[.2em] text-slate-400">{t}</p><p className="mt-3 text-[27px] font-black tracking-tight text-[#071f3d]">{loading?'—':typeof v==='number'&&i<3?money(v):String(v)}</p><p className="mt-2 text-[10px] font-semibold text-slate-400">{n}</p></div>)}</section>

  {error&&<div className="mt-5 rounded-2xl border border-red-200 bg-white p-4 text-sm font-bold text-red-700 shadow-sm">{error}</div>}

  <section className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.85fr]"><div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_15px_45px_rgba(25,45,70,.08)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#a27d3d]">Revenue Intelligence</p><h2 className="mt-1.5 text-2xl font-black text-[#071f3d]">Collection Performance</h2><p className="mt-1 text-xs text-slate-500">Last 7 days · revenue collected versus billing raised.</p></div><div className="rounded-xl border border-slate-200 bg-[#f7f9fb] px-4 py-2.5 text-right"><p className="text-[9px] font-black uppercase text-slate-400">YTD Revenue</p><p className="mt-0.5 text-base font-black text-[#071f3d]">{money(data?.summary.yearRevenue||0)}</p></div></div><Chart items={data?.trends.last7Days||[]}/></div>
   <div className="rounded-[1.75rem] border border-[#213a5a] bg-[#071a33] p-6 text-white shadow-[0_18px_50px_rgba(7,26,51,.18)] sm:p-7"><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#d8b976]">Executive Snapshot</p><h2 className="mt-1.5 text-2xl font-black">Day · Month · Year</h2><p className="mt-1 text-xs text-slate-300">Revenue collected</p><div className="mt-6 space-y-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">Today</p><p className="mt-1 text-2xl font-black text-[#d8b976]">{money(data?.revenue.day||0)}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">This Month</p><p className="mt-1 text-2xl font-black">{money(data?.revenue.month||0)}</p></div><div className="rounded-2xl border border-[#c6a15b]/30 bg-[#c6a15b]/10 p-4"><p className="text-[9px] font-black uppercase tracking-widest text-[#d8b976]">This Year</p><p className="mt-1 text-2xl font-black">{money(data?.revenue.year||0)}</p></div></div></div></section>

  <section className="mt-6 rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_15px_45px_rgba(25,45,70,.08)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#a27d3d]">Annual Performance</p><h2 className="mt-1.5 text-2xl font-black text-[#071f3d]">Month-wise Revenue</h2><p className="mt-1 text-xs text-slate-500">January through December · revenue collected versus billing raised.</p></div><div className="flex gap-2"><span className="rounded-full bg-[#f8f2e5] px-3 py-1.5 text-[10px] font-black text-[#8b6a32]">Revenue {money(data?.summary.yearRevenue||0)}</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-black text-slate-600">Billing {money(data?.summary.yearBilling||0)}</span></div></div><Chart items={data?.trends.yearMonths||[]}/></section>

  <section className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.85fr]"><div className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_15px_45px_rgba(25,45,70,.08)] sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#a27d3d]">Operations</p><h2 className="mt-1.5 text-2xl font-black text-[#071f3d]">Billing Work Queue</h2></div><Link href="/billing" className="rounded-xl bg-[#071f3d] px-4 py-2.5 text-xs font-black text-white">Open Billing →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-slate-200 text-[9px] font-black uppercase tracking-wider text-slate-400"><th className="px-3 py-3">Bill</th><th className="px-3 py-3">Patient</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Paid</th><th className="px-3 py-3">Balance</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th></tr></thead><tbody>{data?.recent.map(r=><tr key={r.billNumber} className="border-b border-slate-100 last:border-0 hover:bg-[#f7f9fb]"><td className="px-3 py-4 font-black text-[#071f3d]">{r.billNumber}</td><td className="px-3 py-4"><b>{r.patient}</b><span className="ml-2 text-[10px] text-slate-400">{r.patientId}</span></td><td className="px-3 py-4 font-bold">{money(r.amount)}</td><td className="px-3 py-4 font-bold text-emerald-700">{money(r.paid)}</td><td className="px-3 py-4 font-bold text-amber-700">{money(r.balance)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${r.status==='PAID'?'bg-emerald-50 text-emerald-700':r.status==='PARTIAL'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700'}`}>{r.status}</span></td><td className="px-3 py-4 text-slate-500">{dateTime(r.createdAt)}</td></tr>)}</tbody></table>{!loading&&!data?.recent.length&&<p className="p-8 text-center text-sm text-slate-400">No billing records yet.</p>}</div></div>
   <div className="space-y-6"><section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_15px_45px_rgba(25,45,70,.08)] sm:p-7"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#a27d3d]">Revenue Mix</p><h2 className="mt-1.5 text-2xl font-black text-[#071f3d]">Service-wise Billing</h2><div className="mt-5 space-y-4">{Object.entries(data?.serviceTotals||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div key={k}><div className="flex justify-between text-xs"><b>{label(k)}</b><span className="font-black text-[#071f3d]">{money(v)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#c6a15b]" style={{width:`${Math.min(100,v/maxService*100)}%`}}/></div></div>)}</div></section>
   <section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-[0_15px_45px_rgba(25,45,70,.08)] sm:p-7"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#a27d3d]">Collection Channels</p><h2 className="mt-1.5 text-2xl font-black text-[#071f3d]">Payment Methods</h2><div className="mt-5 space-y-3">{Object.entries(data?.paymentMethods||{}).sort((a,b)=>b[1]-a[1]).map(([k,v])=><div key={k} className="flex items-center justify-between rounded-xl bg-[#f7f9fb] px-4 py-3"><span className="text-xs font-bold text-slate-600">{k}</span><b className="text-sm text-[#071f3d]">{money(v)}</b></div>)}</div></section></div></section>

  <section className="mt-6 rounded-[1.75rem] border border-[#d9c28e]/40 bg-[#071a33] p-6 text-white shadow-[0_18px_50px_rgba(7,26,51,.16)] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.25em] text-[#d8b976]">Finance Control Centre</p><h2 className="mt-1.5 text-2xl font-black">Billing Operations</h2><p className="mt-1 text-xs text-slate-300">Operational billing remains separate from hospital-wide financial analytics.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Patient Billing","/billing"],["Invoices","/billing"],["Payments","/billing"],["Reports","/reports"]].map(([t,h])=><Link key={t} href={h} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-center text-[10px] font-black text-white transition hover:border-[#c6a15b]/50 hover:bg-[#c6a15b]/10">{t}<span className="ml-1 text-[#d8b976]">→</span></Link>)}</div></div></section>
 </div></main>;
}
