"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const money = (n: number) => `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const dateTime = (v: string) => new Date(v).toLocaleString("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: true });
const label = (x: string) => ({ CONSULTATION: "Consultation", INVESTIGATION: "Investigation", PROCEDURE: "Procedure / Surgery", ELECTRODIAGNOSIS: "Electrodiagnosis", PHYSIOTHERAPY: "Physiotherapy / Rehab", PHARMACY: "Pharmacy / Medicine", OTHER: "Other" }[x] || x);

type Row={billNumber:string;patient:string;patientId:string;amount:number;paid:number;balance:number;status:string;createdAt:string};
type Data={summary:{todayCollection:number;todayBilling:number;pendingBills:number;outstanding:number;paidBills:number;partialBills:number};serviceTotals:Record<string,number>;paymentMethods:Record<string,number>;recent:Row[]};

export default function AdminBillingDashboard(){
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/billing",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error);setData(x);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const cards=data?[['Today Collection',data.summary.todayCollection,'Cash/UPI/Card received','₹'],['Today Billing',data.summary.todayBilling,'Net invoices created','▣'],['Pending Bills',data.summary.pendingBills,'Awaiting full payment','!'],['Outstanding',data.summary.outstanding,'Balance across bills','₹'],['Paid Bills',data.summary.paidBills,'Fully settled','✓'],['Partial Bills',data.summary.partialBills,'Partially paid','◐']]:[];
 return <main className="min-h-screen bg-[#f3f6fa] text-slate-900"><div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">
  <header className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#061f49] via-[#082b61] to-[#0b63ce] p-6 text-white shadow-2xl sm:p-8"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-white/10 blur-2xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-blue-200">SAMS · Administration · Finance</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">Billing Dashboard</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-100">Hospital-wide billing, collections, outstanding balances and revenue operations — restricted to Administration.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-xs font-black text-white backdrop-blur">← Admin</Link><button onClick={()=>void load()} className="rounded-xl bg-white px-4 py-3 text-xs font-black text-[#082b61]">↻ Refresh</button></div></div></header>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([title,value,note,icon])=><div key={String(title)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{title}</p><p className="mt-2 text-2xl font-black text-[#082b61]">{loading?'—':String(icon)==='₹'?money(Number(value)):value}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 font-black text-[#0b63ce]">{icon}</span></div><p className="mt-3 text-[10px] font-semibold text-slate-400">{note}</p></div>)}</div>
  {error&&<div className="mt-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
  <section className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><div className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Operations</p><h2 className="mt-1 text-xl font-black text-[#082b61]">Billing Work Queue</h2></div><Link href="/billing" className="rounded-xl bg-[#082b61] px-4 py-2.5 text-xs font-black text-white">Open Billing →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-[9px] font-black uppercase tracking-wider text-slate-400"><th className="px-3 py-3">Bill</th><th className="px-3 py-3">Patient</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Paid</th><th className="px-3 py-3">Balance</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th></tr></thead><tbody>{data?.recent.map(r=><tr key={r.billNumber} className="border-b last:border-0"><td className="px-3 py-4 font-black text-[#082b61]">{r.billNumber}</td><td className="px-3 py-4"><b>{r.patient}</b><span className="ml-2 text-[10px] text-slate-400">{r.patientId}</span></td><td className="px-3 py-4 font-bold">{money(r.amount)}</td><td className="px-3 py-4 text-emerald-700">{money(r.paid)}</td><td className="px-3 py-4 text-amber-700">{money(r.balance)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${r.status==='PAID'?'bg-emerald-50 text-emerald-700':r.status==='PARTIAL'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{r.status}</span></td><td className="px-3 py-4 text-slate-500">{dateTime(r.createdAt)}</td></tr>)}</tbody></table>{!loading&&!data?.recent.length&&<p className="p-8 text-center text-sm text-slate-400">No billing records yet.</p>}</div></div>
   <div className="space-y-6"><section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Revenue Mix</p><h2 className="mt-1 text-xl font-black text-[#082b61]">Service-wise Billing</h2><div className="mt-4 space-y-3">{Object.entries(data?.serviceTotals||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div key={k}><div className="flex justify-between text-xs"><b>{label(k)}</b><span className="font-black text-[#082b61]">{money(v)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0b63ce]" style={{width:`${Math.min(100,(v/Math.max(1,Math.max(...Object.values(data?.serviceTotals||{_:1}))))*100)}%`}}/></div></div>)}</div></section>
   <section className="rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Quick Actions</p><h2 className="mt-1 text-xl font-black text-[#082b61]">Billing Operations</h2><div className="mt-4 grid grid-cols-2 gap-3">{[["Patient Billing","/billing"],["Procedure / Surgery","/billing"],["Invoices","/billing"],["Payments","/billing"],["Investigation Billing","/investigations"],["Billing Reports","/reports"]].map(([t,h])=><Link key={t} href={h} className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs font-black text-[#082b61] transition hover:border-blue-200 hover:bg-blue-50">{t}<span className="float-right text-blue-600">→</span></Link>)}</div></section></div></section>
  <section className="mt-6 rounded-[1.7rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Administration</p><h2 className="mt-1 text-xl font-black text-[#082b61]">Finance Controls</h2><p className="mt-1 text-xs text-slate-500">Hospital-wide financial views stay inside Admin; operational billing remains available from the Billing workspace.</p></div><div className="flex flex-wrap gap-2"><Link href="/settings" className="rounded-xl border px-4 py-2.5 text-xs font-black">Billing Settings</Link><Link href="/reports" className="rounded-xl bg-[#082b61] px-4 py-2.5 text-xs font-black text-white">Reports →</Link></div></div></section>
 </div></main>
}
