"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
const dateTime=(v:string)=>new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true});
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehab",PHARMACY:"Pharmacy / Medicine",OTHER:"Other"}[x]||x);

type Row={billNumber:string;patient:string;patientId:string;amount:number;paid:number;balance:number;status:string;createdAt:string};
type Trend={label:string;revenue:number;billing:number;date?:string};
type Data={asOf:string;summary:{todayCollection:number;todayBilling:number;monthRevenue:number;monthBilling:number;yearRevenue:number;yearBilling:number;pendingBills:number;outstanding:number;paidBills:number;partialBills:number};revenue:{day:number;month:number;year:number};trends:{last7Days:Trend[];yearMonths:Trend[]};serviceTotals:Record<string,number>;paymentMethods:Record<string,number>;recent:Row[]};

function BarChart({items}:{items:Trend[]}){
 const max=Math.max(1,...items.map(x=>Math.max(x.revenue,x.billing)));
 return <div className="mt-5 overflow-x-auto pb-1"><div className="flex min-w-[620px] items-end gap-3" style={{height:210}}>{items.map((x,i)=><div key={`${x.label}-${i}`} className="flex h-full flex-1 min-w-[55px] flex-col justify-end"><div className="flex h-[180px] items-end justify-center gap-1"><div title={`Revenue ${money(x.revenue)}`} className="w-3 rounded-t-md bg-[#0b63ce]" style={{height:`${Math.max(3,(x.revenue/max)*100)}%`}}/><div title={`Billing ${money(x.billing)}`} className="w-3 rounded-t-md bg-[#9bb9df]" style={{height:`${Math.max(3,(x.billing/max)*100)}%`}}/></div><p className="mt-2 text-center text-[10px] font-bold text-slate-500">{x.label}</p></div>)}</div><div className="mt-3 flex items-center justify-center gap-5 text-[10px] font-bold text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#0b63ce]"/>Revenue collected</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#9bb9df]"/>Billing raised</span></div></div>;
}

export default function AdminBillingDashboard(){
 const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/billing",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error);setData(x);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const maxService=useMemo(()=>Math.max(1,...Object.values(data?.serviceTotals||{})),[data]);
 const cards=data?[{t:"Today Collection",v:data.summary.todayCollection,n:"Collected today",accent:"blue"},{t:"Today Billing",v:data.summary.todayBilling,n:"Invoices raised today",accent:"slate"},{t:"Pending Bills",v:data.summary.pendingBills,n:"Awaiting full settlement",accent:"amber",count:true},{t:"Outstanding",v:data.summary.outstanding,n:"Receivable balance",accent:"rose"},{t:"Paid Bills",v:data.summary.paidBills,n:"Fully settled invoices",accent:"emerald",count:true},{t:"Partial Bills",v:data.summary.partialBills,n:"Partially settled",accent:"violet",count:true}]:[];
 return <main className="min-h-screen bg-[#eef3f8] text-slate-900"><div className="mx-auto max-w-[1540px] p-4 sm:p-6 lg:p-8">
  <header className="relative overflow-hidden rounded-[2.2rem] bg-[#061f49] text-white shadow-[0_25px_70px_rgba(8,43,97,.22)]"><div className="absolute inset-0 bg-gradient-to-br from-[#061f49] via-[#082b61] to-[#0b63ce]"/><div className="absolute -right-28 -top-36 h-96 w-96 rounded-full bg-white/10 blur-3xl"/><div className="absolute -bottom-40 left-1/3 h-80 w-80 rounded-full bg-cyan-300/10 blur-3xl"/><div className="relative p-7 sm:p-9 lg:p-10"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/12 ring-1 ring-white/15">₹</span><div><p className="text-[9px] font-black uppercase tracking-[.32em] text-blue-200">SAMS · Administration · Finance</p><p className="mt-0.5 text-[10px] font-bold text-blue-100/70">Restricted corporate finance workspace</p></div></div><h1 className="mt-5 text-4xl font-black tracking-[-.03em] sm:text-5xl lg:text-6xl">Billing & Revenue</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-100">Executive overview of hospital billing, collections, receivables and revenue performance.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin" className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-xs font-black backdrop-blur">← Admin</Link><button onClick={()=>void load()} className="rounded-xl bg-white px-4 py-3 text-xs font-black text-[#082b61] shadow-lg">↻ Refresh</button></div></div><div className="mt-8 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-3"><div><p className="text-[9px] uppercase tracking-widest text-blue-200/70">Reporting year</p><p className="mt-1 text-sm font-black">{data?new Date(data.asOf).getFullYear():"—"}</p></div><div><p className="text-[9px] uppercase tracking-widest text-blue-200/70">Live status</p><p className="mt-1 text-sm font-black text-emerald-300">● Finance data online</p></div><div><p className="text-[9px] uppercase tracking-widest text-blue-200/70">Last refreshed</p><p className="mt-1 text-sm font-black">{data?dateTime(data.asOf):"Loading…"}</p></div></div></div></header>

  <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{cards.map(c=><div key={c.t} className="group rounded-[1.45rem] border border-white bg-white p-5 shadow-[0_10px_35px_rgba(8,43,97,.06)] transition hover:-translate-y-0.5 hover:shadow-xl"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-slate-400">{c.t}</p><p className="mt-3 text-2xl font-black tracking-tight text-[#082b61]">{loading?"—":c.count?String(c.v):money(Number(c.v))}</p></div><span className={`h-2.5 w-2.5 rounded-full ${c.accent==="emerald"?"bg-emerald-500":c.accent==="amber"?"bg-amber-500":c.accent==="rose"?"bg-rose-500":c.accent==="violet"?"bg-violet-500":"bg-[#0b63ce]"}`}/></div><p className="mt-3 text-[10px] font-semibold text-slate-400">{c.n}</p></div>)}</section>

  {error&&<div className="mt-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}

  <section className="mt-6 grid gap-6 xl:grid-cols-[1.7fr_1fr]"><div className="rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#0b63ce]">Revenue Intelligence</p><h2 className="mt-1 text-2xl font-black tracking-tight text-[#082b61]">Collection Performance</h2><p className="mt-1 text-xs text-slate-500">Collected revenue versus billing raised.</p></div><div className="rounded-xl bg-slate-50 px-3 py-2 text-right"><p className="text-[9px] font-black uppercase text-slate-400">Current year</p><p className="text-sm font-black text-[#082b61]">{money(data?.summary.yearRevenue||0)}</p></div></div><BarChart items={data?.trends.last7Days||[]}/></div>
   <div className="rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)] sm:p-7"><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#0b63ce]">Revenue Snapshot</p><h2 className="mt-1 text-2xl font-black tracking-tight text-[#082b61]">Day · Month · Year</h2><div className="mt-5 space-y-3"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-[9px] font-black uppercase tracking-widest text-blue-600">Today</p><div className="mt-1 flex items-end justify-between"><b className="text-2xl text-[#082b61]">{money(data?.revenue.day||0)}</b><span className="text-[10px] font-bold text-slate-500">Revenue collected</span></div></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">This Month</p><div className="mt-1 flex items-end justify-between"><b className="text-2xl text-[#082b61]">{money(data?.revenue.month||0)}</b><span className="text-[10px] font-bold text-slate-500">Revenue collected</span></div></div><div className="rounded-2xl bg-[#082b61] p-4 text-white"><p className="text-[9px] font-black uppercase tracking-widest text-blue-200">This Year</p><div className="mt-1 flex items-end justify-between"><b className="text-2xl">{money(data?.revenue.year||0)}</b><span className="text-[10px] font-bold text-blue-100">Revenue collected</span></div></div></div></div></section>

  <section className="mt-6 rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)] sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#0b63ce]">Yearly Revenue</p><h2 className="mt-1 text-2xl font-black tracking-tight text-[#082b61]">Month-wise performance</h2><p className="mt-1 text-xs text-slate-500">January through December — revenue collected and billing raised.</p></div><div className="flex gap-2"><span className="rounded-full bg-blue-50 px-3 py-1.5 text-[10px] font-black text-[#0b63ce]">Revenue {money(data?.summary.yearRevenue||0)}</span><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-black text-slate-600">Billing {money(data?.summary.yearBilling||0)}</span></div></div><BarChart items={data?.trends.yearMonths||[]}/></section>

  <section className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0b63ce]">Operations</p><h2 className="mt-1 text-2xl font-black text-[#082b61]">Billing Work Queue</h2></div><Link href="/billing" className="rounded-xl bg-[#082b61] px-4 py-2.5 text-xs font-black text-white">Open Billing →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-[9px] font-black uppercase tracking-wider text-slate-400"><th className="px-3 py-3">Bill</th><th className="px-3 py-3">Patient</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Paid</th><th className="px-3 py-3">Balance</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th></tr></thead><tbody>{data?.recent.map(r=><tr key={r.billNumber} className="border-b last:border-0 hover:bg-slate-50"><td className="px-3 py-4 font-black text-[#082b61]">{r.billNumber}</td><td className="px-3 py-4"><b>{r.patient}</b><span className="ml-2 text-[10px] text-slate-400">{r.patientId}</span></td><td className="px-3 py-4 font-bold">{money(r.amount)}</td><td className="px-3 py-4 text-emerald-700">{money(r.paid)}</td><td className="px-3 py-4 text-amber-700">{money(r.balance)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${r.status==='PAID'?'bg-emerald-50 text-emerald-700':r.status==='PARTIAL'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{r.status}</span></td><td className="px-3 py-4 text-slate-500">{dateTime(r.createdAt)}</td></tr>)}</tbody></table>{!loading&&!data?.recent.length&&<p className="p-8 text-center text-sm text-slate-400">No billing records yet.</p>}</div></div>
   <div className="space-y-6"><section className="rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)]"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0b63ce]">Revenue Mix</p><h2 className="mt-1 text-2xl font-black text-[#082b61]">Service-wise Billing</h2><div className="mt-5 space-y-4">{Object.entries(data?.serviceTotals||{}).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div key={k}><div className="flex justify-between text-xs"><b>{label(k)}</b><span className="font-black text-[#082b61]">{money(v)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0b63ce]" style={{width:`${Math.min(100,(v/maxService)*100)}%`}}/></div></div>)}</div></section>
   <section className="rounded-[1.9rem] border border-slate-200/80 bg-white p-6 shadow-[0_15px_45px_rgba(8,43,97,.07)]"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0b63ce]">Quick Actions</p><h2 className="mt-1 text-2xl font-black text-[#082b61]">Finance Operations</h2><div className="mt-5 grid grid-cols-2 gap-3">{[["Patient Billing","/billing"],["Procedure / Surgery","/billing"],["Invoices","/billing"],["Payments","/billing"],["Investigation Billing","/investigations"],["Billing Reports","/reports"]].map(([t,h])=><Link key={t} href={h} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs font-black text-[#082b61] transition hover:-translate-y-0.5 hover:border-blue-200 hover:bg-blue-50">{t}<span className="float-right text-[#0b63ce]">→</span></Link>)}</div></section></div></section>

  <footer className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-[1.6rem] border border-slate-200 bg-[#f8fafc] px-5 py-4 text-[10px] font-bold text-slate-400"><span>SAMS · Administration Finance Control</span><span>Hospital-wide financial information remains restricted to Admin.</span></footer>
 </div></main>;
}
