"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

type Visit={id:number;tokenNumber:number;visitType:string;status:string;department:string|null;createdAt:string};
type Line={id:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null;sourceId:number|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;subtotal:number;discount:number;netAmount:number;paymentStatus:string;paymentMethod:string|null;paidAmount:number;balanceAmount:number;paidAt:string|null;lineItems?:Line[]};
type Data={visit:Visit;patient:{id:number;patientId:string;name:string;phone:string|null};lineItems:Line[];totals:{subtotal:number};bill:Bill|null};
type Tab="charges"|"invoices"|"payments"|"reports";
const TYPES=["CONSULTATION","INVESTIGATION","PROCEDURE","ELECTRODIAGNOSIS","PHYSIOTHERAPY","PHARMACY","OTHER"];
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",OTHER:"Other Service"}[x]||x);
const money=(n:number)=>`₹${n.toFixed(2)}`;
const visitDateTime=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?"Date/time unavailable":d.toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true});};

export default function BillingPage(){
 const search=useSearchParams();
 const initialPatientId=search.get("patientId")||"";
 const initialVisitId=Number(search.get("visitId")||0);
 const [pid,setPid]=useState(initialPatientId),[visits,setVisits]=useState<Visit[]>([]),[patient,setPatient]=useState<Data["patient"]|null>(null),[data,setData]=useState<Data|null>(null),[tab,setTab]=useState<Tab>("charges"),[type,setType]=useState("CONSULTATION"),[desc,setDesc]=useState(""),[qty,setQty]=useState("1"),[rate,setRate]=useState(""),[discount,setDiscount]=useState(""),[payAmount,setPayAmount]=useState(""),[method,setMethod]=useState("CASH"),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);const x=await r.json();if(!r.ok)throw new Error(x.error||"Billing request failed.");return x;};
 async function find(forwardVisitId=initialVisitId){setLoading(true);setError("");setMessage("");setData(null);setPatient(null);try{const x=await run(`/api/billing?patientId=${encodeURIComponent(pid.trim())}`);setPatient(x.patient);setVisits(x.visits);if(!x.visits.length)setMessage("Patient found, but no OPD visits are recorded yet.");else if(forwardVisitId>0){const match=x.visits.find((v:Visit)=>v.id===forwardVisitId);if(match)await load(match.id);}}catch(e){setError(e instanceof Error?e.message:"Unable to find patient.")}finally{setLoading(false)}}
 async function load(id:number){setLoading(true);setError("");try{const x=await run(`/api/billing?visitId=${id}`);setData(x);setPatient(x.patient);setTab("charges")}catch(e){setError(e instanceof Error?e.message:"Unable to load visit.")}finally{setLoading(false)}}
 useEffect(()=>{if(initialPatientId){void find(initialVisitId)}},[]);
 async function add(){if(!data)return;const q=Number(qty),r=Number(rate);if(!desc.trim()||!Number.isFinite(q)||q<=0||!Number.isFinite(r)||r<0){setError("Enter service, quantity and valid rate.");return}setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"addLine",visitId:data.visit.id,serviceType:type,description:desc.trim(),quantity:q,unitPrice:r})});setDesc("");setQty("1");setRate("");setMessage("Service added.");await load(data.visit.id)}catch(e){setError(e instanceof Error?e.message:"Unable to add service.")}finally{setLoading(false)}}
 async function remove(id:number){if(!data)return;setLoading(true);setError("");try{await run(`/api/billing?lineId=${id}`,{method:"DELETE"});await load(data.visit.id);setMessage("Charge removed.")}catch(e){setError(e instanceof Error?e.message:"Unable to remove charge.")}finally{setLoading(false)}}
 async function invoice(){if(!data)return;setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:data.visit.id})});await load(data.visit.id);setTab("invoices");setMessage("Invoice generated.")}catch(e){setError(e instanceof Error?e.message:"Unable to generate invoice.")}finally{setLoading(false)}}
 async function applyDiscount(){if(!data?.bill)return;const d=Number(discount);if(!Number.isFinite(d)||d<0){setError("Enter a valid discount.");return}setLoading(true);setError("");try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discount",billId:data.bill.id,discount:d})});await load(data.visit.id);setMessage("Discount updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to apply discount.")}finally{setLoading(false)}}
 async function pay(){if(!data?.bill)return;const p=Number(payAmount);if(!Number.isFinite(p)||p<=0||p>data.bill.balanceAmount){setError("Enter a payment amount within the outstanding balance.");return}setLoading(true);setError("");try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billId:data.bill.id,paidAmount:p,paymentMethod:method})});setPayAmount("");await load(data.visit.id);setTab("payments");setMessage("Payment recorded successfully.")}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.")}finally{setLoading(false)}}
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-black uppercase tracking-widest text-blue-600">SAMS · Hospital Finance</p><h1 className="mt-1 text-3xl font-black text-[#082b61]">Billing & Payments</h1><p className="mt-1 text-sm text-slate-500">Complete OPD billing: consultation, investigations, procedures, electrodiagnosis, rehabilitation, pharmacy and other services.</p></header>
 <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex gap-3"><input value={pid} onChange={e=>setPid(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void find()} placeholder="Enter Patient ID (e.g. SAMS-0004)" className="flex-1 rounded-xl border px-4 py-3"/><button onClick={()=>void find()} disabled={loading||!pid.trim()} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">{loading?"Loading...":"Load Patient"}</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}</section>
 {patient&&!data&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#082b61]">{patient.name}</h2><p className="text-sm text-slate-500">Patient ID: <b>{patient.patientId}</b></p><div className="mt-5 space-y-3">{visits.map(v=><button key={v.id} onClick={()=>void load(v.id)} className="flex w-full justify-between rounded-xl border p-4 text-left hover:bg-blue-50"><span><span className="flex flex-wrap items-center gap-x-3 gap-y-1"><b>OPD Visit #{v.id}</b><span className="text-xs font-semibold text-slate-600">{visitDateTime(v.createdAt)}</span></span><span className="mt-1 block text-xs text-slate-500">Token {v.tokenNumber} · {v.visitType} · {v.department||"Department not specified"}</span></span><b className="text-blue-600">Select →</b></button>)}</div></section>}
 {data&&<><section className="grid gap-3 sm:grid-cols-4"><Card t="Patient" v={data.patient.name}/><Card t="Patient ID" v={data.patient.patientId}/><Card t="OPD Visit" v={`#${data.visit.id}`}/><Card t="Outstanding" v={money(data.bill?.balanceAmount??Math.max(0,data.totals.subtotal-(data.bill?.discount??0)))}/></section><nav className="grid grid-cols-2 gap-2 rounded-2xl border bg-white p-2 sm:grid-cols-4">{([["charges","Patient Charges"],["invoices","Invoices"],["payments","Payments"],["reports","Billing Reports"]] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-3 py-3 text-sm font-bold ${tab===k?"bg-blue-600 text-white":"hover:bg-slate-50"}`}>{l}</button>)}</nav>
 {tab==="charges"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#082b61]">Patient Charges</h2><p className="mt-1 text-sm text-slate-500">Each service is a separate bill line. Investigation and pharmacy orders are imported automatically.</p><div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-[180px_1fr_90px_130px_auto]"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border px-3 py-3">{TYPES.map(x=><option key={x}>{x}</option>)}</select><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Service / procedure description" className="rounded-xl border px-3 py-3"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.01" step="0.01" className="rounded-xl border px-3 py-3"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" min="0" step="0.01" placeholder="Rate ₹" className="rounded-xl border px-3 py-3"/><button onClick={()=>void add()} disabled={loading} className="rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">Add Service</button></div><div className="mt-5 overflow-hidden rounded-xl border">{data.lineItems.length?data.lineItems.map(x=><div key={x.id} className="grid grid-cols-[1fr_80px_120px_80px] items-center gap-3 border-b px-4 py-4"><div><b>{x.description}</b><p className="text-xs text-slate-500">{label(x.serviceType)} · {money(x.unitPrice)} each</p></div><span>{x.quantity}</span><b>{money(x.amount)}</b><button onClick={()=>void remove(x.id)} disabled={loading||!!data.bill?.paidAmount} className="text-xs font-bold text-red-600 disabled:text-slate-300">Remove</button></div>):<p className="p-6 text-sm text-slate-500">No billable charges found for this OPD visit.</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Card t="Subtotal" v={money(data.bill?.subtotal??data.totals.subtotal)}/><Card t="Discount" v={money(data.bill?.discount??0)}/><Card t="Final Amount" v={money(data.bill?.netAmount??data.totals.subtotal)}/></div>{data.bill&&<div className="mt-4 flex gap-3"><input value={discount} onChange={e=>setDiscount(e.target.value)} type="number" min="0" placeholder="Discount ₹" className="rounded-xl border px-4 py-3"/><button onClick={()=>void applyDiscount()} disabled={loading||!!data.bill.paidAmount} className="rounded-xl bg-amber-500 px-5 py-3 font-bold text-white">Apply Discount</button></div>}<button onClick={()=>void invoice()} disabled={loading||!!data.bill} className="mt-5 rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white">{data.bill?`Invoice ${data.bill.billNumber} Generated`:"Generate Final Invoice"}</button></section>}
 {tab==="invoices"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#082b61]">Invoices</h2>{data.bill?<><div className="mt-5 grid gap-3 sm:grid-cols-5"><Card t="Invoice" v={data.bill.billNumber}/><Card t="Subtotal" v={money(data.bill.subtotal)}/><Card t="Discount" v={money(data.bill.discount)}/><Card t="Net" v={money(data.bill.netAmount)}/><Card t="Status" v={data.bill.paymentStatus}/></div><div className="mt-5 space-y-2">{data.lineItems.map(x=><div key={x.id} className="flex justify-between border-b py-3"><span><b>{x.description}</b><small className="ml-2 text-slate-500">{label(x.serviceType)} · {x.quantity}</small></span><b>{money(x.amount)}</b></div>)}</div><div className="mt-5 flex justify-between border-t pt-4 font-black"><span>Final Invoice Amount</span><span>{money(data.bill.netAmount)}</span></div></>:<><p className="mt-3 text-sm text-slate-500">No invoice generated yet.</p><button onClick={()=>void invoice()} className="mt-4 rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">Generate Final Invoice</button></>}</section>}
 {tab==="payments"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#082b61]">Payments</h2>{!data.bill?<p className="mt-3 text-sm text-slate-500">Generate the invoice first.</p>:data.bill.balanceAmount<=0?<p className="mt-5 rounded-xl bg-emerald-50 p-5 font-bold text-emerald-700">Fully paid · Receipt {data.bill.receiptNumber||"—"}</p>:<div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="number" min="0.01" max={data.bill.balanceAmount} step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)} placeholder={`Amount (max ${money(data.bill.balanceAmount)})`} className="rounded-xl border px-4 py-3"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border px-4 py-3"><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select><button onClick={()=>void pay()} disabled={loading} className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Record Payment</button></div>} {data.bill&&<div className="mt-6 grid gap-3 sm:grid-cols-3"><Card t="Final" v={money(data.bill.netAmount)}/><Card t="Paid" v={money(data.bill.paidAmount)}/><Card t="Outstanding" v={money(data.bill.balanceAmount)}/></div>}</section>}
 {tab==="reports"&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#082b61]">Billing Reports</h2><div className="mt-5 grid gap-3 sm:grid-cols-4"><Card t="Subtotal" v={money(data.bill?.subtotal??data.totals.subtotal)}/><Card t="Discount" v={money(data.bill?.discount??0)}/><Card t="Paid" v={money(data.bill?.paidAmount??0)}/><Card t="Outstanding" v={money(data.bill?.balanceAmount??data.totals.subtotal)}/></div><p className="mt-5 rounded-xl bg-slate-50 p-5 text-sm"><b>{data.patient.name}</b> · {data.patient.patientId} · OPD Visit #{data.visit.id} · Invoice {data.bill?.billNumber||"Not generated"} · Receipt {data.bill?.receiptNumber||"Not paid"}</p></section>}
 </>}
 </div></main>;
}
function Card({t,v}:{t:string;v:string}){return <div className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{t}</p><p className="mt-2 truncate font-black text-[#082b61]">{v}</p></div>}
