"use client";

import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

type Visit={id:number;tokenNumber:number;visitType:string;status:string;department:string|null;createdAt:string};
type Line={id:number;serviceType:string;description:string;quantity:number;unitPrice:number;amount:number;sourceType:string|null;sourceId:number|null};
type Bill={id:number;billNumber:string;receiptNumber:string|null;subtotal:number;discount:number;netAmount:number;paymentStatus:string;paymentMethod:string|null;paidAmount:number;balanceAmount:number;paidAt:string|null};
type Patient={id:number;patientId:string;name:string;phone:string|null};
type Data={visit:Visit;patient:Patient;lineItems:Line[];totals:{subtotal:number};bill:Bill|null;consultationFee:number};
type Tab="charges"|"procedures"|"invoices"|"payments";

const TYPES=["INVESTIGATION","PROCEDURE","ELECTRODIAGNOSIS","PHYSIOTHERAPY","PHARMACY","OTHER"];
const label=(x:string)=>({CONSULTATION:"Consultation",INVESTIGATION:"Investigation",PROCEDURE:"Procedure / Surgery",ELECTRODIAGNOSIS:"Electrodiagnosis",PHYSIOTHERAPY:"Physiotherapy / Rehabilitation",PHARMACY:"Pharmacy / Medicine",OTHER:"Other Service"}[x]||x);
const money=(n:number)=>`₹${Number(n||0).toFixed(2)}`;
const dt=(v:string)=>new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true});

export default function BillingPage(){
 const search=useSearchParams();
 const [pid,setPid]=useState(search.get("patientId")||"");
 const [visits,setVisits]=useState<Visit[]>([]),[patient,setPatient]=useState<Patient|null>(null),[data,setData]=useState<Data|null>(null);
 const [tab,setTab]=useState<Tab>("charges"),[type,setType]=useState("OTHER"),[desc,setDesc]=useState(""),[qty,setQty]=useState("1"),[rate,setRate]=useState("");
 const [discount,setDiscount]=useState(""),[payAmount,setPayAmount]=useState(""),[method,setMethod]=useState("CASH");
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const run=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);const x=await r.json();if(!r.ok)throw new Error(x.error||"Billing request failed.");return x;};
 async function find(){setLoading(true);setError("");setMessage("");setData(null);setPatient(null);try{const x=await run(`/api/billing?patientId=${encodeURIComponent(pid.trim())}`);setPatient(x.patient);setVisits(x.visits||[]);if(!x.visits?.length)setMessage("Patient found, but no OPD visits are recorded yet.");}catch(e){setError(e instanceof Error?e.message:"Unable to find patient.")}finally{setLoading(false)}}
 async function load(id:number){setLoading(true);setError("");setMessage("");try{const x=await run(`/api/billing?visitId=${id}`);setData(x);setPatient(x.patient);setTab("charges");}catch(e){setError(e instanceof Error?e.message:"Unable to load visit.")}finally{setLoading(false)}}
 useEffect(()=>{if(pid)void find()},[]);
 async function addLine(serviceType=type){if(!data)return;const q=Number(qty),r=Number(rate);if(!desc.trim()||!Number.isFinite(q)||q<=0||!Number.isFinite(r)||r<0){setError("Enter service, quantity and valid rate.");return}setLoading(true);setError("");try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"addLine",visitId:data.visit.id,serviceType,description:desc.trim(),quantity:q,unitPrice:r})});setDesc("");setQty("1");setRate("");setMessage(serviceType==="PROCEDURE"?"Procedure / surgery charge added.":"Service added.");await load(data.visit.id);setTab(serviceType==="PROCEDURE"?"procedures":"charges");}catch(e){setError(e instanceof Error?e.message:"Unable to add service.")}finally{setLoading(false)}}
 async function remove(id:number){if(!data)return;setLoading(true);try{await run(`/api/billing?lineId=${id}`,{method:"DELETE"});await load(data.visit.id);setMessage("Charge removed.")}catch(e){setError(e instanceof Error?e.message:"Unable to remove charge.")}finally{setLoading(false)}}
 async function invoice(){if(!data)return;setLoading(true);try{await run("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitId:data.visit.id})});await load(data.visit.id);setTab("invoices");setMessage("Final invoice generated.")}catch(e){setError(e instanceof Error?e.message:"Unable to generate invoice.")}finally{setLoading(false)}}
 async function applyDiscount(){if(!data?.bill)return;const d=Number(discount);if(!Number.isFinite(d)||d<0){setError("Enter a valid discount.");return}setLoading(true);try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"discount",billId:data.bill.id,discount:d})});await load(data.visit.id);setMessage("Discount updated.")}catch(e){setError(e instanceof Error?e.message:"Unable to apply discount.")}finally{setLoading(false)}}
 async function pay(){if(!data?.bill)return;const p=Number(payAmount);if(!Number.isFinite(p)||p<=0||p>data.bill.balanceAmount){setError("Enter a payment amount within the outstanding balance.");return}setLoading(true);try{await run("/api/billing",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billId:data.bill.id,paidAmount:p,paymentMethod:method})});setPayAmount("");await load(data.visit.id);setTab("payments");setMessage("Payment recorded successfully.")}catch(e){setError(e instanceof Error?e.message:"Unable to record payment.")}finally{setLoading(false)}}
 const consultation=data?.lineItems.find(x=>x.serviceType==="CONSULTATION"&&x.sourceType==="OPD_VISIT");
 const subtotal=data?.bill?.subtotal??data?.totals.subtotal??0;
 const net=data?.bill?.netAmount??Math.max(0,subtotal-(data?.bill?.discount??0));
 const printTitle=data?.bill?.receiptNumber?"Payment Receipt":"Final Bill";
 const print=()=>window.print();
 return <main className="min-h-screen bg-[#f4f7fb] p-4 text-slate-900 sm:p-6 lg:p-8 print:bg-white print:p-0"><style jsx global>{`@media print{body{background:white}.no-print{display:none!important}.print-only{display:block!important}}.print-only{display:none}`}</style><div className="mx-auto max-w-[1450px] space-y-6 no-print">
  <header className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#082b61] via-[#0b427f] to-[#0b63ce] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.25em] text-blue-200">SAMS · Hospital Finance</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Billing & Payments</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">Complete billing for consultation, investigations, procedures, surgery, rehabilitation, pharmacy and final payment.</p></header>
  <section className="rounded-[1.5rem] border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><input value={pid} onChange={e=>setPid(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void find()} placeholder="Enter Patient ID (e.g. SAMS-0004)" className="flex-1 rounded-xl border bg-slate-50 px-4 py-3.5 font-semibold"/><button onClick={()=>void find()} disabled={loading||!pid.trim()} className="rounded-xl bg-[#0b63ce] px-7 py-3.5 font-black text-white">{loading?"Loading...":"Load Patient"}</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}</section>
  {patient&&!data&&<section className="overflow-hidden rounded-[1.5rem] border bg-white shadow-sm"><div className="border-b bg-slate-50 p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Patient Finance Profile</p><h2 className="mt-1 text-xl font-black text-[#082b61]">{patient.name}</h2><p className="text-xs text-slate-500">{patient.patientId}{patient.phone?` · ${patient.phone}`:""}</p></div><div className="space-y-3 p-5"><p className="text-xs font-bold text-slate-500">Select the OPD Visit to continue billing</p>{visits.map((v,i)=><button key={v.id} onClick={()=>void load(v.id)} className="group w-full rounded-2xl border p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap gap-2"><b className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs text-blue-700">OPD Visit #{v.id}</b>{i===0&&<span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">LATEST</span>}<span className="rounded-lg bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{v.status}</span></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><span><small className="block uppercase tracking-wider text-slate-400">Date & Time</small><strong>{dt(v.createdAt)}</strong></span><span><small className="block uppercase tracking-wider text-slate-400">Token</small><strong>#{v.tokenNumber}</strong></span><span><small className="block uppercase tracking-wider text-slate-400">Visit / Department</small><strong>{v.visitType} · {v.department||"Not specified"}</strong></span></div></div><span className="rounded-xl bg-[#0b63ce] px-5 py-3 text-center text-xs font-black text-white">Select Visit →</span></div></button>)}</div></section>}
  {data&&<>
   <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card t="Patient" v={data.patient.name}/><Card t="Patient ID" v={data.patient.patientId}/><Card t="OPD Visit" v={`#${data.visit.id} · ${dt(data.visit.createdAt)}`}/><Card t="Outstanding" v={money(data.bill?.balanceAmount??net)}/></section>
   <nav className="grid grid-cols-2 gap-2 rounded-2xl border bg-white p-2 shadow-sm sm:grid-cols-4">{([["charges","Patient Charges"],["procedures","Procedure / Surgery"],["invoices","Invoices"],["payments","Payments"]] as [Tab,string][]).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`rounded-xl px-3 py-3 text-xs font-black sm:text-sm ${tab===k?"bg-[#0b63ce] text-white":"text-slate-600 hover:bg-slate-50"}`}>{l}</button>)}</nav>
   {tab==="charges"&&<section className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-600">Visit Billing</p><h2 className="text-xl font-black text-[#082b61]">Patient Charges</h2><p className="mt-1 text-sm text-slate-500">Consultation is automatically added from the OPD visit. Investigation and pharmacy orders are imported automatically.</p></div>{consultation&&<div className="mt-5 flex items-center justify-between rounded-2xl border border-blue-100 bg-blue-50 p-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Automatic Consultation</p><b className="text-[#082b61]">{consultation.description}</b><p className="text-xs text-slate-500">OPD Visit #{data.visit.id}</p></div><strong className="text-lg text-blue-700">{money(consultation.amount)}</strong></div>}<div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="mb-3 text-xs font-black text-slate-500">Add additional service</p><div className="grid gap-3 md:grid-cols-[180px_1fr_90px_130px_auto]"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border bg-white px-3 py-3">{TYPES.map(x=><option key={x}>{x}</option>)}</select><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Service description" className="rounded-xl border bg-white px-3 py-3"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.01" step="0.01" className="rounded-xl border bg-white px-3 py-3"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" min="0" step="0.01" placeholder="Rate ₹" className="rounded-xl border bg-white px-3 py-3"/><button onClick={()=>void addLine()} disabled={loading} className="rounded-xl bg-[#0b63ce] px-4 py-3 font-black text-white">Add Service</button></div></div><Lines data={data} remove={remove} loading={loading}/><Totals subtotal={subtotal} discount={data.bill?.discount??0} net={net}/><div className="mt-5 flex flex-wrap gap-3">{data.bill&&<><input value={discount} onChange={e=>setDiscount(e.target.value)} type="number" min="0" placeholder="Discount ₹" className="rounded-xl border px-4 py-3"/><button onClick={()=>void applyDiscount()} disabled={loading||!!data.bill.paidAmount} className="rounded-xl bg-amber-500 px-5 py-3 font-black text-white">Apply Discount</button></>}<button onClick={()=>void invoice()} disabled={loading||!!data.bill} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">{data.bill?`Invoice ${data.bill.billNumber} Generated`:"Generate Final Invoice"}</button></div></section>}
   {tab==="procedures"&&<section className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6"><div className="rounded-2xl bg-gradient-to-r from-[#082b61] to-[#0b63ce] p-5 text-white"><p className="text-[9px] font-black uppercase tracking-[.2em] text-blue-200">Dedicated Procedure Billing</p><h2 className="mt-1 text-2xl font-black">Procedure / Surgery</h2><p className="mt-1 text-sm text-blue-100">Add procedure or surgery charges for the selected patient visit.</p></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_110px_150px_auto]"><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Procedure / surgery name" className="rounded-xl border px-4 py-3"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="1" step="1" className="rounded-xl border px-4 py-3"/><input value={rate} onChange={e=>setRate(e.target.value)} type="number" min="0" step="0.01" placeholder="Rate ₹" className="rounded-xl border px-4 py-3"/><button onClick={()=>void addLine("PROCEDURE")} disabled={loading} className="rounded-xl bg-[#0b63ce] px-6 py-3 font-black text-white">Add Procedure</button></div><div className="mt-6 rounded-2xl border p-4"><h3 className="font-black text-[#082b61]">Current Procedure / Surgery Charges</h3><div className="mt-3">{data.lineItems.filter(x=>x.serviceType==="PROCEDURE").length?data.lineItems.filter(x=>x.serviceType==="PROCEDURE").map(x=><div key={x.id} className="flex items-center justify-between border-b py-3"><div><b>{x.description}</b><p className="text-xs text-slate-500">Qty {x.quantity} · {money(x.unitPrice)} each</p></div><div className="flex items-center gap-4"><b>{money(x.amount)}</b><button onClick={()=>void remove(x.id)} disabled={loading||!!data.bill?.paidAmount} className="text-xs font-black text-red-600">Remove</button></div></div>):<p className="py-4 text-sm text-slate-500">No procedure or surgery charge added yet.</p>}</div></div></section>}
   {tab==="invoices"&&<section className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-black text-[#082b61]">Final Invoice</h2>{data.bill?<><div className="mt-5 grid gap-3 sm:grid-cols-4"><Card t="Invoice" v={data.bill.billNumber}/><Card t="Final Amount" v={money(data.bill.netAmount)}/><Card t="Paid" v={money(data.bill.paidAmount)}/><Card t="Status" v={data.bill.paymentStatus}/></div><Lines data={data} remove={remove} loading={loading}/><div className="mt-5 flex flex-wrap gap-3"><button onClick={print} className="rounded-xl bg-[#082b61] px-6 py-3 font-black text-white">🖨 Print Final Bill</button>{data.bill.receiptNumber&&<button onClick={print} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">🧾 Print Receipt</button>}</div></>:<><p className="mt-3 text-sm text-slate-500">No invoice generated yet.</p><button onClick={()=>void invoice()} className="mt-4 rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">Generate Final Invoice</button></>}</section>}
   {tab==="payments"&&<section className="rounded-[1.5rem] border bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-black text-[#082b61]">Payments & Receipt</h2>{!data.bill?<p className="mt-3 text-sm text-slate-500">Generate the final invoice first.</p>:data.bill.balanceAmount<=0?<><p className="mt-5 rounded-2xl bg-emerald-50 p-5 font-black text-emerald-700">PAID · Receipt {data.bill.receiptNumber||"—"}</p><button onClick={print} className="mt-5 rounded-xl bg-[#082b61] px-6 py-3 font-black text-white">🧾 Print Payment Receipt</button></>:<><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input type="number" min="0.01" max={data.bill.balanceAmount} step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)} placeholder={`Amount · outstanding ${money(data.bill.balanceAmount)}`} className="rounded-xl border px-4 py-3"/><select value={method} onChange={e=>setMethod(e.target.value)} className="rounded-xl border px-4 py-3"><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK_TRANSFER</option></select><button onClick={()=>void pay()} disabled={loading} className="rounded-xl bg-[#0b63ce] px-6 py-3 font-black text-white">Record Payment</button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Card t="Final" v={money(data.bill.netAmount)}/><Card t="Paid" v={money(data.bill.paidAmount)}/><Card t="Outstanding" v={money(data.bill.balanceAmount)}/></div></>}</section>}
  </>}
 </div>
 {data&&<section className="print-only mx-auto max-w-3xl p-8 text-black"><div className="border-b-2 border-black pb-5"><h1 className="text-2xl font-black">SAMS · SERAWAT ADVANCED MULTISPECIALITY JOINT & SPINE CENTRE</h1><p className="mt-2 font-bold">{printTitle}</p></div><div className="grid grid-cols-2 gap-3 py-5 text-sm"><p><b>Patient:</b> {data.patient.name}</p><p><b>Patient ID:</b> {data.patient.patientId}</p><p><b>OPD Visit:</b> #{data.visit.id}</p><p><b>Date:</b> {dt(data.visit.createdAt)}</p><p><b>Invoice:</b> {data.bill?.billNumber||"—"}</p><p><b>Receipt:</b> {data.bill?.receiptNumber||"—"}</p></div><table className="w-full border-collapse text-sm"><thead><tr><th className="border p-2 text-left">Service</th><th className="border p-2">Qty</th><th className="border p-2 text-right">Amount</th></tr></thead><tbody>{data.lineItems.map(x=><tr key={x.id}><td className="border p-2">{x.description}</td><td className="border p-2 text-center">{x.quantity}</td><td className="border p-2 text-right">{money(x.amount)}</td></tr>)}</tbody></table><div className="ml-auto mt-5 w-64 space-y-2 text-sm"><p className="flex justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></p><p className="flex justify-between"><span>Discount</span><b>{money(data.bill?.discount||0)}</b></p><p className="flex justify-between border-t pt-2 text-lg"><span>Final</span><b>{money(net)}</b></p><p className="flex justify-between"><span>Paid</span><b>{money(data.bill?.paidAmount||0)}</b></p><p className="flex justify-between"><span>Balance</span><b>{money(data.bill?.balanceAmount||0)}</b></p></div><p className="mt-10 border-t pt-4 text-xs">This is a computer-generated document.</p></section>}
 </main>
}

function Card({t,v}:{t:string;v:string}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{t}</p><p className="mt-1 break-words text-sm font-black text-[#082b61]">{v}</p></div>}
function Lines({data,remove,loading}:{data:Data;remove:(id:number)=>Promise<void>;loading:boolean}){return <div className="mt-5 overflow-hidden rounded-2xl border">{data.lineItems.length?data.lineItems.map(x=><div key={x.id} className="grid grid-cols-[1fr_70px_110px_auto] items-center gap-3 border-b p-4 last:border-b-0"><div><b>{x.description}</b><p className="text-xs text-slate-500">{label(x.serviceType)} · {money(x.unitPrice)} each</p></div><span>{x.quantity}</span><b>{money(x.amount)}</b><button onClick={()=>void remove(x.id)} disabled={loading||!!data.bill?.paidAmount||x.serviceType==="CONSULTATION"} className="text-xs font-black text-red-600 disabled:text-slate-300">{x.serviceType==="CONSULTATION"?"Automatic":"Remove"}</button></div>):<p className="p-6 text-sm text-slate-500">No billable charges found.</p>}</div>}
function Totals({subtotal,discount,net}:{subtotal:number;discount:number;net:number}){return <div className="mt-5 grid gap-3 sm:grid-cols-3"><Card t="Subtotal" v={money(subtotal)}/><Card t="Discount" v={money(discount)}/><Card t="Final Amount" v={money(net)}/></div>}
