"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Doctor={id:number;name:string;qualification?:string|null;departmentId?:number|null;department?:{id:number;name:string;code:string}|null};
type Appointment={id:number;appointmentNo:string;patientType:string;patientName:string;mobile:string;dob?:string|null;gender?:string|null;reason?:string|null;departmentId?:number|null;departmentName?:string|null;doctorId?:number|null;doctorName:string;appointmentDate:string;appointmentTime:string;source:string;status:string;opdVisitId?:number|null;patientId?:number|null};
function slots(date:string){if(!date)return[];const m=Number(date.slice(5,7));const start=m>=4&&m<=9?8:9;const out:string[]=[];for(let x=start*60;x<=15*60;x+=5){const h=Math.floor(x/60),min=x%60,s=h>=12?"PM":"AM";out.push(`${h%12||12}:${String(min).padStart(2,"0")} ${s}`)}return out}

const nav=[
 {label:"Home",href:"/"},{label:"Dashboard",href:"/dashboard"},{label:"Patient",href:"/patients"},{label:"Patient Portal",href:"/portal"}
];

export default function ReceptionAppointments(){
 const[tab,setTab]=useState<"book"|"list">("book"),[patientType,setPatientType]=useState<"new"|"existing">("new"),[doctors,setDoctors]=useState<Doctor[]>([]),[doctorId,setDoctorId]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[name,setName]=useState(""),[mobile,setMobile]=useState(""),[dob,setDob]=useState(""),[gender,setGender]=useState(""),[reason,setReason]=useState(""),[appointments,setAppointments]=useState<Appointment[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[error,setError]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[registering,setRegistering]=useState<Appointment|null>(null),[aadhaar,setAadhaar]=useState("");
 useEffect(()=>{fetch("/api/doctors",{cache:"no-store"}).then(r=>r.json()).then(d=>setDoctors(Array.isArray(d)?d:[])).catch(()=>setError("Unable to load consultants."));load()},[]);
 async function load(){try{setLoading(true);const r=await fetch("/api/appointments",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to load appointments");setAppointments(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load appointments")}finally{setLoading(false)}}
 const selectedDoctor=doctors.find(d=>String(d.id)===doctorId);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return appointments.filter(a=>(status==="ALL"||a.status===status)&&(!q||`${a.patientName} ${a.mobile} ${a.appointmentNo} ${a.doctorName}`.toLowerCase().includes(q))).sort((a,b)=>`${a.appointmentDate} ${a.appointmentTime}`.localeCompare(`${b.appointmentDate} ${b.appointmentTime}`))},[appointments,query,status]);
 const counts=useMemo(()=>({scheduled:appointments.filter(a=>a.status==="SCHEDULED").length,checked:appointments.filter(a=>a.status==="CHECKED_IN").length,registered:appointments.filter(a=>a.status==="OPD_REGISTERED").length}),[appointments]);
 async function book(){const cleanMobile=mobile.replace(/\D/g,"");if(!doctorId||!date||!time||!name.trim()||(cleanMobile.length!==0&&cleanMobile.length!==10)||(patientType==="new"&&!dob)){setError("Please complete patient, consultant, date and time details. Mobile is optional; if entered, use exactly 10 digits.");return}setSaving(true);setError("");try{const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientType,patientName:name,mobile:cleanMobile,dob,gender,reason,doctorId:Number(doctorId),doctorName:selectedDoctor?.name,departmentId:selectedDoctor?.departmentId,departmentName:selectedDoctor?.department?.name,appointmentDate:date,appointmentTime:time,source:"RECEPTION"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to book appointment");setAppointments(x=>[...x,d]);setTab("list");setName("");setMobile("");setDob("");setGender("");setReason("");setTime("")}catch(e){setError(e instanceof Error?e.message:"Unable to book appointment")}finally{setSaving(false)}}
 async function checkIn(id:number){setError("");try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"CHECKED_IN"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to check-in");setAppointments(x=>x.map(a=>a.id===id?d:a))}catch(e){setError(e instanceof Error?e.message:"Unable to check-in patient")}}
 async function registerOPD(){if(!registering)return;if(registering.patientType==="NEW"&&aadhaar.replace(/\D/g,"").length!==12){setError("Aadhaar number is required for a new patient and must contain exactly 12 digits.");return}setSaving(true);setError("");try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:registering.id,action:"REGISTER_OPD",aadhaarNumber:aadhaar})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to register OPD visit");setAppointments(x=>x.map(a=>a.id===registering.id?d.appointment:a));setRegistering(null);setAadhaar("");setTab("list")}catch(e){setError(e instanceof Error?e.message:"Unable to register OPD visit")}finally{setSaving(false)}}
 async function cancel(id:number){try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"CANCELLED"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to cancel");setAppointments(x=>x.map(a=>a.id===id?d:a))}catch(e){setError(e instanceof Error?e.message:"Unable to cancel appointment")}}
 return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(133,180,136,.28),transparent_30%),radial-gradient(circle_at_88%_14%,rgba(246,203,126,.30),transparent_28%),linear-gradient(180deg,#eef7ef_0%,#f8f5e9_48%,#edf4ee_100%)] text-[#173b35]">
 <header className="sticky top-0 z-30 border-b border-white/70 bg-[#f8fbf5]/92 px-4 py-3 shadow-sm backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-[1320px] items-center gap-3"><div className="shrink-0"><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#5d8066]">SAMS · Reception</p><h1 className="text-xl font-black tracking-tight text-[#163c36] sm:text-2xl">Appointments</h1></div><nav className="ml-auto hidden items-center gap-1 lg:flex">{nav.map(n=><Link key={n.href} href={n.href} className="rounded-xl px-3 py-2 text-[11px] font-black text-[#49645d] hover:bg-white hover:text-[#173b35]">{n.label}</Link>)}</nav><Link href="/reception" className="rounded-xl border border-[#cbd9cd] bg-white/90 px-3 py-2 text-[10px] font-black text-[#173b35] shadow-sm">← Reception</Link></div><div className="mx-auto mt-2 flex max-w-[1320px] gap-1 overflow-x-auto lg:hidden">{nav.map(n=><Link key={n.href} href={n.href} className="shrink-0 rounded-lg bg-white/70 px-2.5 py-1.5 text-[9px] font-black text-[#49645d]">{n.label}</Link>)}</div></header>
 <div className="mx-auto max-w-[1320px] px-4 py-6 sm:px-7 sm:py-8">
 <section className="relative overflow-hidden rounded-[2rem] border border-white/80 bg-[linear-gradient(135deg,#1d5647_0%,#36745d_55%,#7a9b69_100%)] p-6 text-white shadow-[0_24px_65px_rgba(47,91,65,.20)] sm:p-8"><div className="pointer-events-none absolute -right-16 -top-20 h-64 w-64 rounded-full bg-amber-200/15 blur-3xl"/><div className="pointer-events-none absolute -bottom-24 left-1/3 h-48 w-80 rounded-full bg-white/10 blur-3xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.3em] text-emerald-100">Reception · Appointment Desk</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">Plan the patient’s next step.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/78">Book a convenient slot, welcome the patient at reception, then move the appointment directly into OPD.</p></div><div className="grid grid-cols-3 gap-2 sm:min-w-[330px]"><div className="rounded-2xl border border-white/15 bg-white/10 p-3 backdrop-blur"><p className="text-[8px] font-black uppercase tracking-wider text-emerald-100">Scheduled</p><p className="mt-1 text-2xl font-black">{counts.scheduled}</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-3 backdrop-blur"><p className="text-[8px] font-black uppercase tracking-wider text-emerald-100">Checked-in</p><p className="mt-1 text-2xl font-black">{counts.checked}</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-3 backdrop-blur"><p className="text-[8px] font-black uppercase tracking-wider text-emerald-100">OPD</p><p className="mt-1 text-2xl font-black">{counts.registered}</p></div></div></div></section>
 <section className="mt-5 rounded-[1.5rem] border border-white/80 bg-white/88 p-2 shadow-sm backdrop-blur-xl"><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTab("book")} className={`rounded-xl px-5 py-3 text-sm font-black transition ${tab==="book"?"bg-[#173f36] text-white shadow-md":"text-[#567067] hover:bg-[#eef6ef]"}`}>Book Appointment</button><button onClick={()=>{setTab("list");load()}} className={`rounded-xl px-5 py-3 text-sm font-black transition ${tab==="list"?"bg-[#173f36] text-white shadow-md":"text-[#567067] hover:bg-[#eef6ef]"}`}>See Appointments</button></div></section>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 {tab==="book"?<section className="mt-5 rounded-[2rem] border border-white/80 bg-white/92 p-5 shadow-[0_18px_55px_rgba(43,78,54,.09)] backdrop-blur-xl sm:p-7"><div className="mb-6 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-[#66846b]">01 · Booking workspace</p><h3 className="mt-1 text-2xl font-black text-[#173b35]">Create an appointment</h3></div><span className="rounded-full bg-[#edf6ee] px-3 py-1.5 text-[9px] font-black uppercase tracking-wide text-[#4d7659]">Mobile optional</span></div><div className="grid gap-4 lg:grid-cols-2">
 <div className="rounded-2xl border border-[#dfe9df] bg-[#f8fbf7] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#6a8870]">Patient</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setPatientType("new")} className={`rounded-xl border p-3 text-left ${patientType==="new"?"border-[#7ca786] bg-white shadow-sm":"border-[#dfe9df] bg-transparent"}`}><b className="text-sm">New Patient</b><span className="mt-1 block text-[10px] text-slate-500">First visit</span></button><button onClick={()=>setPatientType("existing")} className={`rounded-xl border p-3 text-left ${patientType==="existing"?"border-[#7ca786] bg-white shadow-sm":"border-[#dfe9df] bg-transparent"}`}><b className="text-sm">Existing Patient</b><span className="mt-1 block text-[10px] text-slate-500">Already registered</span></button></div></div>
 <div className="rounded-2xl border border-[#dfe9df] bg-[#f8fbf7] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#6a8870]">Consultant</p><select value={doctorId} onChange={e=>setDoctorId(e.target.value)} className="mt-3 w-full rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm font-bold"><option value="">Select consultant</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name} · {d.department?.name||"Department"}</option>)}</select></div>
 <div className="rounded-2xl border border-[#dfe9df] bg-[#f8fbf7] p-5 lg:col-span-2"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#6a8870]">Date & time</p><p className="mt-1 text-xs text-slate-500">Choose a 5-minute reception slot.</p></div><input type="date" value={date} onChange={e=>{setDate(e.target.value);setTime("")}} className="rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm"/></div><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-6">{slots(date).map(s=><button key={s} onClick={()=>setTime(s)} className={`rounded-xl border px-2 py-2.5 text-xs font-bold ${time===s?"border-[#173f36] bg-[#173f36] text-white":"border-[#dce7dd] bg-white text-[#4e665e] hover:bg-[#eef6ef]"}`}>{s}</button>)}</div></div>
 <div className="rounded-2xl border border-[#dfe9df] bg-[#f8fbf7] p-5 lg:col-span-2"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#6a8870]">Patient details</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full Name *" className="rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm"/><div><input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" maxLength={10} placeholder="Mobile Number (optional)" className="w-full rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm"/><p className="mt-1 text-[9px] text-slate-400">Enter 10 digits only if available.</p></div>{patientType==="new"&&<input value={dob} onChange={e=>setDob(e.target.value)} type="date" className="rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm"/>}<select value={gender} onChange={e=>setGender(e.target.value)} className="rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm"><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for visit / brief complaint" className="min-h-24 rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm sm:col-span-2"/></div></div></div><button disabled={saving} onClick={book} className="mt-6 w-full rounded-2xl bg-[#173f36] px-6 py-4 text-sm font-black text-white shadow-lg transition hover:bg-[#12352e] disabled:opacity-60">{saving?"Booking…":"Confirm Appointment"}</button></section>
 :<section className="mt-5"><div className="rounded-2xl border border-white/80 bg-white/92 p-4 shadow-sm backdrop-blur-xl"><div className="flex flex-col gap-3 lg:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient, mobile, appointment no. or consultant" className="flex-1 rounded-xl border border-[#d6e2d7] bg-[#f8fbf7] px-4 py-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#d6e2d7] bg-white px-4 py-3 text-sm lg:w-48"><option value="ALL">All Status</option><option value="SCHEDULED">Scheduled</option><option value="CHECKED_IN">Checked-in</option><option value="OPD_REGISTERED">OPD Registered</option><option value="CANCELLED">Cancelled</option></select><button onClick={load} className="rounded-xl border border-[#cddfd0] bg-[#edf6ee] px-4 py-3 text-xs font-black text-[#456c50]">↻ Refresh</button></div></div>{loading?<p className="mt-4 rounded-2xl bg-white p-8 text-sm">Loading appointments…</p>:<div className="mt-4 space-y-3">{filtered.length?filtered.map(a=><div key={a.id} className="rounded-2xl border border-white/80 bg-white/92 p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#edf6ee] px-2.5 py-1 text-[9px] font-black uppercase tracking-wide text-[#4d7659]">{a.status.replaceAll("_"," ")}</span><span className="text-[9px] font-black uppercase tracking-[.15em] text-[#789080]">{a.appointmentDate} · {a.appointmentTime}</span></div><h3 className="mt-2 text-lg font-black text-[#173b35]">{a.patientName}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{a.appointmentNo} · {a.mobile||"No mobile provided"}</p><p className="mt-1 text-xs font-bold text-slate-600">{a.doctorName} · {a.departmentName||"Department"}{a.opdVisitId?` · OPD Visit #${a.opdVisitId}`:""}</p></div><div className="flex flex-wrap gap-2">{a.status==="SCHEDULED"&&<><button onClick={()=>checkIn(a.id)} className="rounded-xl bg-[#173f36] px-4 py-2.5 text-xs font-black text-white">Check-in Patient</button><button onClick={()=>cancel(a.id)} className="rounded-xl border border-red-200 bg-white px-4 py-2.5 text-xs font-black text-red-700">Cancel</button></>}{a.status==="CHECKED_IN"&&<button onClick={()=>{setRegistering(a);setAadhaar("");setError("")}} className="rounded-xl bg-[#3973a2] px-4 py-2.5 text-xs font-black text-white">Register for OPD</button>}{a.status==="OPD_REGISTERED"&&<span className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-black text-emerald-700">Token generated · Queue linked</span>}</div></div></div>):<div className="rounded-2xl bg-white p-10 text-center text-sm font-semibold text-slate-500">No appointments found.</div>}</div>}</section>}
 {registering&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#10241e]/55 p-5 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[2rem] border border-[#cddfce] bg-[#f8fbf7] p-7 shadow-2xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#66846b]">OPD Registration</p><h2 className="mt-2 text-2xl font-black text-[#173b35]">{registering.patientName}</h2><div className="mt-5 grid gap-3 rounded-2xl border border-[#dce7dd] bg-white p-4 text-sm"><div><b>Department:</b> {registering.departmentName||"—"}</div><div><b>Consultant:</b> {registering.doctorName}</div><div><b>Appointment:</b> {registering.appointmentDate} · {registering.appointmentTime}</div><div><b>Type:</b> {registering.patientType}</div></div>{registering.patientType==="NEW"&&<div className="mt-5"><label className="text-xs font-black text-[#173b35]">Aadhaar Number <span className="text-red-600">*</span></label><input value={aadhaar} onChange={e=>setAadhaar(e.target.value.replace(/\D/g,"").slice(0,12))} inputMode="numeric" maxLength={12} placeholder="Enter 12-digit Aadhaar number" className="mt-2 w-full rounded-xl border border-[#d6e2d7] bg-white px-4 py-3"/><p className="mt-1 text-[10px] text-slate-500">Aadhaar is captured only for a new patient at OPD registration.</p></div>}<div className="mt-6 flex gap-3"><button onClick={()=>setRegistering(null)} className="flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-black text-slate-600">Cancel</button><button disabled={saving} onClick={registerOPD} className="flex-1 rounded-xl bg-[#173f36] px-4 py-3 text-xs font-black text-white disabled:opacity-60">{saving?"Registering…":"Register OPD & Generate Token"}</button></div></div></div>}
 </div></main>
}
