"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Doctor={id:number;name:string;qualification?:string|null;departmentId?:number|null;department?:{id:number;name:string;code:string}|null};
type Appointment={id:number;appointmentNo:string;patientType:string;patientName:string;mobile:string;dob?:string|null;gender?:string|null;reason?:string|null;departmentId?:number|null;departmentName?:string|null;doctorId?:number|null;doctorName:string;appointmentDate:string;appointmentTime:string;source:string;status:string;opdVisitId?:number|null;patientId?:number|null};
function slots(date:string){if(!date)return[];const m=Number(date.slice(5,7));const start=m>=4&&m<=9?8:9;const out:string[]=[];for(let x=start*60;x<=15*60;x+=5){const h=Math.floor(x/60),min=x%60,s=h>=12?"PM":"AM";out.push(`${h%12||12}:${String(min).padStart(2,"0")} ${s}`)}return out}

export default function ReceptionAppointments(){
 const[tab,setTab]=useState<"book"|"list">("book"),[patientType,setPatientType]=useState<"new"|"existing">("new"),[doctors,setDoctors]=useState<Doctor[]>([]),[doctorId,setDoctorId]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[name,setName]=useState(""),[mobile,setMobile]=useState(""),[dob,setDob]=useState(""),[gender,setGender]=useState(""),[reason,setReason]=useState(""),[appointments,setAppointments]=useState<Appointment[]>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[error,setError]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[registering,setRegistering]=useState<Appointment|null>(null),[aadhaar,setAadhaar]=useState("");
 useEffect(()=>{fetch("/api/doctors",{cache:"no-store"}).then(r=>r.json()).then(d=>setDoctors(Array.isArray(d)?d:[])).catch(()=>setError("Unable to load consultants."));load()},[]);
 async function load(){try{const r=await fetch("/api/appointments",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to load appointments");setAppointments(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load appointments")}finally{setLoading(false)}}
 const selectedDoctor=doctors.find(d=>String(d.id)===doctorId);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return appointments.filter(a=>(status==="ALL"||a.status===status)&&(!q||`${a.patientName} ${a.mobile} ${a.appointmentNo}`.toLowerCase().includes(q))).sort((a,b)=>`${a.appointmentDate} ${a.appointmentTime}`.localeCompare(`${b.appointmentDate} ${b.appointmentTime}`))},[appointments,query,status]);
 async function book(){if(!doctorId||!date||!time||!name.trim()||!mobile.trim()||(patientType==="new"&&!dob)){setError("Please complete patient, consultant, date and time details.");return}setSaving(true);setError("");try{const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientType,patientName:name,mobile,dob,gender,reason,doctorId:Number(doctorId),doctorName:selectedDoctor?.name,departmentId:selectedDoctor?.departmentId,departmentName:selectedDoctor?.department?.name,appointmentDate:date,appointmentTime:time,source:"RECEPTION"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to book appointment");setAppointments(x=>[...x,d]);setTab("list");setName("");setMobile("");setDob("");setGender("");setReason("");setTime("")}catch(e){setError(e instanceof Error?e.message:"Unable to book appointment")}finally{setSaving(false)}}
 async function checkIn(id:number){setError("");try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"CHECKED_IN"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to check-in");setAppointments(x=>x.map(a=>a.id===id?d:a))}catch(e){setError(e instanceof Error?e.message:"Unable to check-in patient")}}
 async function registerOPD(){if(!registering)return;if(registering.patientType==="NEW"&&aadhaar.replace(/\D/g,"").length!==12){setError("Aadhaar number is required for a new patient and must contain exactly 12 digits.");return}setSaving(true);setError("");try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:registering.id,action:"REGISTER_OPD",aadhaarNumber:aadhaar})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to register OPD visit");setAppointments(x=>x.map(a=>a.id===registering.id?d.appointment:a));setRegistering(null);setAadhaar("");setTab("list")}catch(e){setError(e instanceof Error?e.message:"Unable to register OPD visit")}finally{setSaving(false)}}
 async function cancel(id:number){try{const r=await fetch("/api/appointments",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:"CANCELLED"})});const d=await r.json();if(!r.ok)throw Error(d?.error||"Unable to cancel");setAppointments(x=>x.map(a=>a.id===id?d:a))}catch(e){setError(e instanceof Error?e.message:"Unable to cancel appointment")}}
 return <main className="min-h-screen bg-[#e8d6b3] text-[#10233f]">
 <header className="border-b border-[#ded5c5] bg-[#fbf8f1]/95 px-5 py-4 shadow-sm sm:px-8"><div className="mx-auto flex max-w-[1250px] items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#9a7434]">SAMS · Reception</p><h1 className="font-serif text-2xl font-semibold text-[#082b61]">Appointments</h1></div><Link href="/reception" className="rounded-xl border border-[#d6dce7] bg-white px-4 py-2 text-xs font-black text-[#082b61]">← Back to Reception</Link></div></header>
 <div className="mx-auto max-w-[1250px] px-5 py-8 sm:px-8">
 <div className="mb-6 flex gap-2 rounded-2xl border border-[#d6bd84]/70 bg-[#fbf8f1] p-2"><button onClick={()=>setTab("book")} className={`flex-1 rounded-xl px-5 py-3 text-sm font-black ${tab==="book"?"bg-[#082b61] text-[#f3dfad]":"text-[#52627a]"}`}>Book Appointment</button><button onClick={()=>{setTab("list");load()}} className={`flex-1 rounded-xl px-5 py-3 text-sm font-black ${tab==="list"?"bg-[#082b61] text-[#f3dfad]":"text-[#52627a]"}`}>See Appointments</button></div>
 {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 {tab==="book"?<section className="rounded-[2rem] border border-[#d6bd84]/70 bg-[#fbf8f1] p-6 shadow-[0_20px_55px_rgba(70,48,16,.10)] sm:p-9"><div className="mb-7 text-center"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#9a7434]">Reception Appointment Desk</p><h2 className="mt-2 font-serif text-4xl font-medium text-[#082b61]">Book Your Appointment</h2><p className="mt-2 text-sm text-[#52627a]">Same booking experience as the public-facing appointment page.</p></div><div className="grid gap-6 lg:grid-cols-2">
 <div className="rounded-3xl border border-[#ded5c5] bg-white p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#9a7434]">01 · Patient Type</p><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>setPatientType("new")} className={`rounded-2xl border p-4 text-left ${patientType==="new"?"border-[#d6b46a] bg-[#f7ecd2]":"border-[#ded5c5]"}`}><b>👤 New Patient</b><span className="mt-1 block text-xs text-slate-500">First visit</span></button><button onClick={()=>setPatientType("existing")} className={`rounded-2xl border p-4 text-left ${patientType==="existing"?"border-[#d6b46a] bg-[#f7ecd2]":"border-[#ded5c5]"}`}><b>↩ Existing Patient</b><span className="mt-1 block text-xs text-slate-500">Already registered</span></button></div></div>
 <div className="rounded-3xl border border-[#ded5c5] bg-white p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#9a7434]">02 · Consultant</p><select value={doctorId} onChange={e=>setDoctorId(e.target.value)} className="mt-4 w-full rounded-xl border border-[#ded5c5] px-4 py-3 text-sm font-bold"><option value="">Select consultant</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.name} · {d.department?.name||"Department"}</option>)}</select></div>
 <div className="rounded-3xl border border-[#ded5c5] bg-white p-6 lg:col-span-2"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#9a7434]">03 · Date & Time</p><input type="date" value={date} onChange={e=>{setDate(e.target.value);setTime("")}} className="mt-4 w-full rounded-xl border border-[#ded5c5] px-4 py-3"/><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-6">{slots(date).map(s=><button key={s} onClick={()=>setTime(s)} className={`rounded-xl border px-2 py-2 text-xs font-bold ${time===s?"border-[#d6b46a] bg-[#082b61] text-[#f3dfad]":"border-[#ded5c5] bg-white"}`}>{s}</button>)}</div></div>
 <div className="rounded-3xl border border-[#ded5c5] bg-white p-6 lg:col-span-2"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#9a7434]">04 · Patient Details</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full Name *" className="rounded-xl border border-[#ded5c5] px-4 py-3"/><input value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="Mobile Number *" className="rounded-xl border border-[#ded5c5] px-4 py-3"/>{patientType==="new"&&<input value={dob} onChange={e=>setDob(e.target.value)} type="date" className="rounded-xl border border-[#ded5c5] px-4 py-3"/>}<select value={gender} onChange={e=>setGender(e.target.value)} className="rounded-xl border border-[#ded5c5] px-4 py-3"><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for visit / brief complaint" className="rounded-xl border border-[#ded5c5] px-4 py-3 sm:col-span-2"/></div></div></div><button disabled={saving} onClick={book} className="mt-7 w-full rounded-2xl bg-[#082b61] px-6 py-4 text-sm font-black text-[#f3dfad] shadow-lg disabled:opacity-60">{saving?"Booking…":"Confirm Appointment"}</button></section>
 :<section><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient, mobile or appointment no." className="flex-1 rounded-xl border border-[#ded5c5] bg-white px-4 py-3 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#ded5c5] bg-white px-4 py-3 text-sm"><option value="ALL">All Status</option><option value="SCHEDULED">Scheduled</option><option value="CHECKED_IN">Checked-in</option><option value="OPD_REGISTERED">OPD Registered</option><option value="CANCELLED">Cancelled</option></select></div>{loading?<p className="rounded-2xl bg-white p-8 text-sm">Loading appointments…</p>:<div className="space-y-3">{filtered.length?filtered.map(a=><div key={a.id} className="rounded-2xl border border-[#d6bd84]/70 bg-[#fbf8f1] p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#9a7434]">{a.appointmentDate} · {a.appointmentTime} · {a.source}</p><h3 className="mt-1 text-lg font-black text-[#082b61]">{a.patientName}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{a.appointmentNo} · {a.mobile} · {a.doctorName} · {a.departmentName||"Department"}</p><p className="mt-1 text-xs font-bold text-slate-600">Status: {a.status}{a.opdVisitId?` · OPD Visit #${a.opdVisitId}`:""}</p></div><div className="flex flex-wrap gap-2">{a.status==="SCHEDULED"&&<><button onClick={()=>checkIn(a.id)} className="rounded-xl bg-[#082b61] px-4 py-2.5 text-xs font-black text-[#f3dfad]">Check-in Patient</button><button onClick={()=>cancel(a.id)} className="rounded-xl border border-red-200 bg-white px-4 py-2.5 text-xs font-black text-red-700">Cancel</button></>}{a.status==="CHECKED_IN"&&<button onClick={()=>{setRegistering(a);setAadhaar("");setError("")}} className="rounded-xl bg-[#0b63ce] px-4 py-2.5 text-xs font-black text-white">Register for OPD</button>}{a.status==="OPD_REGISTERED"&&<span className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-xs font-black text-emerald-700">Token generated · Queue linked</span>}</div></div></div>):<div className="rounded-2xl bg-white p-10 text-center text-sm font-semibold text-slate-500">No appointments found.</div>}</div>}</section>}
 {registering&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#071525]/60 p-5 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[2rem] border border-[#d6bd84] bg-[#fbf8f1] p-7 shadow-2xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#9a7434]">OPD Registration</p><h2 className="mt-2 text-2xl font-black text-[#082b61]">{registering.patientName}</h2><div className="mt-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-sm"><div><b>Department:</b> {registering.departmentName||"—"}</div><div><b>Consultant:</b> {registering.doctorName}</div><div><b>Appointment:</b> {registering.appointmentDate} · {registering.appointmentTime}</div><div><b>Type:</b> {registering.patientType}</div></div>{registering.patientType==="NEW"&&<div className="mt-5"><label className="text-xs font-black text-[#082b61]">Aadhaar Number <span className="text-red-600">*</span></label><input value={aadhaar} onChange={e=>setAadhaar(e.target.value.replace(/\D/g,"").slice(0,12))} inputMode="numeric" maxLength={12} placeholder="Enter 12-digit Aadhaar number" className="mt-2 w-full rounded-xl border border-[#ded5c5] bg-white px-4 py-3"/><p className="mt-1 text-[10px] text-slate-500">Aadhaar is captured only for a new patient at OPD registration.</p></div>}<div className="mt-6 flex gap-3"><button onClick={()=>setRegistering(null)} className="flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-black text-slate-600">Cancel</button><button disabled={saving} onClick={registerOPD} className="flex-1 rounded-xl bg-[#082b61] px-4 py-3 text-xs font-black text-[#f3dfad] disabled:opacity-60">{saving?"Registering…":"Register OPD & Generate Token"}</button></div></div></div>}
 </div></main>
}
