import { prisma } from "@/lib/prisma";
import PrintOnLoad from "@/components/PrintOnLoad";
import { notFound } from "next/navigation";

const dt = (value: Date | null) => value ? `${value.toLocaleDateString("en-IN")} · ${value.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}` : "—";

export default async function InvestigationReportPrint({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const order = await prisma.investigationOrder.findUnique({
    where: { id: Number(id) },
    include: { master: true, opdVisit: { include: { patient: true, departmentMaster: true, doctor: true } } },
  });
  if (!order || !["VERIFIED", "PUBLISHED"].includes(order.status)) return notFound();

  const patient = order.opdVisit.patient;
  const master = order.master;
  const visit = order.opdVisit;
  const reference = patient.gender?.toLowerCase().startsWith("m") ? (master?.maleReferenceRange || master?.referenceRange) : patient.gender?.toLowerCase().startsWith("f") ? (master?.femaleReferenceRange || master?.referenceRange) : master?.referenceRange;

  return <>
    <PrintOnLoad />
    <main className="sheet">
      <div className="watermark" aria-hidden="true"><img src="/serawat-logo.png" alt="" /></div>
      <header className="header">
        <div className="brand"><img src="/serawat-logo.png" alt="Serawat logo" /><div><div className="hospital">SERAWAT ADVANCED</div><div className="hospital second">MULTISPECIALITY JOINT &amp; SPINE CENTRE</div><div className="title">LABORATORY INVESTIGATION REPORT</div></div></div>
        <div className="reportNo"><span>Accession No.</span><b>{order.accessionNumber || `LAB-${order.id}`}</b><small>Order #{order.id}</small></div>
      </header>

      <section className="patient">
        <div><span>Patient</span><b>{patient.firstName} {patient.lastName}</b></div>
        <div><span>Patient ID</span><b>{patient.patientId}</b></div>
        <div><span>Age / Sex</span><b>{patient.dateOfBirth ? `${new Date().getFullYear() - patient.dateOfBirth.getFullYear()} / ${patient.gender || "—"}` : `— / ${patient.gender || "—"}`}</b></div>
        <div><span>Mobile</span><b>{patient.phone || "—"}</b></div>
        <div><span>OPD Visit</span><b>#{visit.id} · Token #{visit.tokenNumber}</b></div>
        <div><span>Department</span><b>{visit.departmentMaster?.name || "—"}</b></div>
        <div><span>Consultant</span><b>{visit.doctor?.name || "—"}</b></div>
        <div><span>Reported</span><b>{dt(order.reportedAt)}</b></div>
      </section>

      <section className="investigationHead">
        <div><span>Investigation</span><h1>{order.investigation}</h1><p>{master?.code || "—"} · {master?.category || "Laboratory"}</p></div>
        <div className="status"><span>Report Status</span><b>{order.status === "PUBLISHED" ? "PUBLISHED" : "VERIFIED"}</b></div>
      </section>

      <section className="specimen">
        <div><span>Specimen</span><b>{order.specimen || master?.specimen || "—"}</b></div>
        <div><span>Method</span><b>{master?.method || "—"}</b></div>
        <div><span>Unit</span><b>{master?.unit || "—"}</b></div>
        <div><span>Reference Range</span><b>{reference || "—"}</b></div>
      </section>

      <section className="resultSection">
        <div className="sectionTitle">RESULT / FINDINGS</div>
        <div className="result">{order.reportText || "No result recorded."}</div>
        {(order.abnormalFlag || order.criticalFlag) && <div className="flags">{order.criticalFlag && <b>CRITICAL RESULT</b>}{order.abnormalFlag && <b>ABNORMAL RESULT</b>}</div>}
      </section>

      <section className="verification">
        <div><span>Verified By</span><b>{order.verifiedBy || "Authorized Laboratory User"}</b></div>
        <div><span>Verified At</span><b>{dt(order.verifiedAt)}</b></div>
        <div><span>Published At</span><b>{dt(order.publishedAt)}</b></div>
      </section>

      <footer>
        <div>Electronically generated by SAMS after laboratory verification.</div>
        <div>Patient ID: {patient.patientId} · Accession: {order.accessionNumber || `LAB-${order.id}`}</div>
      </footer>
    </main>
    <style>{`@page{size:A4 portrait;margin:0}html,body{margin:0!important;padding:0!important;background:#fff!important}.sheet{box-sizing:border-box;position:relative;width:210mm;min-height:297mm;margin:0;padding:8mm 10mm 7mm;color:#172033;background:#fff;font-family:Arial,Helvetica,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.watermark{position:absolute;z-index:0;left:50%;top:52%;transform:translate(-50%,-50%);width:85mm;height:85mm;opacity:.045;pointer-events:none}.watermark img{width:100%;height:100%;object-fit:contain}.header,.patient,.investigationHead,.specimen,.resultSection,.verification,footer{position:relative;z-index:1}.header{min-height:27mm;border-bottom:1.2px solid #183d70;display:flex;align-items:center;justify-content:space-between;gap:7mm}.brand{display:flex;align-items:center;gap:4mm;min-width:0}.brand img{width:17mm;height:17mm;object-fit:contain}.hospital{font-family:Georgia,'Times New Roman',serif;font-size:17px;font-weight:800;letter-spacing:.035em;line-height:1.08;color:#082b61}.hospital.second{font-size:15px;margin-top:1mm}.title{font-size:9px;font-weight:900;letter-spacing:.16em;color:#64748b;margin-top:3mm}.reportNo{min-width:34mm;text-align:right;border:1px solid #d7c08a;border-radius:2mm;padding:2.5mm 3mm;color:#082b61}.reportNo span,.patient span,.investigationHead span,.specimen span,.verification span{display:block;font-size:6.5px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#64748b}.reportNo b{display:block;font-size:8.5px;margin-top:1mm}.reportNo small{display:block;font-size:7px;color:#64748b;margin-top:1mm}.patient{display:grid;grid-template-columns:repeat(4,1fr);gap:3.5mm 5mm;padding:4mm 0;border-bottom:1px solid #cbd5e1}.patient b,.specimen b,.verification b{display:block;font-size:8.5px;margin-top:1mm}.investigationHead{display:flex;justify-content:space-between;align-items:center;gap:8mm;padding:5mm 0;border-bottom:1px solid #cbd5e1}.investigationHead h1{margin:1.5mm 0 0;font-size:18px;line-height:1.15;color:#082b61}.investigationHead p{margin:1mm 0 0;font-size:8px;color:#64748b;font-weight:700}.status{text-align:right;border:1px solid #a7d9b8;background:#f1fbf4;border-radius:2mm;padding:2.5mm 4mm}.status b{display:block;margin-top:1mm;font-size:9px;color:#167447}.specimen{display:grid;grid-template-columns:1fr 1fr 1fr 1.5fr;gap:4mm;padding:4mm 0;border-bottom:1px solid #d7dee8}.resultSection{margin-top:5mm}.sectionTitle{font-size:8px;font-weight:900;letter-spacing:.14em;color:#082b61;padding-bottom:2mm;border-bottom:1px solid #183d70}.result{margin-top:4mm;min-height:55mm;border:1px solid #b9c6d5;border-radius:2mm;padding:5mm;font-size:10px;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere}.flags{display:flex;gap:3mm;margin-top:3mm}.flags b{font-size:7px;color:#a11b1b;border:1px solid #e3a8a8;background:#fff5f5;padding:1.5mm 2.5mm;border-radius:2mm}.verification{display:grid;grid-template-columns:1fr 1fr 1fr;gap:5mm;margin-top:7mm;padding-top:4mm;border-top:1px solid #cbd5e1}.verification b{font-size:8px;color:#082b61}footer{display:flex;justify-content:space-between;gap:8mm;margin-top:7mm;padding-top:3mm;border-top:1px solid #e2e8f0;font-size:6.5px;font-weight:700;color:#64748b} @media print{html,body{width:210mm!important;min-height:297mm!important;background:#fff!important}.sheet{width:210mm!important;min-height:297mm!important;margin:0!important;box-shadow:none!important}.resultSection,.verification,.footer{break-inside:avoid;page-break-inside:avoid}}`}</style>
  </>;
}
