import { prisma } from "../lib/prisma";

type Seed = {
  code: string;
  name: string;
  category: string;
  department: string;
  specimen: string;
  sms: number;
  corp: number;
};

type Row = [
  string,
  string,
  string,
  string,
  string,
  number,
  number
];

// Quaternary expansion: additional subspecialty investigations not intended
// to replace the earlier master/expansion batches. SAMS rate = 65% from the
// SMS benchmark toward the corporate benchmark, rounded to nearest rupee.
const rows: Row[] = [
  // Pulmonology / respiratory
  ["Q4_PFT_SIMPLE_SPIROMETRY","Spirometry with Flow Volume Loop","Pulmonary","Pulmonology","Breath",500,800],
  ["Q4_PFT_LUNG_VOLUMES","Pulmonary Function Test with Lung Volumes","Pulmonary","Pulmonology","Breath",900,1440],
  ["Q4_PFT_DLCO","DLCO / Diffusion Capacity","Pulmonary","Pulmonology","Breath",900,1440],
  ["Q4_PFT_FULL","Complete Pulmonary Function Test","Pulmonary","Pulmonology","Breath",1200,1920],
  ["Q4_PFT_BRONCHODILATOR_REVERSIBILITY","Bronchodilator Reversibility Test","Pulmonary","Pulmonology","Breath",600,960],
  ["Q4_PFT_MIP_MEP","Maximum Inspiratory and Expiratory Pressure","Pulmonary","Pulmonology","Breath",700,1120],
  ["Q4_PFT_MVV","Maximum Voluntary Ventilation","Pulmonary","Pulmonology","Breath",500,800],
  ["Q4_PFT_SIX_MIN_WALK","Six Minute Walk Test with SpO2","Pulmonary","Pulmonology","Physiologic test",400,640],
  ["Q4_EXHALED_NO","Exhaled Nitric Oxide","Pulmonary","Pulmonology","Exhaled breath",1000,1600],
  ["Q4_ALLERGY_SKIN_PRICK","Allergy Skin Prick Test Panel","Allergy","Allergy & Immunology","Skin",1200,1920],
  ["Q4_TOTAL_IGE","Total IgE Quantitation","Allergy","Allergy & Immunology","Serum",400,640],
  ["Q4_SPECIFIC_IGE_PANEL","Specific IgE Allergy Panel","Allergy","Allergy & Immunology","Serum",1200,1920],
  // Gastroenterology
  ["Q4_H_PYLORI_STOOL_ANTIGEN","H. pylori Stool Antigen","Gastroenterology","Gastroenterology","Stool",500,800],
  ["Q4_H_PYLORI_UREA_BREATH","H. pylori Urea Breath Test","Gastroenterology","Gastroenterology","Breath",1200,1920],
  ["Q4_FECAL_CALPROTECTIN","Fecal Calprotectin","Gastroenterology","Gastroenterology","Stool",900,1440],
  ["Q4_FECAL_ELASTASE","Fecal Pancreatic Elastase","Gastroenterology","Gastroenterology","Stool",1000,1600],
  ["Q4_FECAL_OCCULT_BLOOD_IMMUNO","Fecal Occult Blood Immunochemical Test","Gastroenterology","Gastroenterology","Stool",300,480],
  ["Q4_C13_UREA_BREATH","C13 Urea Breath Test","Gastroenterology","Gastroenterology","Breath",1200,1920],
  ["Q4_SERUM_GASTRIN","Serum Gastrin","Gastroenterology","Gastroenterology","Serum",700,1120],
  ["Q4_SERUM_CHROMOGRANIN_A","Chromogranin A","Gastroenterology","Gastroenterology","Serum",1800,2880],
  ["Q4_CEA","Carcinoembryonic Antigen","Tumor Markers","Gastroenterology","Serum",500,800],
  ["Q4_CA19_9","CA 19-9","Tumor Markers","Gastroenterology","Serum",600,960],
  ["Q4_CA72_4","CA 72-4","Tumor Markers","Gastroenterology","Serum",700,1120],
  // Hepatology
  ["Q4_HBV_DNA_QUANT","HBV DNA Quantitative PCR","Molecular Diagnostics","Hepatology","Plasma",1800,2880],
  ["Q4_HCV_RNA_QUANT","HCV RNA Quantitative PCR","Molecular Diagnostics","Hepatology","Plasma",1800,2880],
  ["Q4_HBV_GENOTYPE","HBV Genotyping","Molecular Diagnostics","Hepatology","Plasma",2500,4000],
  ["Q4_HCV_GENOTYPE","HCV Genotyping","Molecular Diagnostics","Hepatology","Plasma",2500,4000],
  ["Q4_HDV_RNA","HDV RNA PCR","Molecular Diagnostics","Hepatology","Plasma",2200,3520],
  ["Q4_HEV_RNA","HEV RNA PCR","Molecular Diagnostics","Hepatology","Plasma",2200,3520],
  ["Q4_LIVER_FIBROSCAN","Transient Elastography / FibroScan","Hepatology","Hepatology","Imaging",1800,2880],
  ["Q4_LIVER_STIFFNESS_2D_SWE","2D Shear Wave Elastography Liver","Hepatology","Radiology","Imaging",1800,2880],
  // Endocrinology / metabolic
  ["Q4_INSULIN_FASTING","Fasting Insulin","Endocrinology","Endocrinology","Serum",300,480],
  ["Q4_C_PEPTIDE_FASTING","Fasting C-Peptide","Endocrinology","Endocrinology","Serum",500,800],
  ["Q4_C_PEPTIDE_STIMULATED","Stimulated C-Peptide","Endocrinology","Endocrinology","Serum",600,960],
  ["Q4_HOMA_IR","HOMA-IR","Endocrinology","Endocrinology","Serum",400,640],
  ["Q4_HBA1C_HPLC","HbA1c by HPLC","Endocrinology","Endocrinology","EDTA blood",450,720],
  ["Q4_FRUCTOSAMINE","Fructosamine","Endocrinology","Endocrinology","Serum",350,560],
  ["Q4_GROWTH_HORMONE","Growth Hormone","Endocrinology","Endocrinology","Serum",700,1120],
  ["Q4_IGF1","IGF-1","Endocrinology","Endocrinology","Serum",900,1440],
  ["Q4_IGFBP3","IGFBP-3","Endocrinology","Endocrinology","Serum",900,1440],
  ["Q4_PROLACTIN_POOL","Prolactin Pooled Sample","Endocrinology","Endocrinology","Serum",500,800],
  ["Q4_CORTISOL_8AM","8 AM Serum Cortisol","Endocrinology","Endocrinology","Serum",400,640],
  ["Q4_CORTISOL_24H_URINE","24 Hour Urinary Free Cortisol","Endocrinology","Endocrinology","24h urine",900,1440],
  ["Q4_DEXAMETHASONE_SUPPRESSION","Dexamethasone Suppression Test","Endocrinology","Endocrinology","Serum",900,1440],
  ["Q4_ACTH","ACTH","Endocrinology","Endocrinology","EDTA plasma",700,1120],
  ["Q4_RENIN_PLASMA","Plasma Renin Activity","Endocrinology","Endocrinology","EDTA plasma",1000,1600],
  ["Q4_ALDOSTERONE","Aldosterone","Endocrinology","Endocrinology","Serum",700,1120],
  ["Q4_ALDOSTERONE_RENIN_RATIO","Aldosterone Renin Ratio","Endocrinology","Endocrinology","Serum/plasma",1200,1920],
  ["Q4_METANEPHRINES_PLASMA","Plasma Free Metanephrines","Endocrinology","Endocrinology","Plasma",1800,2880],
  ["Q4_METANEPHRINES_URINE","Urinary Metanephrines 24 Hour","Endocrinology","Endocrinology","24h urine",1600,2560],
  ["Q4_5HIAA_URINE","Urinary 5-HIAA 24 Hour","Endocrinology","Endocrinology","24h urine",1200,1920],
  // Rheumatology / autoimmune
  ["Q4_ANA_IF","ANA by Immunofluorescence","Autoimmunity","Rheumatology","Serum",600,960],
  ["Q4_ANA_PROFILE","ANA Profile","Autoimmunity","Rheumatology","Serum",1800,2880],
  ["Q4_ENA_PROFILE","ENA Profile","Autoimmunity","Rheumatology","Serum",1800,2880],
  ["Q4_DS_DNA_CRITHIDIA","Anti-dsDNA by Crithidia","Autoimmunity","Rheumatology","Serum",900,1440],
  ["Q4_C3_COMPLEMENT","Complement C3","Immunology","Rheumatology","Serum",500,800],
  ["Q4_C4_COMPLEMENT","Complement C4","Immunology","Rheumatology","Serum",500,800],
  ["Q4_CH50","Total Complement CH50","Immunology","Rheumatology","Serum",700,1120],
  ["Q4_ANTI_CCP","Anti-CCP Antibody","Autoimmunity","Rheumatology","Serum",700,1120],
  ["Q4_RHEUMATOID_FACTOR_QUANT","Quantitative Rheumatoid Factor","Autoimmunity","Rheumatology","Serum",400,640],
  ["Q4_HLA_B27_FLOW","HLA-B27 by Flow Cytometry","Immunology","Rheumatology","EDTA blood",1200,1920],
  ["Q4_HLA_B27_PCR","HLA-B27 by PCR","Molecular Diagnostics","Rheumatology","EDTA blood",1400,2240],
  ["Q4_ANTI_SCL70","Anti-Scl-70 Antibody","Autoimmunity","Rheumatology","Serum",700,1120],
  ["Q4_ANTI_CENTROMERE","Anti-Centromere Antibody","Autoimmunity","Rheumatology","Serum",700,1120],
  ["Q4_ANTI_JO1","Anti-Jo-1 Antibody","Autoimmunity","Rheumatology","Serum",700,1120],
  ["Q4_ANTI_MDA5","Anti-MDA5 Antibody","Autoimmunity","Rheumatology","Serum",1200,1920],
  ["Q4_ANTI_SRP","Anti-SRP Antibody","Autoimmunity","Rheumatology","Serum",1200,1920],
  ["Q4_ANTI_RO52","Anti-Ro52 Antibody","Autoimmunity","Rheumatology","Serum",700,1120],
  // Nephrology / renal
  ["Q4_URINE_ALBUMIN_24H","24 Hour Urine Albumin","Clinical Pathology","Nephrology","24h urine",300,480],
  ["Q4_URINE_PROTEIN_24H","24 Hour Urine Protein","Clinical Pathology","Nephrology","24h urine",300,480],
  ["Q4_URINE_PROTEIN_CREATININE","Urine Protein Creatinine Ratio","Clinical Pathology","Nephrology","Urine",350,560],
  ["Q4_URINE_ALBUMIN_CREATININE","Urine Albumin Creatinine Ratio","Clinical Pathology","Nephrology","Urine",350,560],
  ["Q4_CYSTATIN_C","Cystatin C","Biochemistry","Nephrology","Serum",700,1120],
  ["Q4_EGFR_CYSTATIN","eGFR by Cystatin C","Biochemistry","Nephrology","Serum",700,1120],
  ["Q4_FRACTIONAL_SODIUM_EXCRETION","Fractional Excretion of Sodium","Biochemistry","Nephrology","Serum + urine",500,800],
  ["Q4_URINE_ELECTROLYTES","Urine Sodium Potassium Chloride","Biochemistry","Nephrology","Urine",500,800],
  ["Q4_URINE_OSMOLALITY","Urine Osmolality","Biochemistry","Nephrology","Urine",400,640],
  ["Q4_SERUM_OSMOLALITY","Serum Osmolality","Biochemistry","Nephrology","Serum",400,640],
  // Infectious disease / microbiology
  ["Q4_BLOOD_CULTURE_AEROBIC","Blood Culture Aerobic","Microbiology","Microbiology","Blood",600,960],
  ["Q4_BLOOD_CULTURE_ANAEROBIC","Blood Culture Anaerobic","Microbiology","Microbiology","Blood",600,960],
  ["Q4_BLOOD_CULTURE_FUNGAL","Fungal Blood Culture","Microbiology","Microbiology","Blood",1000,1600],
  ["Q4_BLOOD_CULTURE_MYCOBACTERIAL","Mycobacterial Blood Culture","Microbiology","Microbiology","Blood",1200,1920],
  ["Q4_CSF_BACTERIAL_CULTURE","CSF Bacterial Culture","Microbiology","Microbiology","CSF",700,1120],
  ["Q4_CSF_FUNGAL_CULTURE","CSF Fungal Culture","Microbiology","Microbiology","CSF",900,1440],
  ["Q4_CSF_TB_PCR","CSF Mycobacterium tuberculosis PCR","Molecular Diagnostics","Microbiology","CSF",1200,1920],
  ["Q4_TB_CARTRIDGE_RESISTANCE","TB Molecular Detection with Rifampicin Resistance","Molecular Diagnostics","Microbiology","Sputum",1200,1920],
  ["Q4_TB_LPA_FIRST_LINE","TB Line Probe Assay First Line","Molecular Diagnostics","Microbiology","Sputum",2200,3520],
  ["Q4_TB_LPA_SECOND_LINE","TB Line Probe Assay Second Line","Molecular Diagnostics","Microbiology","Sputum",2500,4000],
  ["Q4_DENGUE_NS1","Dengue NS1 Antigen","Microbiology","Microbiology","Serum",400,640],
  ["Q4_DENGUE_IGG","Dengue IgG","Microbiology","Microbiology","Serum",350,560],
  ["Q4_DENGUE_IGM","Dengue IgM","Microbiology","Microbiology","Serum",350,560],
  ["Q4_CHIKUNGUNYA_IGM","Chikungunya IgM","Microbiology","Microbiology","Serum",400,640],
  ["Q4_CHIKUNGUNYA_PCR","Chikungunya PCR","Molecular Diagnostics","Microbiology","Serum",1200,1920],
  ["Q4_MALARIA_PCR","Malaria PCR","Molecular Diagnostics","Microbiology","EDTA blood",1200,1920],
  ["Q4_LEPTOSPIRA_PCR","Leptospira PCR","Molecular Diagnostics","Microbiology","Blood/urine",1200,1920],
  ["Q4_BRUCELLA_AGGLUTINATION","Brucella Agglutination Test","Microbiology","Microbiology","Serum",350,560],
  ["Q4_HIV_1_RNA_QUANT","HIV-1 RNA Quantitative PCR","Molecular Diagnostics","Microbiology","Plasma",1800,2880],
  ["Q4_HIV_GENOTYPING","HIV Genotypic Resistance Testing","Molecular Diagnostics","Microbiology","Plasma",5000,8000],
  // Molecular / genetics
  ["Q4_KARYOTYPE_BLOOD","Conventional Karyotyping Blood","Molecular Diagnostics","Genetics","EDTA blood",1800,2880],
  ["Q4_KARYOTYPE_BONE_MARROW","Bone Marrow Karyotyping","Molecular Diagnostics","Genetics","Bone marrow",2500,4000],
  ["Q4_FISH_BCR_ABL","FISH BCR-ABL1","Molecular Diagnostics","Genetics","EDTA blood",2500,4000],
  ["Q4_FISH_HER2","FISH HER2/ERBB2","Molecular Diagnostics","Oncology","Tissue",2500,4000],
  ["Q4_FISH_22Q11","FISH 22q11.2 Deletion","Molecular Diagnostics","Genetics","EDTA blood",2200,3520],
  ["Q4_FISH_DOWN_SYNDROME","FISH Trisomy 21 Rapid Test","Molecular Diagnostics","Genetics","Amniotic fluid/blood",2200,3520],
  ["Q4_CYTOGENETIC_MICROARRAY","Chromosomal Microarray","Molecular Diagnostics","Genetics","Blood",5000,8000],
  ["Q4_CFTR_COMMON_VARIANTS","CFTR Common Variant Panel","Molecular Diagnostics","Genetics","EDTA blood",3000,4800],
  ["Q4_FAMILIAL_HYPERCHOLESTEROLEMIA_PANEL","Familial Hypercholesterolemia Gene Panel","Molecular Diagnostics","Genetics","EDTA blood",4000,6400],
  ["Q4_THROMBOPHILIA_GENETIC_PANEL","Inherited Thrombophilia Genetic Panel","Molecular Diagnostics","Genetics","EDTA blood",3500,5600],
  ["Q4_BRCA1_BRCA2_FULL","BRCA1 and BRCA2 Comprehensive Testing","Molecular Diagnostics","Genetics","EDTA blood",5000,8000],
  ["Q4_LYNCH_PANEL","Lynch Syndrome Gene Panel","Molecular Diagnostics","Genetics","EDTA blood",5000,8000],
  ["Q4_DMD_DELETION_DUPLICATION","DMD Deletion/Duplication Analysis","Molecular Diagnostics","Genetics","EDTA blood",4500,7200],
  ["Q4_SMA_SMN1","Spinal Muscular Atrophy SMN1 Analysis","Molecular Diagnostics","Genetics","EDTA blood",3500,5600],
  ["Q4_FRAGILE_X","Fragile X Molecular Testing","Molecular Diagnostics","Genetics","EDTA blood",3500,5600],
  // Oncology / pathology
  ["Q4_PD_L1_IHC","PD-L1 Immunohistochemistry","Histopathology","Oncology","Tissue",1800,2880],
  ["Q4_KI67_IHC","Ki-67 Immunohistochemistry","Histopathology","Oncology","Tissue",1500,2400],
  ["Q4_ER_IHC","Estrogen Receptor Immunohistochemistry","Histopathology","Oncology","Tissue",1500,2400],
  ["Q4_PR_IHC","Progesterone Receptor Immunohistochemistry","Histopathology","Oncology","Tissue",1500,2400],
  ["Q4_HER2_IHC","HER2 Immunohistochemistry","Histopathology","Oncology","Tissue",1500,2400],
  ["Q4_P53_IHC","p53 Immunohistochemistry","Histopathology","Oncology","Tissue",1500,2400],
  ["Q4_MMR_IHC_PANEL","Mismatch Repair Protein IHC Panel","Histopathology","Oncology","Tissue",3500,5600],
  ["Q4_SOFT_TISSUE_SARCOMA_PANEL","Soft Tissue Sarcoma IHC Panel","Histopathology","Oncology","Tissue",4000,6400],
  ["Q4_LYMPHOMA_IHC_PANEL","Lymphoma Immunohistochemistry Panel","Histopathology","Hematopathology","Tissue",4500,7200],
  ["Q4_FLOW_LYMPHOMA_SCREEN","Flow Cytometry Lymphoma Screening","Neurophysiology","Hematopathology","EDTA blood",3500,5600],
  ["Q4_FLOW_LEUKEMIA_PANEL","Flow Cytometry Acute Leukemia Panel","Hematopathology","Hematopathology","Bone marrow/blood",4500,7200],
  ["Q4_FLOW_PNH","Flow Cytometry PNH Clone","Hematopathology","Hematopathology","EDTA blood",3500,5600],
  ["Q4_BCR_ABL_QUANT_PCR","BCR-ABL1 Quantitative PCR","Molecular Diagnostics","Hematopathology","EDTA blood",2200,3520],
  ["Q4_JAK2_V617F","JAK2 V617F Mutation","Molecular Diagnostics","Hematopathology","EDTA blood",1800,2880],
  ["Q4_CALR_MUTATION","CALR Mutation Analysis","Molecular Diagnostics","Hematopathology","EDTA blood",1800,2880],
  ["Q4_MPL_MUTATION","MPL Mutation Analysis","Molecular Diagnostics","Hematopathology","EDTA blood",1800,2880],
  // Cardiology
  ["Q4_HOLTER_24H","24 Hour Holter Monitoring","Cardiology","Cardiology","Physiologic test",1200,1920],
  ["Q4_HOLTER_48H","48 Hour Holter Monitoring","Cardiology","Cardiology","Physiologic test",1800,2880],
  ["Q4_AMBULATORY_BP","24 Hour Ambulatory Blood Pressure Monitoring","Cardiology","Cardiology","Physiologic test",900,1440],
  ["Q4_TMT","Treadmill Test / Exercise Stress Test","Cardiology","Cardiology","Physiologic test",1000,1600],
  ["Q4_STRESS_ECHO","Stress Echocardiography","Cardiology","Cardiology","Imaging",2500,4000],
  ["Q4_FETAL_ECHO","Fetal Echocardiography","Cardiology","Cardiology","Imaging",1800,2880],
  ["Q4_ECHO_3D","Three Dimensional Echocardiography","Cardiology","Cardiology","Imaging",2200,3520],
  ["Q4_ECHO_STRain","Global Longitudinal Strain Echocardiography","Cardiology","Cardiology","Imaging",2200,3520],
  ["Q4_TROPONIN_I_HS","High Sensitivity Troponin I","Cardiology","Cardiology","Serum",700,1120],
  ["Q4_NT_PROBNP","NT-proBNP","Cardiology","Cardiology","Serum",1000,1600],
  ["Q4_LIPOPROTEIN_A","Lipoprotein(a)","Cardiology","Cardiology","Serum",600,960],
  ["Q4_APOLIPOPROTEIN_B","Apolipoprotein B","Cardiology","Cardiology","Serum",600,960],
  // Neurology / neurophysiology
  ["Q4_EEG_SLEEP","Sleep EEG","Neurophysiology","Neurology","EEG",1200,1920],
  ["Q4_VIDEO_EEG_4H","Video EEG 4 Hour","Neurophysiology","Neurology","EEG",2500,4000],
  ["Q4_VIDEO_EEG_24H","Video EEG 24 Hour","Neurophysiology","Neurology","EEG",4500,7200],
  ["Q4_NCS_UPPER_LIMB","Nerve Conduction Study Upper Limbs","Neurophysiology","Neurology","Physiologic test",1200,1920],
  ["Q4_NCS_LOWER_LIMB","Nerve Conduction Study Lower Limbs","Neurophysiology","Neurology","Physiologic test",1200,1920],
  ["Q4_NCS_ALL_LIMBS","Nerve Conduction Study Four Limbs","Neurophysiology","Neurology","Physiologic test",1800,2880],
  ["Q4_RNS","Repetitive Nerve Stimulation","Neurophysiology","Neurology","Physiologic test",1200,1920],
  ["Q4_SSEP","Somatosensory Evoked Potentials","Neurophysiology","Neurology","Physiologic test",1200,1920],
  ["Q4_VEP","Visual Evoked Potentials","Neurophysiology","Neurology","Physiologic test",1000,1600],
  ["Q4_BAEP","Brainstem Auditory Evoked Potentials","Neurophysiology","Neurology","Physiologic test",1000,1600],
  ["Q4_MEP","Motor Evoked Potentials","Neurophysiology","Neurology","Physiologic test",1800,2880],
  ["Q4_POLYSOMNOGRAPHY","Overnight Polysomnography","Sleep Medicine","Sleep Medicine","Sleep study",2500,4000],
  ["Q4_CPAP_TITRATION","CPAP Titration Sleep Study","Sleep Medicine","Sleep Medicine","Sleep study",2200,3520],
  ["Q4_MSLT","Multiple Sleep Latency Test","Sleep Medicine","Sleep Medicine","Sleep study",2500,4000],
  ["Q4_MWT","Maintenance of Wakefulness Test","Sleep Medicine","Sleep Medicine","Sleep study",2200,3520],
  // Ophthalmology
  ["Q4_OCT_MACULA","OCT Macula","Imaging","Ophthalmology","Imaging",1000,1600],
  ["Q4_OCT_OPTIC_NERVE","OCT Optic Nerve/RNFL","Imaging","Ophthalmology","Imaging",1000,1600],
  ["Q4_VISUAL_FIELD","Automated Perimetry / Visual Field","Imaging","Ophthalmology","Physiologic test",800,1280],
  ["Q4_CORNEAL_TOPOGRAPHY","Corneal Topography","Imaging","Ophthalmology","Imaging",800,1280],
  ["Q4_PACHYMETRY","Corneal Pachymetry","Imaging","Ophthalmology","Imaging",500,800],
  ["Q4_FUNDUS_FLUORESCEIN","Fundus Fluorescein Angiography","Imaging","Ophthalmology","Imaging",1500,2400],
  ["Q4_ICG_ANGIOGRAPHY","Indocyanine Green Angiography","Imaging","Ophthalmology","Imaging",1800,2880],
  ["Q4_ELECTRORETINOGRAPHY","Electroretinography","Neurophysiology","Ophthalmology","Physiologic test",1800,2880],
  // ENT / audiology
  ["Q4_PURE_TONE_AUDIOMETRY","Pure Tone Audiometry","ENT","Audiology","Physiologic test",400,640],
  ["Q4_IMPEDANCE_AUDIOMETRY","Impedance Audiometry","ENT","Audiology","Physiologic test",500,800],
  ["Q4_TYMPANOMETRY","Tympanometry","ENT","Audiology","Physiologic test",400,640],
  ["Q4_OAE","Otoacoustic Emissions","ENT","Audiology","Physiologic test",700,1120],
  ["Q4_BERA","BERA / Auditory Brainstem Response","ENT","Audiology","Physiologic test",1200,1920],
  ["Q4_VESTIBULAR_VNG","Videonystagmography","ENT","Audiology","Physiologic test",1800,2880],
  ["Q4_VESTIBULAR_VHIT","Video Head Impulse Test","ENT","Audiology","Physiologic test",1500,2400],
  // Fertility / reproductive medicine
  ["Q4_AMH","Anti-Mullerian Hormone","Endocrinology","Reproductive Medicine","Serum",900,1440],
  ["Q4_SEMINAL_ANALYSIS_ADVANCED","Advanced Semen Analysis","Clinical Pathology","Andrology","Semen",800,1280],
  ["Q4_SEMINAL_DNA_FRAGMENTATION","Sperm DNA Fragmentation Index","Clinical Pathology","Andrology","Semen",2500,4000],
  ["Q4_SPERM_SURVIVAL","Sperm Survival Test","Clinical Pathology","Andrology","Semen",800,1280],
  ["Q4_SPERM_ANTIBODY","Anti-Sperm Antibody","Immunology","Andrology","Semen/serum",1200,1920],
  ["Q4_PREGNANCY_BETA_HCG_QUANT","Quantitative Beta hCG","Endocrinology","Reproductive Medicine","Serum",350,560],
  ["Q4_PRENATAL_SCREENING_FIRST_TRIMESTER","First Trimester Prenatal Screening","Molecular Diagnostics","Fetal Medicine","Maternal blood",1800,2880],
  ["Q4_NIPT","Non-Invasive Prenatal Testing","Molecular Diagnostics","Fetal Medicine","Maternal blood",4500,7200],
  // Toxicology / therapeutic drug monitoring
  ["Q4_PARACETAMOL_LEVEL","Paracetamol Level","Toxicology","Clinical Toxicology","Serum",600,960],
  ["Q4_VALPROATE_LEVEL","Valproate Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_CARBAMAZEPINE_LEVEL","Carbamazepine Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_PHENYTOIN_LEVEL","Phenytoin Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_PHENOBARBITONE_LEVEL","Phenobarbital Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_DIGOXIN_LEVEL","Digoxin Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_LITHIUM_LEVEL","Lithium Level","Therapeutic Drug Monitoring","Clinical Pharmacology","Serum",600,960],
  ["Q4_TACROLIMUS_LEVEL","Tacrolimus Level","Therapeutic Drug Monitoring","Transplant Medicine","EDTA blood",1000,1600],
  ["Q4_CYCLOSPORINE_LEVEL","Cyclosporine Level","Therapeutic Drug Monitoring","Transplant Medicine","EDTA blood",1000,1600],
  // Nutrition / vitamins
  ["Q4_VITAMIN_B1","Vitamin B1","Vitamins & Nutrition","Nutrition","Whole blood",800,1280],
  ["Q4_VITAMIN_B6","Vitamin B6","Vitamins & Nutrition","Nutrition","Serum",800,1280],
  ["Q4_VITAMIN_A","Vitamin A","Vitamins & Nutrition","Nutrition","Serum",800,1280],
  ["Q4_VITAMIN_E","Vitamin E","Vitamins & Nutrition","Nutrition","Serum",800,1280],
  ["Q4_ZINC","Serum Zinc","Vitamins & Nutrition","Nutrition","Serum",500,800],
  ["Q4_COPPER","Serum Copper","Vitamins & Nutrition","Nutrition","Serum",500,800],
  ["Q4_SELENIUM","Serum Selenium","Vitamins & Nutrition","Nutrition","Serum",800,1280],
  ["Q4_HOMOCYSTEINE","Homocysteine","Vitamins & Nutrition","Nutrition","Serum",600,960],
  // Advanced imaging
  ["Q4_CT_CORONARY_ANGIOGRAPHY","CT Coronary Angiography","Radiology","Radiology","Imaging",3000,4800],
  ["Q4_CT_PULMONARY_ANGIOGRAPHY","CT Pulmonary Angiography","Radiology","Radiology","Imaging",2500,4000],
  ["Q4_CT_AORTOGRAPHY","CT Aortography","Radiology","Radiology","Imaging",2800,4480],
  ["Q4_CT_ENTEROGRAPHY","CT Enterography","Radiology","Radiology","Imaging",2500,4000],
  ["Q4_CT_COLONOGRAPHY","CT Colonography","Radiology","Radiology","Imaging",2200,3520],
  ["Q4_CT_PERFUSION_BRAIN","CT Brain Perfusion","Radiology","Radiology","Imaging",2500,4000],
  ["Q4_MRI_PROSTATE_MULTIPARAMETRIC","Multiparametric MRI Prostate","MRI","Radiology","Imaging",3000,4800],
  ["Q4_MRI_RECTUM","MRI Rectum","MRI","Radiology","Imaging",2500,4000],
  ["Q4_MRI_ENTEROGRAPHY","MR Enterography","MRI","Radiology","Imaging",2800,4480],
  ["Q4_MRI_CARDIAC","Cardiac MRI","MRI","Radiology","Imaging",4000,6400],
  ["Q4_MRI_FETAL","Fetal MRI","MRI","Radiology","Imaging",3000,4800],
  ["Q4_MRI_BREAST_DYNAMIC","Dynamic Contrast Breast MRI","MRI","Radiology","Imaging",3000,4800],
  ["Q4_MR_SPECTROSCOPY_BRAIN","MR Spectroscopy Brain","MRI","Radiology","Imaging",2500,4000],
  ["Q4_MR_TRACTOGRAPHY","MR Tractography","MRI","Radiology","Imaging",2500,4000],
  ["Q4_DWI_WHOLE_BODY","Whole Body Diffusion MRI","MRI","Radiology","Imaging",3500,5600],
  // Nuclear medicine
  ["Q4_THYROID_SCAN","Thyroid Scan","Nuclear Medicine","Nuclear Medicine","Imaging",900,1440],
  ["Q4_THYROID_UPTAKE","Radioactive Iodine Thyroid Uptake","Nuclear Medicine","Nuclear Medicine","Imaging",1200,1920],
  ["Q4_RENAL_DTPA_SCAN","DTPA Renal Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1500,2400],
  ["Q4_RENAL_EC_SCAN","EC Renal Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1500,2400],
  ["Q4_DMSA_RENAL_SCAN","DMSA Renal Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1500,2400],
  ["Q4_HIDA_SCAN","Hepatobiliary HIDA Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1500,2400],
  ["Q4_MUGA_SCAN","MUGA Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1800,2880],
  ["Q4_VQ_SCAN","Ventilation Perfusion Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1800,2880],
  ["Q4_PARATHYROID_SCAN","Parathyroid Scan","Nuclear Medicine","Nuclear Medicine","Imaging",1500,2400],
  ["Q4_GALLIUM_SCAN","Gallium Scan","Nuclear Medicine","Nuclear Medicine","Imaging",2200,3520],
  ["Q4_PET_CT_FDG","FDG PET-CT","Nuclear Medicine","Nuclear Medicine","Imaging",7000,11200],
  ["Q4_PET_CT_PSMA","PSMA PET-CT","Nuclear Medicine","Nuclear Medicine","Imaging",7500,12000],
  ["Q4_PET_CT_DOTATATE","Ga-68 DOTATATE PET-CT","Nuclear Medicine","Nuclear Medicine","Imaging",7500,12000],
  ["Q4_PET_CT_FAPI","FAPI PET-CT","Nuclear Medicine","Nuclear Medicine","Imaging",8000,12800],
];

const investigations: Seed[] = rows.map(([code,name,category,department,specimen,sms,corp]) => ({
  code, name, category, department, specimen, sms, corp,
}));

async function main() {
  let added = 0;
  for (const item of investigations) {
    const rate = Math.round(item.sms + (item.corp - item.sms) * 0.65);
    const existing = await prisma.investigationMaster.findUnique({ where: { code: item.code } });
    await prisma.investigationMaster.upsert({
      where: { code: item.code },
      update: {
        name: item.name,
        shortName: item.name,
        category: item.category,
        department: item.department,
        specimen: item.specimen,
        smsBenchmarkRate: item.sms,
        corporateBenchmarkRate: item.corp,
        rate,
        pricingLastVerifiedAt: new Date(),
        active: true,
      },
      create: {
        code: item.code,
        name: item.name,
        shortName: item.name,
        category: item.category,
        department: item.department,
        specimen: item.specimen,
        aliases: "",
        smsBenchmarkRate: item.sms,
        corporateBenchmarkRate: item.corp,
        rate,
        pricingLastVerifiedAt: new Date(),
        active: true,
      },
    });
    if (!existing) added++;
  }
  console.log(`Quaternary Investigation Master expansion: ${investigations.length} processed, ${added} new entries.`);
}

main().catch(console.error).finally(async () => prisma.$disconnect());
